### ISSUE TITLE
Change in Emoji colour texture

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#100]
When we type a emoji in the chatbox, the texture colour of it changes from yellow to somewhat white.

![Screenshot_2020-07-09-14-14-19-665_net froemling bombsquad](https://user-images.githubusercontent.com/42458260/87018297-adc57e80-c1ee-11ea-81d9-a8ffe78588cd.jpg)

**Comment by efroemling** [comment]
Thanks for the reminder that this was in there. I went ahead and disabled this behavior in commit 98272fff4897a78e2b79869b738c75055a3dddd2 so they should now show up in full color.

I had added this behavior a long time ago to help prevent colorful emoji from being distracting on in-game text/etc. But now I'm thinking it just looks dumb; I'd rather just disable emoji in specific places in the game if bright/distracting colors are a distraction..
