### ISSUE TITLE
Enhancement of log file

### ISSUE THREAD

**Issue by Gengar-lab** [efroemling/ballistica#102]
Suppose I have three mod files x, y, and z , and y has some code error. 

When we Open BombSquad, the Mods folder is executed. At this time, the error arises that "Error(s) Scanning scripts, see log files. When we check log file, we should have the content like:

x is working properly.... 

y has error!!!
Traceback [most recent call last] :
Error in line 36 of ba.py....... 
(All errors that are given by python compiler) 

z is working properly..... 

So it will be easy to debug and solve errors and check what is wrong and in which file.

**Comment by Dliwk** [comment]
Let's move it to #101
