### ISSUE TITLE
someone hacked my account please help bro

### ISSUE THREAD

**Issue by sahil0098** [efroemling/ballistica#103]
@efroemling Het
![Screenshot_20200710-024951](https://user-images.githubusercontent.com/44600877/87091883-1137c680-c258-11ea-9372-f0c68e3f591d.png)
 eric someone was hacked my account and linked his account with my account and use some mods to ban the unlink system for 99999days and i need to unlink that hacker plus i need to link with my new pc because my account already linked with 5accounts already please help me bro my google play games id is Dragonloop196 and my gmail is r7835885767@gmail.com please remove that  ban so i can link my account and unlink that hacker account. i am waiting for removing that hacker from account and make the 24/7 dedicated server and play the bombsquad on pc by linking with my main account.

**Comment by PythonCode-blip** [comment]
that is a bug not a hacker @sahil0098 it happened to me too but it isn't a hacker

**Comment by sahil0098** [comment]
It's not a bug bro it's an rule if someone try to use script in their account that would be stuck like this i want an creator reply who could fix this

**Comment by Akshay-Y7** [comment]
Same with me! But i know why its because my one id was banned when i was a beginner here XD so you need to contact eric at [support@froemling.net](url)

**Comment by EternalARK** [comment]
Same problem here.....

**Comment by efroemling** [comment]
Yes you'll get this if any of your linked accounts was flagged for hacking at any point. Send me an email at support@froemling.net and I can check into it.

**Comment by sahil0098** [comment]
@efroemling Reply me on support why you closed this topic

**Comment by alicerunsonfedora** [comment]
@sahil0098 I could probably take a guess here as to why the topic is closed:

- This isn't a bug report. Issues on most repositories like this one are for bugs that need to be addressed (or should be addressed) in the code.
- This (potentially) involves discussing private information. You shouldn't be using public spaces like GitHub issues to discuss things with private information (or even security vulnerabilities, for that matter. Thankfully, GitHub has addressed that: [Creating a security advisory][secad]).

[secad]: https://docs.github.com/en/github/managing-security-vulnerabilities/creating-a-security-advisory

**Comment by efroemling** [comment]
Yes this is correct. Things like this should go through the support email since they are related to accounts/security. This issues list is more for things like game bugs and features.
