### ISSUE TITLE
Game Closing

### ISSUE THREAD

**Issue by LucasRibeiro1024b** [efroemling/ballistica#105]
When I try to play a campaing, when the first match ends my game close, it occurs every time.

**Comment by efroemling** [comment]
Which version are you running? (should be at the bottom right on the main menu)

**Comment by efroemling** [comment]
This sounds like an issue that was fixed several versions back, so I'm wondering if you're just running an old build.. Please let me know if you can check the version number, otherwise I'll close this soon.
