### ISSUE TITLE
Can you please add an option for disabling the running in the punch and grab button

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#107]
I am using a separate running button just to run, but everytime when i need to do a punch/grab 360 degree move, i keep activating the hold event accidentally when i keep the punch and grab held for too long, It is really driving me nuts. Because of this, many times the 360 or 180 spin gets cancelled out, several times, and if i need to do a punch in the opposite direction, i cannot because, i need to release the run key, then the grab key, then the punch key.  Or the R and punch, or the run and grab. 

Please add an option if possible. I know that this is too complicated to do since the game revolves around android players. I dont want it to be disabled for everyone because then it would make things even more complicated. I just want it disabled for keyboard players, as an option, in the keyboard settings tab.

**Comment by efroemling** [comment]
I do think this is a good idea. I'll leave this open and will try to get to it at some point (or get more of the low-level engine source code uploaded so other people can) 👍

**Comment by TornadoesPride** [comment]
@astrojade ever heard of the SHIFT key near the arrow keys? Am a keyboard player on both android and pc and I use the SHIFT key with grab and punch for running and all my moves the stunts everything is working fine as best it should.... Consider using the SHIFT and control when you'll use the PUNCH or GRAB key... else it'll keep driving you nuts

**Comment by astrojade** [comment]
@TornadoesPride Yes i already have a separate button for running and Yes, i am aware about the shift key, Thanks for the information. Nope, i am not telling eric to completely disable the running keys in grab/ punch button for keyboard/controller players. This is not what i want eric to do.  If this is done, then yes, like you said, it will be a total disaster. 

Yes, i want eric to make an option (like a checkbox), allowing us to choose whether we want the running in the punch and grab keys or not, and this option should only be for keyboard/ controller players. This option should be disabled for android players because there is technically no separate button for running in the android controls.
