### ISSUE TITLE
İntel gpu problem on windows10

### ISSUE THREAD

**Issue by MythB** [efroemling/ballistica#111]
Game is working on intel gpu in default settings.(Laptop)
When game working on intel gpu,
Which is Intel(R) UHD Graphics 630 with latest firmware
I can't screenshot in fullscreen mode. When i try only  seen desktop without the game screen.
And in window mode this weird graphical glitch happening. 
I have rtx2060 too and is fine everthings works perfect so far
![ss1](https://user-images.githubusercontent.com/22128319/87489221-22634780-c64b-11ea-920b-ffdfb72896ef.jpg)

**Comment by EternalARK** [comment]
It's fixed in the latest beta version intel driver.
