### ISSUE TITLE
REGARDING INPUT ACCEPTED AT SAME TIME

### ISSUE THREAD

**Issue by PuneetGurjar** [efroemling/ballistica#113]
how many inputs can be accepted at a same time or within 1-2 seconds.  

so far i tried a lot and can say that maximum of 4 inputs can be accepted

**Comment by efroemling** [comment]
Could you clarify a bit what you mean here?

**Comment by PuneetGurjar** [comment]
That if we want to perform any skill which includes many controls to be controlled at same time we need to remove our control from directions

**Comment by efroemling** [comment]
And do you mean with the keyboard, touch-screen, gamepad?... I imagine all of those might have different limits on how many inputs can be detected at once. The game itself imposes no limits on that though; it is whatever the device/operating-system allows...

**Comment by PuneetGurjar** [comment]
No its same for any device
