### ISSUE TITLE
Weird Bomb Direction change

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#114]
Case 1:

This bug has happened with me 2 to 3 times. When we punch a bomb which is coming towards ourself, if we punch it, At normal cases its direction should now be opposite i.e. in direction of punch, but at certain angles of punch, it speed towards the direction it was going(coming towards us) increases.

You can see the [video](https://drive.google.com/file/d/1ud_h_wShGSiMBjPsNsXdy9QNtVbPnFUQ/view?usp=drivesdk).

Case 2:

When the Mel Bot is just going to spawn sticky bomb and I punch him at his head somewhat between the head and the bomb spawn location(which is above our heads), the sticky bomb flies with high speed, like in the previous video when I punched the bomb, but now in the direction of punch, instead of sticking to my hand.
[Video](https://drive.google.com/file/d/1yTKbvKYK7BMSrcNWCGNGW1eGGJcQD_Oc/view?usp=drivesdk) of Mel.

**Comment by efroemling** [comment]
Interesting; thanks for the heads-up. That certainly looks like some bad math. If somebody wants to debug this, I believe all of the punch physics is handled in the scripting layer (look for PunchHitMessage in spaz.py). I would add a print statement in to show all the values that are going into the hit-message that it generates. I would expect one of these values to be unusually high for a punch such as this. It would be interesting to see where that is coming from. Perhaps we can add a clamp or something.

I'll leave this open and try to look into it eventually but physics fixes are pretty low priority for me at the moment compared to all the other stuff I've got on my list.

**Comment by TornadoesPride** [comment]
@efroemling  I can assure you that it happens due the punch being affected on the side of the bomb, hope you played 8-ball pool game before as the ball tends to move towards the resultant direction, like the angle where its being hit on, with how much force you're using..... so similarly the bomb was punched back of the bomb with the gloves(now that would be a powerful punch) hence the game doesnt really care which way the player is facing, it follows the physics . It's a common misconception of AM FACING TOWARDS THE GOAL POST WHY IS THE BALL GOING THE OTHER WAY🙂.... Hope you understood this @Benefit-Zebra if not, I can hit you up with bomb punch tutorials ♥️
