### ISSUE TITLE
Android TV version on Sony Bravia no more working

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#117]
Here my experience on Android TV version on Sony Bravia. First time i played bombsquad was on our brand new Sony TV. I found bombsquad by accident in the play store. At the beginning i had a lot of fun playing with my kids locally with three PS4-Controller and also multiplayer FFA-mode via internet. 
This worked fine until i got an update of OS of the TV. After the update the sound (TV loudspeaker, sound output of TV and sound output of the Controller) was lost in bombsquad. At this point Sony stopped the roll out of the new OS-Version. After a year or so, there was another update. After that the sound was back but the PS4-Controller via  blue tooth didnt work correct. There was a huge lag (0,5 to 1 second for one command) for the controller commands while navigating in the TV-Menu but also in bombsquad. That means, the bombsquad is no more playable. Since that time i play bombsquad on my notebook, where it works perfect. Only sometimes there is some lag if i have a bad internet connection. But i think this is a problem for all games and located in the www. I dont know what Eric can do with with this field report. But its sad, that the Sony TV platform is lost for bombsquad. :-(
Now i will stop writing and, ..., launch bombsquad on my notebook: :-)

**Comment by efroemling** [comment]
Sorry to hear you are having problems.
Unfortunately there is not much I can do about controller lag, especially if you are seeing the same lag outside of BombSquad. The same with controller support. The game should support any controller recognized by Android but if a system update made a controller stop working then you'd have to talk to Sony to get that fixed (which doesn't seem very likely to happen sadly).
However, hopefully the upside is that there are test builds for Linux, Windows, and Mac, so perhaps you can play on your Notebook :)
https://files.ballistica.net/bombsquad/builds/

**Comment by chelikol** [comment]
I also think the problem exists outside of bombsquad. When I connect the PS4 controller with a USB cable, it works without delay, but unfortunately also without sound. :-( 
It's amazing anyway that it is possible to run a massively interactive software on so many different operating systems. Anyway, the notebook version works perfectly.

**Comment by efroemling** [comment]
Glad to hear at least the notebook version is working well. 👍
I'll go ahead and close this since it doesn't sound like there's anything else I can fix in regards to the bluetooth lag..

**Comment by chelikol** [comment]
In the following, here is another possibly enlightening information. I bought another one today to complement our PS4 controllers (snakebyte 29 euros) and connected it to the Sony Bravia Android TV for a test. It works perfectly. No blue-tooth lag and the sound also works. The original Sony controller doesn't work properly on the Sony TV, but works perfectly on the Windows PC. It seems that there is a compatibility problem between Sony Android TV and Sony PS4 controller. Very strange. But anyway, I can now play on TV and Windows notebook. By the way: I tried bombsquad on a chromebook for testing purposes. It worked, although the controller sensitivity of the analog stick seemed a bit strange to me.

Translated with www.DeepL.com/Translator (free version)
