### ISSUE TITLE
Enhancement Of Internal Game Keyboard

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#119]
@efroemling Since to use emojis, we need to turn off Internal Game Keyboard setting. How about BombSquad Having its own set of Emojis along with the standard emoji in Internal Game Keyboard of BombSquad. 

![Screenshot_2020-07-19-11-19-08-358_net froemling bombsquad](https://user-images.githubusercontent.com/42458260/87868313-2af0b080-c9b2-11ea-8d0e-eae418a1ec5c.jpg)

Which we can access through the Empty button beside the double quotes. 

Also like standard keyboard, when we double tap the Capital Up Arrow(Shift Arrow), all letters while typing remain CAPITAL nonstop. We should add this feature to Internal Game Keyboard also.

**Comment by PythonCode-blip** [comment]
Might be a good idea even though there's a mod for that in 1.4 but not for 1.5 so why not?

**Comment by efroemling** [comment]
This probably isn't something I can devote time to anytime soon but if someone would like to add such features to the internal keyboard (or port the aforementioned 1.4 mod to 1.5) I'd be happy to accept them here 👍.

**Comment by PythonCode-blip** [comment]
Yeah, well why is that empty button with no symbol there?

**Comment by efroemling** [comment]
> Yeah, well why is that empty button with no symbol there?

That's the shift key when the keyboard isn't in numbers/symbols mode.

**Comment by PythonCode-blip** [comment]
> > Yeah, well why is that empty button with no symbol there?
> 
> That's the shift key when the keyboard isn't in numbers/symbols mode.

Oh, after all this time trying to figure out I thought it was an upcoming feature.

**Comment by efroemling** [comment]
On the iOS keyboard (which I roughly modeled this one after) the shift key turns into a '#+=' button in that case which gives access to more symbols. I didn't take things that far though and just made it blank. But that'd be something else somebody could add if they felt like it... 😬

**Comment by Benefit-Zebra** [comment]
@efroemling Here is the updated [onscreenkeyboard.py](https://drive.google.com/file/d/1wIV7-m7w2XLsOgkbL9RSUlZBsmDunUae/view?usp=drivesdk). 

I cannot test it on android since there is no ba_meta tag for it now. Can you please try it.

**Comment by Benefit-Zebra** [comment]
@efroemling Here is the updated [onscreenkeyboard.py](https://drive.google.com/file/d/1wWwmea4IHWK6svlto7WQkFgcPTTDTMKp/view?usp=drivesdk) with BombSquad Emojis. 

I have not tested it, since on android there is no ba_meta tag for it now. Can you please try it.

**Comment by efroemling** [comment]
The emoji & caps-lock additions are now in 1.5.23 so I'll go ahead and close this. Feel free to open new issue(s) if there are more ideas/issues...
