### ISSUE TITLE
Error Server BombSquad Putty Linux

### ISSUE THREAD

**Issue by JoseANG3L** [efroemling/ballistica#121]
Perform a method similar to the previous versions of BombSquad 1.4.155, install Python 3.7, also the libraries, (this method is 24/7), after that code it gives me that error. Any solution?
Thank you.

![IMG-20200719-WA0226](https://user-images.githubusercontent.com/57434391/87894924-bb0e1480-ca09-11ea-815b-3fcc7eafa0f9.jpeg)

**Comment by JoseANG3L** [comment]
You used the BombSquad_Server_Linux_1.5.22

**Comment by grishatop1** [comment]
I had the same problem. Here is how I fixed it.

1. Update the packages list
`sudo apt update`
`sudo apt install software-properties-common`

1. Next, add the deadsnakes PPA to your sources list:
`sudo add-apt-repository ppa:deadsnakes/ppa`
And then press ENTER to continue.

1. Install python with:
`sudo apt install python3.7`

That should help.

**Comment by bseditor** [comment]
@JoseANG3L run it with following cmds:
1. python3.7 -o ./bombsquad_server OR
2. python3.7 ./bombsquad_server

**Comment by JoseANG3L** [comment]
In the end I got it, thank you very much, the steps are as follows:

1. Update the packages list:
`sudo apt update`

2.  Install python with:
`sudo apt install python3.7`

3. Install libpython with:
`sudo apt-get install libpython3.7`

4. Enter the server folder:
`cd _server_`

5. Login to tmux:
`tmux`

6. Run the following commands:
`chmod 777 bombsquad_server`
`chmod 777 config.yaml`

To execute the following command you must enter the dist folder.
`cd dist`
then
`chmod 777 bombsquad_headless`

7. We go back to the server folder and run it with:
`python3.7 ./bombsquad_server`

**Notes:**
- To stop the server use **Ctrl+Z** or **Ctrl+C**

**Comment by efroemling** [comment]
Sorry I hadn't responded to this; I think the original error you were seeing was fixed in a recent [pull request](https://github.com/efroemling/ballistica/pull/115) and should be fixed in the latest 1.5.23 builds.
Basically, the 'bombsquad_server' script was trying to execute itself using a command called 'python3.7 -o', when the intention was for it to execute with 'python3.7' with an '-o' argument.

**Comment by efroemling** [comment]
I'll go ahead and close this as I think it's fixed; feel free to re-open if not.

**Comment by JoseANG3L** [comment]
I already tried the new version 1.5.23 and it requires the same steps.

**Comment by efroemling** [comment]
You will still need to have Python 3.7 installed, but once that is the case then you should be able to just run ./bombsquad_server and it should work. (no need to run 'python3.7 ./bombsquad_server'). Please let me know if that is not the case.

**Comment by JoseANG3L** [comment]
When installing Python 3.7 and running it with ./bombsquad_server, ask for the following library
libpython3.7
when that library is installed and run again with ./bombsquad_server, the error in the image above appears, it only works for me with the python3.7 ./bombsquad_server command.

**Comment by efroemling** [comment]
What is the first line of your bombsquad_server file? That line is the command that the script uses to run itself. It should be `#!/usr/bin/env -S python3.7 -O`

So you are seeing that line and ./bombsquad_server still fails?
If so, try changing the line to `#!/usr/bin/env python3.7` and let me know if that works.

**Comment by JoseANG3L** [comment]
The first command did not work, the second gave this result.

To install python3.7 use the following command:
`sudo apt install python3.7`
![error](https://user-images.githubusercontent.com/57434391/88496109-b6091200-cf81-11ea-8e51-f103e4b56730.jpg)
