### ISSUE TITLE
Hook of filter_chat_message failed

### ISSUE THREAD

**Issue by EternalARK** [efroemling/ballistica#125]
Occurred since version 1.5.23.

**Comment by efroemling** [comment]
Can you provide the error output/traceback/etc? I don't think any of that code changed between 1.5.22 but happy to look into it.

**Comment by EternalARK** [comment]
I've tested, it's no use even in this case.
![image](https://user-images.githubusercontent.com/30522559/88458693-7d563380-cec2-11ea-858c-f0f3d8db2245.png)
Console does no response.

**Comment by efroemling** [comment]
I just tested it and it worked for me.
Are you perhaps running into [this](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#python-cache-files-gotcha)?
You can also add a print() at the top level of _hooks.py to make sure that the file you are editing is the one the game is seeing.

**Comment by EternalARK** [comment]
Got the problem. The internal __pycache__ does not update with the py automatically, so I deleted the folder. It worked.
