### ISSUE TITLE
Problems with OpenAL

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#128]
Sometimes I get segmentation fault in `ballistica::AudioServer::UpdateAvailableSources()` when closing game, but I can't reproduce this :(

**Comment by efroemling** [comment]
Thanks for the info. I'll see if I can see any potential problems in that function. Is there any more info included with the crash? And which platform is this on?

**Comment by Dliwk** [comment]
I tried to reproduce this in debug build for more info, but now I don't get crashes. And I ran into this on linux.

**Comment by Dliwk** [comment]
Game crashed after closing again (thread 16).
![изображение](https://user-images.githubusercontent.com/47295209/89881489-41afaf00-dbce-11ea-92dd-8d96da967984.png)

Could this be an OpenAL/Pulse bug?

**Comment by Dliwk** [comment]
Hmm
![изображение](https://user-images.githubusercontent.com/47295209/92797652-f0f0c900-f3ba-11ea-80f9-6ee3401eabd6.png)

**Comment by Dliwk** [comment]
I don't see it anymore for a long time, had to be problem on my side.
