### ISSUE TITLE
Python modules unusual behaviour

### ISSUE THREAD

**Issue by mehulpoddar** [efroemling/ballistica#138]
I'll break my question down into two parts :

1) How to create custom user scripts directory?
What I did was to check the `ba.App.python_directory_user`, and then copy the 4 directories inside `ba_data\python` (the app scripts directory) to the `python_directory_user`.
When I checked `ba.__file__`, it comes from the `python_directory_user`, so it seems correct, but could someone confirm if this is correct?

2) **The Main question**
The code changes I make in the `python_directory_user` **do not reflect!**
I tried renaming files and directories in this path, then the .exe fails with an error, which proves that the .exe is using these files, but it does not use the code inside these files! :/
For example, I changed a function name in a file and with the renaming file technique I confirmed game is crashing without the correct name, proving that this file is being used, but the changed function name is never reflected. When I try to call the function through telnet terminal, it only gets called with the old function name and not the changed function name!

Can anybody explain this odd behaviour?
Thank you in advance!

**Comment by Dliwk** [comment]
1. To 'replace' app python files, you need to copy them to `os.path.join(ba.app.python_directory_user, "sys", ba.app.version)`
2. It seems like [this](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#python-cache-files-gotcha).

**Comment by mehulpoddar** [comment]
1. Do I need to append the "/sys/<version>", even when I'm doing this on PC?
2. Thank you so much, I think this should resolve it.

**Comment by efroemling** [comment]
A few notes:
- Yes you need to append the sys/<version> even for PC; I wanted to make it somewhat difficult to break new versions of the game by keeping out-of-date overridden system scripts lying around, so each new build needs to be explicitly overridden.
- If you want to debug where scripts are loading from, do: `import sys; print(sys.path)` to see the directory load order or for a loaded module 'foo', `print(foo.__file__)`
- As a shortcut, you can run `import ba.modutils; ba.modutils.create_user_system_scripts()` to copy a complete set of system scripts into the right place in your mods dir. or `ba.modutils.delete_user_system_scripts()` to clean it up.

**Comment by efroemling** [comment]
Going to close this; feel free to re-open if anything is still unclear...

**Comment by Benefit-Zebra** [comment]
The same happened with me. I copied all 4 folders ba, bacommon, bastd, efro to BombSquad/sys/1.5.24/.When I opened BombSquad, the folders got compiled, but the changes didn't reflected.
