### ISSUE TITLE
ucrtbased.dll required in Windows debug build

### ISSUE THREAD

**Issue by abhinaypandey02** [efroemling/ballistica#140]
Windows release build working fine but not the debug build

**Comment by Dliwk** [comment]
Looks same as #54. This just needs to be configured so that required debug version of libs are automatically included with ballistica debug builds.

**Comment by efroemling** [comment]
Ok thanks for the heads-up; I'll try to get this added. Alongside the Python 3.8 update I switched windows debug builds to use debug versions of the Python libraries, which might mean that there are other debug libraries such as this that are needed now too.

**Comment by efroemling** [comment]
ucrtbased.dll should now be bundled for windows debug prefab builds. Can you confirm whether this fixes the problem for you or if it complains about anything else missing?

**Comment by abhinaypandey02** [comment]
> ucrtbased.dll should now be bundled for windows debug prefab builds. Can you confirm whether this fixes the problem for you or if it complains about anything else missing?

Yes it's fixed and no other DLL is being asked about. I tried to manually add ucrtbased.dll earlier but the debug version used to throw an error and I thought it might be because of my DLL. But your DLL version is also throwing that error in the debug version (release build working fine). It's not related to DLL so I will start a new issue for that. Thank you for fixing DLLs
