### ISSUE TITLE
Android Version can't Open HTTPS link

### ISSUE THREAD

**Issue by EternalARK** [efroemling/ballistica#144]
![Screenshot_2020-08-02-22-33-39-730_net froemling bombsquad](https://user-images.githubusercontent.com/30522559/89125413-f695ed80-d4a3-11ea-993a-bcbbc90738c0.png)
It's from Internal library I guess.

**Comment by efroemling** [comment]
This is a known issue. The version of Python used by the Android version is custom built (based on the build setup from [here](https://github.com/yan12125/python3-android)) and I'm not sure what it would take to get its SSL stuff working properly.  Perhaps someone who knows security stuff better than me can help out.

**Comment by Dliwk** [comment]
If I'm not wrong, https now works fine on Android, so I'll close this.

**Comment by efroemling** [comment]
Yes https should now be working everywhere. Please holler if not.
