### ISSUE TITLE
Plugins reading the same file twice

### ISSUE THREAD

**Issue by abhinaypandey02** [efroemling/ballistica#145]
I have a mod that has a folder with __init__.py file. I made a simple plugin class in its __init__.py file and everything works fine. But what I guess is a little bug is that bombsquad is reading the same file twice, once taking the whole folder as plugin and second by taking __init__.py file as plugin.
I think there needs to be some sort of conditional statement to not import plugins if the file is __init__.py because it would be already imported as the whole folder.

![Screenshot (15)](https://user-images.githubusercontent.com/29501260/89159709-7f3c8880-d58d-11ea-9148-520b7d13b50a.png)

**Comment by Dliwk** [comment]
Hmm, It happens with all meta-exports in \_\_init\_\_.py files. As hotfix you can just remove them from \_\_init\_\_.py, e.g.
```python
"""BombSquad super awesome chat commands"""
from .plugin import ChatCommandsPlugin
```

**Comment by abhinaypandey02** [comment]
> Hmm, It happens with all meta-exports in __init__.py files. As hotfix you can just remove them from __init__.py, e.g.
> 
> ```python
> """BombSquad super awesome chat commands"""
> from .plugin import ChatCommandsPlugin
> ```

My purpose of chat commands is working even without making it a plugin too, as I am importing it from ba._hooks module.
I just wanted to report this little error for others to be helped.
