### ISSUE TITLE
Camera position and rotation

### ISSUE THREAD

**Issue by ghost** [efroemling/ballistica#148]
Can we get some features like a changing camera position and rotation of players from code

**Comment by astrojade** [comment]
See, Eric already has added a manual camera, where you can  control the camera, manually by attaching a mouse and keyboard, and clicking the f7 button to access manual camera while playing ingame.  You can rotate the camera how much you want (by clicking the alt and control keys), but when it comes to controlling the moving camera, which is following us everytime, its a very tedious task. 
Even i want this feature  where i can just zoom in, while this camera is moving soo that 
1) the camera keeps following me in a zoomed in position plus its not static(fixed position like manual camera)
2) Incase its too zoomed in, i just need to zoom out(mouse scroll), and the camera will behave like its normal self

And (1) and (2) should both be done without enabling manual camera

But like i said, i dont know the coding, this may be good in theory, but beyond difficult too code. Soo yea theoretical idea.

**Comment by DrovGamedev** [comment]
@astrojade, thanks, I know

**Comment by efroemling** [comment]
I'll have to think a bit about this.

A fully scriptable camera does sound like a fun idea and could open up some fun new possibilities for mini-games or cut-scene type things and technically wouldn't be too hard to do. However, the one major downside is that the game doesn't always even have direct control of the camera. For instance, in the VR versions of the game, the player is free to move their head wherever they want. If there is an AR version of the game in the future it would be similar. So any minigame/etc. that made heavy use of custom camera positions/etc. would likely look broken on these versions of the game (or would need a way to prevent those players from accessing that mini game).

The idea of allowing a bit of user control over the camera such as zooming in could be interesting though (at least in cases such as phones where there is a single person playing on it). Currently the game simply maintains 'areas of interest' which are points in space with a radius. Each spaz generally has one of these and certain other objects such as flags or pucks do too. The camera then tries to keep all areas of interest fully on-screen. Maybe we could do something like have the option to 'zoom in' to frame only areas of interest representing a player on that local device or something like that... 🤔

**Comment by Dliwk** [comment]
What about opening (part of) the source code now, what prevents this? People can play with the camera themselves :smile:

**Comment by efroemling** [comment]
Nothing prevents this; I'm hoping to do that as soon as I can find the time. Basically in addition to the current 'prefab' builds I would like to have builds where some of the game is precompiled as a library but as much as possible of the C++ layer is open-sourced and user-buildable. All of the graphics layer including the camera should be open sourced.

**Comment by Dliwk** [comment]
#337 provided scriptable camera for local use (and it sounds like best possible thing at this point).
