### ISSUE TITLE
Sticky Bomb Gravitational Pull Bug (Assault)

### ISSUE THREAD

**Issue by PythonCode-blip** [efroemling/ballistica#150]
So when a Spaz goes towards the flag with a sticky bomb stuck to it's head, it goes to its original spawn point but goes to the opposite direction very fast and also more Spazes get interrupted and killed.

**Comment by efroemling** [comment]
Hmm; I assume the Spaz is getting teleported back to their home flag but the sticky bomb does not and the strong pull effect between them for at least a moment after that causes chaos. I imagine similar weirdness might occur if a player is being held as he touches the flag.
Ideally we'd probably want the sticky connection or the held-by-player connection to just drop cleanly in this case.. I'll mark this as a bug and hopefully we can improve this at some point..

**Comment by PythonCode-blip** [comment]
Thanks in advance!
