### ISSUE TITLE
Server builds not starting

### ISSUE THREAD

**Issue by abhinaypandey02** [efroemling/ballistica#154]
![IMG-20200805-WA0005.jpg](https://user-images.githubusercontent.com/29501260/89565584-63aad980-d83c-11ea-8e7a-9a32bec6e9a1.jpg)

The -S argument and -O argument causes problems. Removing both let's the server run fine

**Comment by efroemling** [comment]
It seems that versions of /usr/bin/env for linux before 2018 didn't support the -S argument. We use the -S argument to allow passing arguments to the interpreter (in this case -O which tells python to run in optimized mode). Without the -S, it interprets everything after the path as a single argument so /usr/bin/env then looks for a binary named "python3.8 -O" which of course does not exist.
(see "Character Interpretation" on [this page](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) for more info)

If you do `/usr/bin/env --version` I'm guessing you'll see a version below 8.30.  It sounds like that was the first one with support for -S.

As a workaround, you can either modify the script's shebang line to be `#!/usr/bin/env python3.8` or you can explicitly run `python3.8 -O ./bombsquad_server`. The first option means it will run in debug mode but that shouldn't make a huge difference (the server script simply launches the contained bombsquad binary which *will* be running optimized)
