### ISSUE TITLE
Android Telnet Issue

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#155]
When I Establish Telnet connection with BombSquad, BombSquad asks to allow telnet access, I tapped on allow. When I return back on Telnet screen, it asks for password which I don't know:

![IMG-20200701-WA0014](https://user-images.githubusercontent.com/42458260/86202698-a106b200-bb80-11ea-82da-68fa2133c376.jpg)

**Comment by Dliwk** [comment]
I think this isn't relevant, since telnet has been [disabled][commit].

[commit]: https://github.com/efroemling/ballistica/commit/0fc11b5712731e62b3448d13bae725202a02fa14
