### ISSUE TITLE
Add Copy Account id option

### ISSUE THREAD

**Issue by Gengar-lab** [efroemling/ballistica#156]
When we type 'getaccountid' in Settings/Advanced/Enter Code, We get our account id which is very long. I think adding a copy to clipboard option will be very useful.

**Comment by Benefit-Zebra** [comment]
But for people making server. Adding this option would directly be helpful.

**Comment by Dliwk** [comment]
Hi there, this feature was implemented in https://github.com/efroemling/ballistica/pull/503, so I'll close this.
