### ISSUE TITLE
Is it possible to add a search bar in the Server list(internet tab)?

### ISSUE THREAD

**Issue by Akshay-Y7** [efroemling/ballistica#157]
Finding a server in the list is super irritating! The servers just swich their positions according to the ping... Its so much irritating... It can be useful :D

**Comment by DrovGamedev** [comment]
it is possible

**Comment by abhinaypandey02** [comment]
https://github.com/ModSquadBS/Bombsquad-Community-Mods-V2/blob/master/mods/gather_search.py
A small mod by me. Enable in plugins menu.

**Comment by Akshay-Y7** [comment]
Yayyy horae :D Thanks btw :D
