### ISSUE TITLE
Edited Code Doesn't Give Any Effect

### ISSUE THREAD

**Issue by animemoeus** [efroemling/ballistica#158]
I was tried to edit the code located in `dist/ba_data/python/bastd/` on server version from [here](https://files.ballistica.net/bombsquad/builds/BombSquad_Server_Linux_1.5.23.tar.gz) but isn't give any effect.

What should I do?

**Comment by Dliwk** [comment]
It seems like [this](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#python-cache-files-gotcha).

You can just explicitly delete compiled .pyc files.
