### ISSUE TITLE
ba.stdobj() is throwing an error:

### ISSUE THREAD

**Issue by bseditor** [efroemling/ballistica#159]
Could someone tell me that why `ba.stdobj()` is throwing an err. 'ba has no attribute stdobj'  although its mentioned [here](https://files.ballistica.net/bombsquad/builds/CHANGELOG.md) that `bs.getSharedObject() is now ba.stdobj()`?
![Capture](https://user-images.githubusercontent.com/51753219/89860324-d9a69c00-dbc0-11ea-8c9d-1691e5ec6dfd.PNG)

**Comment by Benefit-Zebra** [comment]
Try using
 ```from bastd.gameutils import SharedObjects```

**Comment by bseditor** [comment]
@Benefit-Zebra I found in [Ballistica API](https://github.com/efroemling/ballistica/blob/master/docs/ba_module.md) but did'nt get any info related this therefore, I went to changelog.md. Btw thanks for your help.

**Comment by Benefit-Zebra** [comment]
> @Benefit-Zebra I found in [Ballistica API](https://github.com/efroemling/ballistica/blob/master/docs/ba_module.md) but did'nt get any info related to this

> (documentation of bastd module is still pending).

That what I said
