### ISSUE TITLE
How to run the linux server as a daemon?

### ISSUE THREAD

**Issue by amoghh** [efroemling/ballistica#167]
I ssh into my aws instance and run the server successfully.. but if i try to close my ssh connection the bombsquad server also shuts down.. how can i run it in the background?
i run the server using ./bombsquad_server

**Comment by efroemling** [comment]
That will happen with any program you run over an ssh connection; closing the connection will generally kill the running program, just as if you had closed a terminal window in the GUI. If you want to keep something running in the background I would suggest looking into ’screen’ or ’tmux’. Both of those let you run stuff and 'detach' from it so it keeps running in the background. You can then reattach later when you ssh back in.

Note to self/others: perhaps a tutorial page or [Knowledge Nuggets](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets) entry for this would be useful...

**Comment by amoghh** [comment]
Yes thanks a lot.. I managed to get it working using screen.. been a fan of yours since a long time had set up a server previously prior to version 1.5. I was using the nohup command to run the server init script in background which doesnt seem to work anymore. Got it working using screen. 
Also is it possible to run the script from the root using the path without going into the folder? if i try that i get yaml file not found.

P.S I cant wait for 2.0..

**Comment by efroemling** [comment]
Interesting; I'm not sure why the nohup method wouldn't work anymore. Perhaps this is related to how the server script uses the standard python interpreter now (code.interact()); perhaps that somehow prevents it from detaching from the launching terminal. Perhaps someone could experiment with disabling that code or other things to see if it works.

Also it *should* be possible to run the server script from any directory. At the bottom of the server script in the main() function the first thing it tries to do is change the current directory to where the script is. (os.chdir(...)).  Perhaps this is not working correctly if it can't find the yaml file though. I don't think that would be too hard to debug if you wanted to throw some print() statements in and see what's going wrong.

**Comment by Dliwk** [comment]
Gonna close this now because you have a workable solution.

I want to mention another way, this is systemd uint. Just an example:
```ini
# /etc/systemd/system/app_bombsquad.service
# ----------------------------------------------

[Unit]
Description=My super awesome BombSquad server

[Service]
ExecStart=/app/bombsquad/run.sh
User=app_bombsquad
Group=app_bombsquad
Restart=always

[Install]
WantedBy=default.target
```

```bash
# /app/bombsquad/run.sh
# ----------------------------------------------

# change directory to our home (/app/bombsquad)
cd

# launch server
./bombsquad_server
```

But bombsquad_server script closes immediately because of it gets EOF from stdin :( 
I use this dirty trick:

```python
# /app/bombsquad/bombsquad_server_launcher.py
# ----------------------------------------------
import subprocess

while True:
    try:
        process = subprocess.Popen(['./bombsquad_server'], stdin=subprocess.PIPE)
        process.wait()
    except KeyboardInterrupt:
        process.kill()
        break
```

This is a bit more secure because of server runs as another user:group and you no need to ~reinvent the wheel~ develop automated tmux/screen sessions controller.
