### ISSUE TITLE
Ovewrite powerupbox class

### ISSUE THREAD

**Issue by Al-Clouds** [efroemling/ballistica#170]
I want create a mod with more bombs but i need to create new class to implement new elements in. So i create a new file in mod file with new powerupbox class and i create a file for plugin.

(I don't want to modify game files, i just want create a mod which can be activate or desactivate by user)

###MyPlugin.py

```python
# ba_meta require api 6

from __future__ import annotations

from typing import TYPE_CHECKING

import ba

from powerupBoxFactoryNew import PowerupBoxNew, PowerupBoxFactoryNew

if TYPE_CHECKING:
    pass


# ba_meta export plugin
class MyPlugin(ba.Plugin):

    def on_app_launch(self) -> None:
        bastd.actor.powerupbox.PowerupBoxFactory = PowerupBoxFactoryNew
        bastd.actor.powerupbox.PowerupBox = PowerupBoxNew

```

I don't put the second file because it's exactly the thame as original.

When i activate a map in the game i verify when powerup spawn if the class called is mine but it always **<class 'bastd.actor.powerupbox.PowerupBox'>**

 I tried in my plugin to change to 
>```python  
>setattr(bastd.actor.powerupbox, 'PowerupBoxFactory,' PowerupBoxFactoryNew)
>setattr(bastd.actor.powerupbox, 'PowerupBox', PowerupBoxNew)
>```

Can someone hlep me to solve this problem?
How overide game class which will be applied to all bombsquad game (new game created AND campaign game)?
Thanks for your responces.

**Comment by DrovGamedev** [comment]
also redefine needed methods

**Comment by Al-Clouds** [comment]
For the moment i fix it by switch place of code in the _app.py file like this on_app_launch() function 
```python
self.load_plugins()
        for plugin in self.active_plugins.values():
            try:
                plugin.on_app_launch()
            except Exception:
                from ba import _error
                _error.print_exception('Error in plugin on_app_launch()')

        _achievement.init_achievements()
        spazappearance.register_appearances()
        _campaign.init_campaigns()
```

**Comment by Benefit-Zebra** [comment]
@Al-Clouds Powerups of Campaign game do not get change. Try using your script for Team game or FFA game.

**Comment by Mikahael** [comment]
A bit late to comment but agreed with zebra sir.
