### ISSUE TITLE
What happen to eric

### ISSUE THREAD

**Issue by YairMejiaValtierra** [efroemling/ballistica#173]
Why eric is inactive

**Comment by efroemling** [comment]
I've been doing a bit of traveling/vacationing in recent weeks so my work time has been a bit limited. I should be returning to my more regular updates soon...

**Comment by YairMejiaValtierra** [comment]
OMG, thank God you are OK I thought something might've happens to you Eric

**Comment by Benefit-Zebra** [comment]
I think this issue can be closed now.

**Comment by Dliwk** [comment]
Eric is alive; BombSquad is developing! :partying_face: :partying_face: :partying_face: :tada: :tada: :tada:
