### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by YairMejiaValtierra** [efroemling/ballistica#176]
![Screenshot_2020-09-01-20-33-03](https://user-images.githubusercontent.com/68833654/91929308-f8192800-ec92-11ea-8334-924eb6eb7a9a.png)
![Screenshot_2020-09-01-20-33-24](https://user-images.githubusercontent.com/68833654/91929328-023b2680-ec93-11ea-9cf7-776463e7d98d.png)
![Screenshot_2020-09-01-20-33-32](https://user-images.githubusercontent.com/68833654/91929334-06674400-ec93-11ea-8296-4b6126a6e31d.png)

**Comment by Benefit-Zebra** [comment]
This is purposely done to keep the emojis according to their type.
