### ISSUE TITLE
Missing emojis

### ISSUE THREAD

**Issue by YairMejiaValtierra** [efroemling/ballistica#177]
![Screenshot_2020-09-01-20-33-03](https://user-images.githubusercontent.com/68833654/91929397-2139b880-ec93-11ea-81ed-7ff1e30f6ae9.png)
![Screenshot_2020-09-01-20-33-32](https://user-images.githubusercontent.com/68833654/91929402-23037c00-ec93-11ea-8989-ca3982a4982e.png)
![Screenshot_2020-09-01-20-33-24](https://user-images.githubusercontent.com/68833654/91929403-2434a900-ec93-11ea-815e-ea228d60d4e2.png)
Idk what happened but I just found this

**Comment by Benefit-Zebra** [comment]
This is purposely done to keep the emojis separated according to their type.

**Comment by Benefit-Zebra** [comment]
This issue can be closed now.

**Comment by Dliwk** [comment]
Hmm; looks like I was too sloppy adding emojis to the built-in keyboard and there are some extra invisible symbols...

Ah, no, this is how it should be. Emojis are simply divided into categories, so that different categories do not mix, there are empty cells.
