### ISSUE TITLE
while hosting 1.5 on server having trouble can u please get me out for solution

### ISSUE THREAD

**Issue by amalthamban7** [efroemling/ballistica#182]
ubuntu@ip-172-31-38-118:~/BombSquad$ ./bombsquad_server
/usr/bin/env: invalid option -- 'S'
Try '/usr/bin/env --help' for more information.

can someone help

**Comment by JoseANG3L** [comment]
https://github.com/efroemling/ballistica/issues/121

**Comment by Dliwk** [comment]
What version of Ubuntu are you running this from? The -S argument has been [added][commit] in coreutils 21th Jun '18.
By the way, it seems like this should already work by itself in newest ballistica versions.

[commit]: https://github.com/coreutils/coreutils/commit/668306ed86c8c79b0af0db8b9c882654ebb66db2
