### ISSUE TITLE
Make a Server Searcher by Name or Version

### ISSUE THREAD

**Issue by YairMejiaValtierra** [efroemling/ballistica#183]
Concept: 
![20200910_021426](https://user-images.githubusercontent.com/68833654/92709026-6f8e2d80-f30b-11ea-8927-467d15224bd3.jpg)

**Comment by DrovGamedev** [comment]
already, but less functional: [plugin](https://github.com/DrovGamedev/BombSquad-Hardcore-Modpack/blob/master/mods/server_search.py)

**Comment by abhinaypandey02** [comment]
https://github.com/ModSquadBS/Bombsquad-Community-Mods-V2/blob/master/mods/gather_search.py

**Comment by Dliwk** [comment]
What is the use of searching by version?

Search by name is available from [1.5.27](https://github.com/efroemling/ballistica/releases/tag/v1.5.27).

**Comment by Dliwk** [comment]
Closing now; BombSquad itself displays only network-compatible servers (or what is the benefit of searching by version?).
BombSquad haven't *too* many servers now, so I think case-sensitive search will only clutter up the interface, especially on small screens.

Reopen if I'm wrong.
