### ISSUE TITLE
Tournaments are not supported 

### ISSUE THREAD

**Issue by KoLenka12** [efroemling/ballistica#185]
In BombSquad 1.5.x tournaments are not supported![Screenshot_20200919-140241.png](https://user-images.githubusercontent.com/58659520/93664590-d84a7800-fa78-11ea-81b5-96490c7b02f1.png)

**Comment by Dliwk** [comment]
Are you sure you running vanilla game (without any mods)?

**Comment by KoLenka12** [comment]
yes

**Comment by Benefit-Zebra** [comment]
Which version are you running, beta version or released veraion?
