### ISSUE TITLE
Executing a callable from in-game thread

### ISSUE THREAD

**Issue by ritiek** [efroemling/ballistica#187]
Hi. I want to keep a log of my in-game chats in a file. AFAIK there is no callback method available on the client side which would execute whenever a chat message is received. So my plan is to call `_ba.get_chat_messages()` after every few seconds and append the new chat messages to a log file. But I can't get this to work.

If I call this code from the in-game thread:
```python
import _ba
import time

while True:
    print(_ba.get_chat_messages())
    time.sleep(5)
```
This displays the chat messages every 5 secs but causes the in-game thread to completely halt (due to `time.sleep`) and this I don't want. What I want is this code should keep running in a separate background thread without bringing the in-game thread to a halt.

So, I modify it as:
```python
import _ba
import time

def print_chat_messages_loop()
    while True:
        print(_ba.get_chat_messages())
        time.sleep(5)

import threading
t = threading.Thread(target=print_chat_messages_loop)
t.start()
```

but then I end up with this `RuntimeError` on the call to `_ba.get_chat_messages`:
> RuntimeError: Precondition failed: InGameThread()

I guess for some reason it is required to run `_ba.get_chat_messages` in the in-game thread, but I can't find a way to do this in v1.5+.

I could get this to work in versions <1.5 by passing `_ba.get_chat_messages` (the method name to get the chat messages used to be different but you get the idea) in `bs.callInGameThread()` ([whose help can be found in the old docs](https://www.froemling.net/docs/bombsquad-python-api)), such that the code would look something like this:
```python
import _ba
import time

def print_chat_messages_loop():
    while True:
        bs.callInGameThread(lambda: print(_ba.get_chat_messages()))
        time.sleep(5)

import threading
t = threading.Thread(target=print_chat_messages_loop)
t.start()
```
This "trick" used to work well in <1.5 but I can't find a method similar to `bs.callInGameThread` in v1.5+, so I'm having problems saving my chat logs in v1.5+.

**Comment by DrovGamedev** [comment]
Problem solution:

from ba import Timer, TimeType
import _ba

timer = Timer(5.0, lambda: print(_ba.get_chat_messages()), timetype=TimeType.REAL, repeat=True)

But you can use some other methods for chat-writing

**Comment by ritiek** [comment]
Thank you! This works nicely.

> But you can use some other methods for chat-writing

Like how?

**Comment by DrovGamedev** [comment]
A chat-writer that stores data for a certain amount of time and later writes it to a file without reopening it (f.write(''); f.flush()). Update data in chat-writer using method filter_chat_message (ba._hooks)

**Comment by ritiek** [comment]
`filter_chat_message (ba._hooks)` seems to be only called on messages being sent from my side (if i am not the host). I also want to log chats from other people.

Anyway, I'm going to close this since the original issue has been solved!
