### ISSUE TITLE
Quesiton - How can i use old mods on latest bs ?

### ISSUE THREAD

**Issue by Teals53** [efroemling/ballistica#190]
about mrmaxmeier :(

**Comment by Benefit-Zebra** [comment]
Read Q.3 of readme **Will my existing BombSquad 1.4.x mods still work?**

**Comment by Teals53** [comment]
well i cant use installer.py ?

**Comment by Dliwk** [comment]
As already mentioned, you [can't][readme_faq] just run mods for 1.4 in 1.5 head-on.

Of course, it is possible to automate the process of translating *simple* mods to the new API, but... most of the other mods redefine the internal logic of the game, making them *very* dependent on the structure of the 1.4.

So, old mods can only be used if you rewrite them with your hands, all this terrible magic that most of mods use.

What is a simple mod? It is minigame.

[readme_faq]: https://github.com/efroemling/ballistica/blob/master/README.md#frequently-asked-questions

**Comment by Teals53** [comment]
sad noises

**Comment by Dliwk** [comment]
Don't be sad; you may run BombSquad 1.4 to use old mods. E. g. I still play BombDash ModPack, but it based on 1.4. 
Anyway, 1.4 and 1.5 are still compatible in terms of network play :smile:

**Comment by Teals53** [comment]
yeah ik xd

**Comment by Teals53** [comment]
hope new stuff can be come asap xd
