### ISSUE TITLE
Error while executing BombSquad.exe 1.5.26 build 20185

### ISSUE THREAD

**Issue by Bumwalibai** [efroemling/ballistica#191]
![image](https://user-images.githubusercontent.com/72663822/95659823-5ca48e00-0b41-11eb-8297-734881fac69d.png)

![image](https://user-images.githubusercontent.com/72663822/95659814-4c8cae80-0b41-11eb-8fa2-5eb2e949ce42.png)

**Comment by efroemling** [comment]
I believe this is fixed in newer builds. Please re-open if it does not seem to be.
