### ISSUE TITLE
Textures Names

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#196]
Can we rename texture names same as how variables are named in Python like:

achievementOnslaught.ktx changes to achievement_onslaught.ktx

I think this will make it at par with Python3 variable naming. Since we upgraded from Python2.

**Comment by DrovGamedev** [comment]
after this, you'll have some troubles with net-play like only 1.5 or 1.4 build-version-to-play servers (error message - "Failed to load achievement_onslaught.ktx")

**Comment by Benefit-Zebra** [comment]
We can use Dependency System for this.

**Comment by efroemling** [comment]
Before long assets will be switching over to the dependency system (including built-in assets) and so they will be accessed by lowercase/underscore names there. I hope to rename all the files themselves too, though I will need some sort of compatibility layer if we want to maintain the ability to connect to old 1.4.x servers which still use the old names. (so if the server says to load fooBar.ktx then the local game would look for foo_bar.ktx, etc.)

**Comment by efroemling** [comment]
(closing now; holler if you still have questions not covered by the previous explanation)
