### ISSUE TITLE
Thanks for making BombSquad.

### ISSUE THREAD

**Issue by Ir0905** [efroemling/ballistica#197]
Hi Eric, 

I have played BombSquad for several years and recommended it to my friends around me.The idea of BombSquad is great and it brings me a lot of fun. So I want to express my love for this game .However,I've always felt it's a pity that this charming game didn't  be released on steam and other platforms (xbox ,switch.etc) ,because this interesting game is worth more people to play. Until today, I saw the roadmap and learned that you have plans to ship on steam. I'm glad that more people can experience the fun of BombSquad and enjoy the joy of this game.

Thanks again for your excellent work! Looking forward to what comes next!

**Comment by chelikol** [comment]
For some time now I have been toying with the idea of switching from Windows to linux. But not without bombsquad. Therefore I tried a live-CD from Ubuntu and installed bombsquad:

sudo snap install bombsquad

By means of code I have linked my account. It works perfectly.

**Comment by astrojade** [comment]
This game is impressive but because of the lag, no one wants to carry on playing this. If you compare rocket league to this game, u will notice that even on low net it is still playable. But yea, i would like if this game becomes 0 lag free, then this game will be more entertaining for everyone to play.

**Comment by Dliwk** [comment]
Since this is old inactive issue I better close this (and make current open-issue list more.. useful?..). I guess it'd be nice to create some [discussion][1] with all thanks. :slightly_smiling_face: 

[1]: https://github.com/efroemling/ballistica/discussions
