### ISSUE TITLE
Don't starting server

### ISSUE THREAD

**Issue by KoLenka12** [efroemling/ballistica#200]
Servers were originally running on version 1.4.155 in Ubuntu 18.04. But after switching to BombSquad 1.5.26 in Ubuntu 20.01, the servers stopped starting, giving the following error:
![wng72UO40dY](https://user-images.githubusercontent.com/58659520/97496381-49d3eb00-1982-11eb-9cb0-5db070584b2c.jpg)

I tried changing the server port 43210 to 20000. All to no avail.

**Comment by DrovGamedev** [comment]
monki flip

**Comment by Dliwk** [comment]
Kolenka blin ti roflish chto li :man_facepalming:

**Comment by Dliwk** [comment]
@KoLenka12 rollback done?
