### ISSUE TITLE
Issues in bomb squad local multiplayer

### ISSUE THREAD

**Issue by AmrWassiem** [efroemling/ballistica#203]
## Proplem with multiplayer
hi Eric, I found an issues in bomb squad local lan multiplayer, When i play with my friend with local hotspot:
- if i'm the host, my friend's ping is very high
and there is a lot of lag 
- if he is the host, my ping is very high

## Description

This is more important about my(and my friend's) bomb squad:

|    | Issue description |
| ------------- | ------------- |
| OS | Android |
| Type of issue |  :bug: Bug |
| BombSquad version |  [1.5.27](https://github.com/efroemling/ballistica/releases/tag/v1.5.27) |
| Commit |  [2642488](https://github.com/efroemling/ballistica/commit/2642488a51b250752169738f5aeeccaafa2bc8de) |

## Steps to reproduce

- Launch BombSquad.
- Play localy hotspot
- you will see that the ping is very high for the non-host one 😔
- please comment, Eric

## Sorry

I 'm sorry, my English is very bad , but i'm from Egypt

## info
i know some python , i can use OOP if i will need it

**Comment by Dliwk** [comment]
Hi! Currently BombSquad net-play code is poorly optimized and consumes a lot of traffic; most likely the hotspot simply can't withstand such a load. You can visit the [Roadmap](https://github.com/efroemling/ballistica/wiki/Roadmap) to get some information. Big net-play optimization is planned in [2.0](https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-20).

**Comment by AmrWassiem** [comment]
ok ,i will see that

**Comment by AmrWassiem** [comment]
@efroemling
