### ISSUE TITLE
User Music Option

### ISSUE THREAD

**Issue by lemonyPRIDE** [efroemling/ballistica#204]
Hello Eric,

Hope you're in good health. I wanted you to bring back the **User Music** option that was available in the previous old builds of the Bombsquad. It was really good listening to my tracks and playing the game, it usually pumps up the fun for me and  most of the other players am sure. If possible do so in the next update, if it will take longer to give this update share the script instead. 

Before you do make sure this time it supports almost all types of audio extensions.

**Comment by efroemling** [comment]
Hmm this should still be available in the Mac App Store and Android versions of the app. Are you not seeing it or is it not working?

**Comment by lemonyPRIDE** [comment]
I don't see the option anywhere in the Windows version. It's the reason I was suggesting you to share the script.

**Comment by efroemling** [comment]
Oh; that explains it. I've not implemented this option for the windows version yet. The custom-soundtracks options are currently OS-specific; the Mac one talks to iTunes/Music.app and the Android one talks to the android music playback library. Under assets/src/ba_data/python check out ba/music.py, ba/macmusicapp.py, and ba/osmusic.py to see how these work. It may be possible to implement an equivalent for windows completely via python scripts (perhaps windows exposes media playback functionality at the system level?), or it may be possible to wire up something like the FFmpeg library at the c++ level...

**Comment by lemonyPRIDE** [comment]
I'll reopen this after I find any problem installing this, I wont bother you until then, and thank you for this immediate support
