### ISSUE TITLE
Jugar con amigos en modo online

### ISSUE THREAD

**Issue by Maxximio** [efroemling/ballistica#211]
## Description
Encontrar una forma de jugar bombsquad en partidas privadas con amigos en forma de servidores LAN 

## Solution
Por medio de programas aparte como Hamachi, se puede hacer servidores LAN, pero no es lo mejor ya que para dispositivos móviles no existe una forma muy viable, en algunos videojuegos se puede crear este tipo de servidores por medio de un servidor LAN al que puedes invitar a tus amigos.

## Alternatives
Posiblemente se pueda hacer un sustituto de Hamachi que funcione para bombsquad en dispositivos móviles, para evitar un cambio que puede llegar a ser peligroso.

## Additional context
Hacía ya tiempo que las partidas online ya funcionan, pero un túnel directo con un server lan, haría que el servidor vaya mucho más rápido. No soy desarrollador, solo quería dar una idea de algo que podría ser útil para los demás jugadores. :'D

**Comment by Dliwk** [comment]
Should be solved with 1.6's private parties!
