### ISSUE TITLE
HOW CAN I UNBAN MY ACCOUNT

### ISSUE THREAD

**Issue by PuneetGurjar** [efroemling/ballistica#213]
I LINKED WITH MY FRIEND TO GET TICKETS BUT I DID'T KNOW THAT HIS DEVICE WAS ROOTED AND MY ID GOT BANNED NOW I AM NOT ABLE TO PLAY TOURNAMET I HAVE OPENED ALL CHARACTER AND SOME ICONS ALSO 
plsss help!! 🥺

**Comment by PuneetGurjar** [comment]
MY ID IS PC236724 [PC280000 LINKED]

**Comment by ritiek** [comment]
Can you elaborate what do you mean by your ID got banned because of a rooted device? I have a rooted phone myself and I can always apply Magisk Hide on Bombsquad if I want to play single-player tournaments. Anyway, I've never heard of IDs getting banned just because they were used on a rooted device.

**Comment by PuneetGurjar** [comment]
AFTER LINKING WITH MY FRIEND ACCOUNT I GOT BANNED MAYBE DUE TO ROOTED DEVICE OR HE DID SOMETHING WRONG WITH MY ACCOUNT. THAT ACCOUNT WAS MY 3 YRS OF DILIGENT .
PLSS HELP

**Comment by SushrutShidhaye** [comment]
Ok so he/you use some mods to win tournament or score more than a maximum score limit with using mods/editing scripts so it got catched by eric's autoban code -_- (autoban code is too aggressive)
Request him on mail to unban ur id (account_id / pb-xyz)

**Comment by KAKASHI449** [comment]
I wanted to lose my account too, how do I do that?

**Comment by Dliwk** [comment]
Possibly another duplicate of #103..

**Comment by PuneetGurjar** [comment]
ok 👍

**Comment by safiqulsheikh019-wq** [comment]
Bgmi Support
Tuesday, September 22, 2026
02:41 PM
HOW CAN WE ASSIST YOU?
Account
Battlegrounds Mobile India Support
02:41 PM
Let's see if these articles help

Why was my account banned?

Penalties about purchase through unauthorized services

How to delete game account?
02:42 PM
Yes, they helped
Battlegrounds Mobile India Support
02:42 PM
Glad we could help you!
Tuesday, September 22, 2026
02:43 PM
HOW CAN WE ASSIST YOU?
Account
Battlegrounds Mobile India Support
02:43 PM
Let's see if these articles help

Why was my account banned?

Penalties about purchase through unauthorized services

How to delete game account?
02:43 PM
Yes, they helped
Battlegrounds Mobile India Support
02:43 PM
Glad we could help you!
Tuesday, September 22, 2026
02:43 PM
HOW CAN WE ASSIST YOU?
Account Permanent Ban
Battlegrounds Mobile India Support
02:43 PM
Let's see if these articles help

Why was my account banned?

Penalties about purchase through unauthorized services

the device ban feature.
02:45 PM
Yes, they helped
Battlegrounds Mobile India Support
02:45 PM
Glad we could help you!
Conversation ID: #12276835

Tuesday, September 22, 2026
02:45 PM
HOW CAN WE ASSIST YOU?
Account Permanent Ban
Battlegrounds Mobile India Support
02:45 PM
Let's see if these articles help

Why was my account banned?

Penalties about purchase through unauthorized services

the device ban feature.
05:03 PM
No, I need to talk to someone
Battlegrounds Mobile India Support
05:03 PM
Hello Player, 

Thank you for contacting BATTLEGROUNDS MOBILE INDIA Customer Support! 

We understand your concern regarding your account being banned.

We will once again review your account to accurately determine the cause.

Thank you for supporting BATTLEGROUNDS MOBILE INDIA! 
05:05 PM
**Subject: Request for BGMI Account Ban Review**

Hello BGMI Support Team,

My BGMI account has been banned, and I would like to request a manual review of my account.

**Character Name:** Saif—PHB
**Character ID/UID:** [55697863073
**Ban Date:** [2026.09.22
**Device:** Vivo V50e

I believe this ban may have been applied incorrectly. I request you to please review my account activity and the reason for the ban. If there is any unauthorized application, device issue, or other violation detected on my account, please provide the relevant details.

I respect BGMI's rules and would like to continue playing fairly. Please reconsider the ban and restore my account if the review confirms that the ban was issued incorrectly.

Thank you for your time and support.

**Regards,**
Saif—PHB

You can also prepare these details

* Make it shorter for in-game support
* Add your UID and ban date
*55697863073

<img width="2392" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f3c24705-ec4d-44eb-8126-79fe92f0e81e" />
