### ISSUE TITLE
Compilation from source fails with newer OpenAL versions (>=v1.20.0)

### ISSUE THREAD

**Issue by ritiek** [efroemling/ballistica#217]
## Description
Compilation from source seems to fail when using newer OpenAL versions (>=v1.20.0) due to changes in type definitions.

## Steps to reproduce
```c
$ git clone https://github.com/efroemling/ballistica
$ cd ballistica
$ python3.8 tools/pcommand install_pip_reqs
$ make cmake
...
[ 30%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/app/app_config.cc.o                                                                                                                          
[ 30%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/app/app_globals.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/app/stress_test.cc.o
[ 30%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/app/headless_app.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/app/vr_app.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/audio/al_sys.cc.o
[ 32%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/audio/audio.cc.o
[ 32%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/audio/audio_server.cc.o
[ 33%] Building CXX object CMakeFiles/ballisticacore.dir/src/ballistica/audio/audio_source.cc.o
In file included from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/audio/al_sys.h:17,
                 from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/audio/al_sys.cc:3:
/usr/include/AL/alc.h:36:16: error: using typedef-name ‘ALCcontext’ after ‘struct’
   36 | typedef struct ALCcontext ALCcontext;
      |                ^~~~~~~~~~
In file included from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/core/exception.h:10,
                 from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/ballistica.h:28,
                 from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/audio/al_sys.h:8,
                 from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/audio/al_sys.cc:3:
/home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/core/types.h:19:34: note: ‘ALCcontext’ has a previous declaration here
   19 | typedef struct ALCcontext_struct ALCcontext;
      |                                  ^~~~~~~~~~
In file included from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/audio/al_sys.h:17,
                 from /home/ritiek/Downloads/ballistica/ballisticacore-cmake/src/ballistica/audio/al_sys.cc:3:
...
```

## Workaround

I currently have [OpenAL v1.21.0](https://www.archlinux.org/packages/extra/x86_64/openal/) installed. I was able to workaround this error on my fork with this minor change 5ca859ba1732cb63e94767dc1e1959503d66a998, and then it compiled fine!

Can we somehow automatically determine that if `AL_VERSION` >= v1.20.0 then use the new type definitions in ballistica? That way, it should compile fine with newer OpenAL versions while also keeping backwards compatibility with older OpenAL versions.

Also, [OpenAL v1.20.0 was released in November last year](https://github.com/kcat/openal-soft/releases) so I'm surprised/curious to know if there are reasons why this hasn't been updated in ballistica?

## Machine
**Platform**: Manjaro Linux 20.2
**Commit**: 29eefd6 (latest commit on ballistica master from 5 days ago)

**Comment by efroemling** [comment]
Thanks for the heads-up on this. I'm currently running my linux builds on Ubuntu 20.04 LTS; I'm guessing it is still on an older OpenAL which is why I hadn't run into this.
Anyway I just pushed commit 40d025f769f469bcff6dd551e6059a96d27b73b0 which should fix this. I simply moved the ALCContext declaration into an 'Impl' class defined in audio_server.cc so that it doesn't need to be in audio_server.h at all. I had been predeclaring that type in ballistica's types.h to avoid pulling OpenAL headers into audio_server.h.
Can you confirm that this fixes the build on your end?

**Comment by ritiek** [comment]
Yes, Compiles fine for me after 40d025f. Thanks!
