### ISSUE TITLE
Change terrain color in Bombsquad 1.5*

### ISSUE THREAD

**Issue by fabiodeoliveiraesilva** [efroemling/ballistica#222]
### Description
I have a Futbol Soccer mod game running on a dedicated server currently using Bombsquad 1.4.
I am migrating to Bombsquad 1.5, and I am creating a new Futbol Soccer mod game for this version.

He has already managed to implement almost everything, except changing the color of the terrain.

### In version 1.4 I used the following code:

**try:
            bs.getActivity().getMap().node.materials = [bs.getSharedObject('footingMaterial')]
            bs.getActivity().getMap().floor.materials = [bs.getSharedObject('footingMaterial')]
        except Exception: print('Can\'t unfreeze the map')
        try: bs.getActivity().getMap().floor.color = (0.2,1,0.2)
        except Exception: print('Can\'t change the color map')**

### In version 1.5 I tried to use this code below but it didn't work

**try:
            ba.getactivity().getMap().node.materials = [ba.stdobj('footingMaterial')]
            ba.getactivity().getMap().floor.materials = [ba.stdobj('footingMaterial')]
        except Exception: print('Cant unfreeze the map')
        try: ba.getactivity().getMap().floor.color = (0.2,1,0.2)
        except Exception: print('Cant change the color map')**

**Comment by Dliwk** [comment]
Are you really using `GameActivity.getMap()` in 1.5? This method is replaced with property `GameActivity.map` field. 
It's recommended to always print base-level exceptions, for example using ba.print_exception().

I guess your code now should be like this
```python3
# ba.stdobj() is replaced with bastd.gameutils.SharedObjects in newest versions.
shared = SharedObjects.get()
try:
    ba.getactivity().map.node.materials = [shared.footing_material]
    ba.getactivity().map.floor.materials = [shared.footing_material]
except Exception:
    print('ERROR: Cant unfreeze the map')
    ba.print_exception()
try:
    ba.getactivity().map.floor.color = (0.2, 1, 0.2)
except Exception:
    print('ERROR: Cant change the color map')
    ba.print_exception()
```

**Comment by fabiodeoliveiraesilva** [comment]
Thank you
