### ISSUE TITLE
Bug: Some troubles with plugins

### ISSUE THREAD

**Issue by drov-drov** [efroemling/ballistica#224]
Description: meta-scan cann't find plugins in mods directory

Reproduce:
1) Give memory permissions to BombSquad app
2) Copy workable plugin to mods folder ('Settings > Advanced > Show Mods Folder')
3) Restart the game
4) Go to 'Settings > Advanced > Plugins' and see nothing

It works on next devices:
Android TV-Box Ugoos X3 (Android 9.0; Android-TV; Amlogic S905X3; ARM G31 MP2)
Xiaomi Redmi Note 9 Pro (Android 10.0; MIUI 11; Qualcomm SM7125 Snapdragon 720G; Adreno 618)

Tested on next package versions:
1.5.29, release from GitHub-repo
1.5.29, release from GP

**Comment by efroemling** [comment]
When you say 'It works on next devices' do you mean that plugin scanning *does* work on those devices, or do you mean you can reproduce the issue on those devices?
Disk permissions have been reworked in Android 11 so I expect scanning to not work correctly there currently, but on 10 and earlier it *should* work (but perhaps that is not the case)

**Comment by drov-drov** [comment]
I meant reproduce of the issue

**Comment by sanederchik** [comment]
> When you say 'It works on next devices' do you mean that plugin scanning _does_ work on those devices, or do you mean you can reproduce the issue on those devices?
> Disk permissions have been reworked in Android 11 so I expect scanning to not work correctly there currently, but on 10 and earlier it _should_ work (but perhaps that is not the case)

Dear Eric! I think that this problem does exits now in 1.5.29, because there are no plugins available when I put `.py` files in a `BombSquad` folder.
I described this problem in the following discussion.

https://github.com/efroemling/ballistica/discussions/247
