### ISSUE TITLE
Tournament disabled

Good day. If it can be good ... Why didn't you write anywhere, didn't warn anywhere that when I get a root, my account (keyword ACCOUNT, in which I officially bought the pro version ...) will not be suitable for tournaments ... Why!? I wouldn't get a root if I knew .... a terrier ... I can't play tournaments forever ... can you help, I'm not a hacker, im need root for termux, for programming and working with $HOME repository... why "root" pc gamers can play tournaments.... pleeeease help, i beg you....😭
Im really lost my BombSquad pro account!? Hellp, its breaked my day.... Hellpppp please i beg you...... my banned account mail is vladreh227@gmail.com... Im waiting for ansver and help...😥
Sorry for my English....

### ISSUE THREAD

**Issue by VladyslavRehan** [efroemling/ballistica#227]
We're using [GitHub Discussions](https://github.com/efroemling/ballistica/discussions)! Asking and answering questions is much more convenient there than in Issues.

**Comment by AllStarYT** [comment]
If the phone is rooted, install magisk and put bombsquad as one the apps that can't recognize the root. I don't know how to explain perfectly, search on youtube or google.

**Comment by VladyslavRehan** [comment]
> If the phone is rooted, install magisk and put bombsquad as one the apps that can't recognize the root. I don't know how to explain perfectly, search on youtube or google.

I not absolutely understood what to look for ... I on stack ower flow found that the blacklist gets not a device, its gets an all account.  This account is linked to my computer bombsquad.  I also can't take part in tournaments there ... it's probably forever ... I hided magisk as possible, and bombsquad added magisk hide to the list, dont helped....
Sorry for my English...
Please help me....

**Comment by AllStarYT** [comment]
I'm sorry, but I can't help ya
Don't know man, unlink the android account and only play on pc, really sorry for that

**Comment by VladyslavRehan** [comment]
> I'm sorry, but I can't help ya
> Don't know man, unlink the android account and only play on pc, really sorry for that

No, im just want i want erik to turn off this check on root right ....

**Comment by SushrutShidhaye** [comment]
Check my Answer in 
Issur #213

**Comment by VladyslavRehan** [comment]
Eric, help...

**Comment by SushrutShidhaye** [comment]
Did u unroot device and tried?

**Comment by VladyslavRehan** [comment]
> Did u unroot device and tried?

No, I achieved this root so hard by flashing the phone .... I'm afraid I'll catch the bootloop again... Thank you for answering....

Sorry for my English

**Comment by SushrutShidhaye** [comment]
> > Did u unroot device and tried?
> 
> No, I achieved this root so hard by flashing the phone .... I'm afraid I'll catch the bootloop again... Thank you for answering....
> 
> Sorry for my English

Use Magisk Hide to hide root access from apps search on Google and then try...

**Comment by VladyslavRehan** [comment]
- Eric... Where are you...?

**Comment by efroemling** [comment]
Hey guys; sorry but there's nothing I can do about this sort of thing for now. I had to add root detection years ago because hacking was so rampant on tournaments. I know its not a perfect solution, but I can't turn it off without making things a lot worse again. What I am working on is a future where tournaments are played on my own servers (once I finish implementing client-prediction to solve lag issues) and then it will be possible to 100% prevent hacks. For now I hope you are able to get one of the workarounds mentioned above working...

**Comment by VladyslavRehan** [comment]
> Hey guys; sorry but there's nothing I can do about this sort of thing for now. I had to add root detection years ago because hacking was so rampant on tournaments. I know its not a perfect solution, but I can't turn it off without making things a lot worse again. What I am working on is a future where tournaments are played on my own servers (once I finish implementing client-prediction to solve lag issues) and then it will be possible to 100% prevent hacks. For now I hope you are able to get one of the workarounds mentioned above working...

Thank you for reply. Finally im hid Bomb Squad from the root. It was a long way. And what I was glad that the whole account did not get to the blacklist ... But what else interests me, any mod that is specially designed for version 1.5, even the banal Colors mod changes something in the game and on the tournaments writes that i changed the game files. If you delete io, it does not disappear and you need to reinstall the game.

**Comment by efroemling** [comment]
Yes I know it is annoying that any mod in 1.5 disabled tourney play; but it is technically possible for mods to make changes that affect scores so this also was necessary for security.

My hope is to add something like a 'Disable Mods' checkbox in advanced settings that will (after restarting the game) disable any scanning or loading of mods so that tourneys can be played without manually uninstalling/reinstalling all mods.
If someone wants to try adding this feature I'd be happy to offer tips/assistance.

Though the true fix for this also will be cloud-based tourneys; at that point I can completely stop caring if the local game was modified.. I'm honestly really looking forward to getting to that point; trying to police what people do on their own devices is no fun.

**Comment by VladyslavRehan** [comment]
> Yes I know it is annoying that any mod in 1.5 disabled tourney play; but it is technically possible for mods to make changes that affect scores so this also was necessary for security.
> 
> My hope is to add something like a 'Disable Mods' checkbox in advanced settings that will (after restarting the game) disable any scanning or loading of mods so that tourneys can be played without manually uninstalling/reinstalling all mods.
> If someone wants to try adding this feature I'd be happy to offer tips/assistance.
> 
> Though the true fix for this also will be cloud-based tourneys; at that point I can completely stop caring if the local game was modified.. I'm honestly really looking forward to getting to that point; trying to police what people do on their own devices is no fun.

Thank you! It's all very nice, I look forward to it! I'm so glad that everything is still ahead! Happiness in everything! Sorry for wasting your time ...

**Comment by Dolfost** [comment]
I want to inform you that a week after that, by removing the game, sweeping the traces of the root, and installing the game and before the first run to hide the root from it, everything works. Yes, I forgot a bit what I wrote here...
