### ISSUE TITLE
Bug: Lobby Crash

### ISSUE THREAD

**Issue by drov-drov** [efroemling/ballistica#228]
Description:
After speed-profile-changing in lobby (0-50 ms, 100-700 loops), BombSquad crashes.

Reproduce:
1) Choose a game-mode and launch it
2) Use auto-clicker to repeat swipes in lobby
3) After few second, the game will crash

Solve:
Can be fixed by adding special method with 
warning like simple auto-clicker warning that already uses in game.

Machine:
Huawei Mediapad T3 8.0 LTE (Android 7.0; EMUI 5.1.3; Snapdragon 425)

Version:
1.5.29, release from github.

**Comment by Dliwk** [comment]
Is it the problem that should have been temporarily fixed in #35?

**Comment by Dliwk** [comment]
Oh; maybe game crashes because of you (host) attack yourself and protection system just can't kick you?
