### ISSUE TITLE
Docs for bastd module

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#23]
Hmm this repository contains `ba` and `bastd` modules, but we have wiki only for `ba`

**Comment by efroemling** [comment]
This is a good point. I'm hoping to be able to move my docs generation script into the public repo and hopefully we can adapt it to run for other packages like bastd and not just ba.

We could also look at using off-the-shelf Python docs generation tools, but it's also nice to have complete control over what gets generated.

**Comment by Dliwk** [comment]
Well, someone might want to take a look at [docs generation][1] and poke around there.

[1]: https://github.com/efroemling/ballistica/blob/master/tools/batools/docs.py

**Comment by efroemling** [comment]
Yes, all the docs-generation code is public now, but I haven't had time yet to try and expand it to operate on more than just the ba module. Theoretically it shouldn't be too hard to do. There's also still the question of possibly using other python docs generation libraries, though there are potential upsides to doing it all ourself.

**Comment by Dliwk** [comment]
Well I'm tinkering with this right now, so is there any strong reason of importing pydoc in many methods instead of single top-file import?

**Comment by efroemling** [comment]
> Well I'm tinkering with this right now, so is there any strong reason of importing pydoc in many methods instead of single top-file import?
> 
> 
In some cases like the pcommands scripts I like to do imports at the function level so that they don’t add overhead for short commands when they are not used, but I think in the document generation code it should be fine to move that to the module level.

**Comment by Dliwk** [comment]
![изображение](https://user-images.githubusercontent.com/47295209/153275804-eeff69b7-45e4-485d-9116-aab5a1f85e75.png)
Uhh I feel I ran into some trouble :( 
Adding type annotations like `activate_sound: ba.Sound = ba.getsound(...)` would be ridiculous, so I'll probably will try to teach this script to get variable type from function signature... Any other ideas?



> In some cases like the pcommands scripts I like to do imports at the function level so that they don’t add overhead for short commands when they are not used, but I think in the document generation code it should be fine to move that to the module level.

Okay, got it. I probably may commit this all as is and push to my fork if you want to take a look.

**Comment by efroemling** [comment]
Oh hmm.. yeah perhaps trying to teach it to pull the type from the signature would be the best option. Or maybe some fancy way to get the type from mypy or something. Though if all that winds up being very difficult, just adding explicit annotations to the source wouldn’t be the end of the world I suppose.

And yeah I’d be happy to take a look at your fork...

**Comment by Dliwk** [comment]
Ok I pushed to [docs-generation][1] branch.

[1]: https://github.com/Dliwk/ballistica/tree/docs-generation

**Comment by efroemling** [comment]
> Ok I pushed to [docs-generation](https://github.com/Dliwk/ballistica/tree/docs-generation) branch.

Looking good so far 👍

**Comment by efroemling** [comment]
> and not so good at getting function signatures from C++ layer, so now I'll try to deal with this.

Just a thought: now that pretty much everything in the C++ layer is getting added to the dummy _ba.py module, I think it might technically be possible to do docs generation without having to run the game itself.

**Comment by Dliwk** [comment]
Um, it seems I forgot about this stub file... then I can't find a reason for him not to get correct signature :thinking:

**Comment by efroemling** [comment]
Are you running the docs generation from within the game? (like how the existing generation works?). If that is the case, maybe it is seeing the *actual* C++ layer stuff as opposed to the stub versions and getting confused by that?...

To generate the _ba.py stub file with proper annotations/etc. I have to parse the 'live' c++ function/class docstrings and ensure that they contain a full valid signature as the first line. It would probably be easier for external tools to simply look at _ba.py.

**Comment by Dliwk** [comment]
Fine, this is supported since [16 Aug 2021][1], but version 6.6.0 was released earlier, so I'll probably start PR now which won't be merged until we have Python 3.10 and using the latest version of pdoc become possible.

[1]: https://github.com/mitmproxy/pdoc/pull/293

**Comment by Dliwk** [comment]
Ok, future discussions can be held there, I guess.
