### ISSUE TITLE
Server bug

### ISSUE THREAD

**Issue by AllStarYT** [efroemling/ballistica#236]
The server FFA Brazil 1 is bugged out, you can't finish the minigame. When you hold the flag for 30 seconds nothing happens, it just stay on the 0 and you can't win or lose, and if you die you can't respawn anymore. It's only happening in the FFA Brazil 1, the 2 is fine... 

You can see on the screenshots that I was playing in the server with the "Prota" name, but I can't respawn since I died on the first time. 

@efroemling 

![Screenshot_20210214-171521_BombSquad](https://user-images.githubusercontent.com/77262895/107888162-8dc70d80-6ee9-11eb-8cc2-1277ff9e4323.png)
![Screenshot_20210214-171554_BombSquad](https://user-images.githubusercontent.com/77262895/107888165-8f90d100-6ee9-11eb-8b9b-cc74844f0b8f.png)

**Comment by Dliwk** [comment]
Hmm I probably close this since it was a looong time ago and now I simply can't find this server :smile:
