### ISSUE TITLE
Bug: Keyboard cloning

### ISSUE THREAD

**Issue by KoLenka12** [efroemling/ballistica#238]
## Description
When choosing a different language and "smile" or "numbers" section there is a partial cloning of the keyboard. 

## Machine
**Platform**: Huawei MediaPad T3
**BombSquad version**: 1.5.29
## Screenshots

![Screenshot_20210217-225023](https://user-images.githubusercontent.com/58659520/108266877-0fd26300-7184-11eb-8693-704ee1ac9a5b.png)
![Screenshot_20210217-225027](https://user-images.githubusercontent.com/58659520/108266897-15c84400-7184-11eb-8f26-09dd468f816a.png)

**Comment by Dliwk** [comment]
Hmm; These "cloned" characters will be replaced with spaces in referenced commit. In principle, keyboard developers should create pages so that each page has the same number of characters as the main page, so I also added an error message if page size if incorrect.
