### ISSUE TITLE
How to remove the 8 players limit?

### ISSUE THREAD

**Issue by LingEmberMaple** [efroemling/ballistica#240]
How to remove the 8 players limit?

**Comment by JoseANG3L** [comment]
@LingEmberMaple 
In the python folder, go to _ba /_session.py_, go to code line 93, the following code will appear, just change the value of 8 for whatever you want.

```
def __init__(self,
             depsets: Sequence[ba.DependencySet],
             team_names: Sequence[str] = None,
             team_colors: Sequence[Sequence[float]] = None,
             min_players: int = 1,
             max_players: int = 8):
```

**Comment by LingEmberMaple** [comment]
> @LingEmberMaple
> In the python folder, go to **_ba_/__session.py_**, go to code line 93, the following code will appear, just change the value of 8 for whatever you want.
> 
> ```
> def __init__(self,
>              depsets: Sequence[ba.DependencySet],
>              team_names: Sequence[str] = None,
>              team_colors: Sequence[Sequence[float]] = None,
>              min_players: int = 1,
>              max_players: int = 8):
> ```

I have tried it, but it doesn't work.
My server still only allows 8 players.

**Comment by JoseANG3L** [comment]
@LingEmberMaple 
Remember to delete the **__pycache__** folder which is in the same folder where you edit the file so that the changes work.
Only delete it the first time.

**Comment by LingEmberMaple** [comment]
> @LingEmberMaple
> Remember to delete the "**pycache**" folder which is in the same folder where you edit the file so that the changes work.
> Only delete it the first time.

No, it does't work.
