### ISSUE TITLE
How does it show text messages on the screen in Bombsquad 1.5?

### ISSUE THREAD

**Issue by fabiodeoliveiraesilva** [efroemling/ballistica#242]
### I'm trying to show text messages on the screen in Bombsquad 1.5, I tried to use the code below but it didn't work:

```python
def text():
        t = _ba.newnode('text',
                attrs={ 'text':u'\ue043Message1\ue043',
                        'scale':1.2,
                        'maxwidth':0,
                        'position':(0,138),
                        'shadow':0.5,
                        'flatness':1.0,
                        'color':((0+random.random()*1.0),(0+random.random()*1.0),(0+random.random()*1.0)),
                        'h_align':'center',
                        'v_attach':'bottom'})
        ba.animate(t,'opacity',{0: 0.0,500: 1.0,6500: 1.0,7000: 0.0})
        ba.timer(7000,t.delete)
    ba.timer(3000,ba.Call(text))
    ba.timer(50000,ba.Call(text),repeat = True)
```

**Comment by Dliwk** [comment]
ba.Timer [now takes][1] its 'time' arg as seconds instead of milliseconds. To port old calls, add: timeformat='ms' to each call or convert input to seconds.

So, most likely your text just stays with zero opacity.

[1]: https://github.com/efroemling/ballistica/blob/master/CHANGELOG.md#150-20001

**Comment by fabiodeoliveiraesilva** [comment]
**It doesn't work, nothing appears**

```
def text():
        t = ba.newnode(
                'text', 
                attrs={
                    'text':u'\ue043Message1\ue043',
                    'scale':1.2,
                    'maxwidth':800,
                    'position':(0,138),
                    'shadow':0.5,
                    'flatness':1.0,
                    'color':(1,1,1),
                    'h_align':'center',
                    'v_attach': 'bottom',
                    'vr_depth': -20

                    
                })
ba.timer(3,ba.Call(text),repeat = True)
```

**Comment by JoseANG3L** [comment]
I already tried it and if it works, it is only to change the milliseconds to seconds, the format of the node is to show in the game, the ba.Call is not necessary if it is in the same line of code.

`import random
        def text():
            t = ba.newnode('text',
                           attrs={
                                'text':u'\ue043Message1\ue043',
                                'scale':1.2,
                                'maxwidth':0,
                                'position':(0,138),
                                'shadow':0.5,
                                'flatness':1.0,
                                'color':((0+random.random()*1.0),
                                         (0+random.random()*1.0),
                                         (0+random.random()*1.0)),
                                'h_align':'center',
                                'v_attach':'bottom'})
            ba.animate(t, 'opacity', {0.0: 0.0, 0.5: 1.0, 6.5: 1.0, 7.0: 0.0})
            ba.timer(7.0, t.delete)
        ba.timer(3.0, text)
        ba.timer(50, text, repeat=True)`

![message](https://user-images.githubusercontent.com/57434391/108749038-ea878100-7504-11eb-81da-46c0e2b2ae9e.png)

**Comment by JoseANG3L** [comment]
`import random
def text():
    t = ba.newnode('text',
                   attrs={
                        'text':u'\ue043Message1\ue043',
                        'scale':1.2,
                        'maxwidth':0,
                        'position':(0,138),
                        'shadow':0.5,
                        'flatness':1.0,
                        'color':((0+random.random()*1.0),
                                 (0+random.random()*1.0),
                                 (0+random.random()*1.0)),
                        'h_align':'center',
                        'v_attach':'bottom'})
    ba.animate(t, 'opacity', {0.0: 0.0, 0.5: 1.0, 6.5: 1.0, 7.0: 0.0})
    ba.timer(7.0, t.delete)
ba.timer(3.0, text)
ba.timer(50, text, repeat=True)`

**Comment by JoseANG3L** [comment]
> import random
def text():
    t = ba.newnode('text',
                   attrs={
                        'text':u'\ue043Message1\ue043',
                        'scale':1.2,
                        'maxwidth':0,
                        'position':(0,138),
                        'shadow':0.5,
                        'flatness':1.0,
                        'color':((0+random.random()*1.0),
                                 (0+random.random()*1.0),
                                 (0+random.random()*1.0)),
                        'h_align':'center',
                        'v_attach':'bottom'})
    ba.animate(t, 'opacity', {0.0: 0.0, 0.5: 1.0, 6.5: 1.0, 7.0: 0.0})
    ba.timer(7.0, t.delete)
ba.timer(3.0, text)
ba.timer(50, text, repeat=True)

**Comment by Dliwk** [comment]
It seems that everything has worked for you, so I think I'll close it; reopen if needed.
