### ISSUE TITLE
Cheaters appeared in the game :(

### ISSUE THREAD

**Issue by xapyku** [efroemling/ballistica#244]
Hello.
Can you tell me how to deal with this?
When you barely killed an opponent - he goes out and instantly comes back in, although this is not provided. because of this does not accrue a point and the game loses its meaning. Maybe someone else has run into this? Can this be somehow fixed in the new version of the game?
But the game is great)

**Comment by 3alTemp** [comment]
As of now, people who leave and rejoin a game have to wait 10 seconds as usual, so the issue has been fixed.
@efroemling do you mind closing this issue once you're free? 🤠

**Comment by xapyku** [comment]
> На данный момент людям, которые покидают игру и возвращаются в нее, приходится ждать 10 секунд, как обычно, поэтому проблема исправлена. @efroemling вы не могли бы закрыть этот выпуск, как только освободитесь? 🤠

Конечно я могу закрыть обсуждение, потому что не могу проверить, исправлена ли ошибка. Потому что давно не играю и это не встречается всегда. Просто некоторые пользователи так делали и приходилось искать другой сервер, чтобы не огорчаться )
Только вот разберусь, как тут закрывается тема :D

**Comment by xapyku** [comment]
> As of now, people who leave and rejoin a game have to wait 10 seconds as usual, so the issue has been fixed. @efroemling do you mind closing this issue once you're free? 🤠

Of course, I can close the discussion because I can't check if the bug has been fixed. Because I haven't played for a long time and it doesn't always happen. It's just that some users did this and I had to look for another server so as not to be upset)
I'll just figure out how the topic closes here :D
