### ISSUE TITLE
Disabling VerticalSync for Higher FPS

### ISSUE THREAD

**Issue by sepehrmoh81** [efroemling/ballistica#248]
Hi
I'm currently playing on Windows, Version 1.5.29. I checked the BombSquad data files related to graphics and figured out there's a VerticalSync switch for the mac version, but it's off for Windows. I changed the values and the option is now shown in Graphics Settings, but doesn't do anything. FPS is locked of 60, sometimes shows 61 and then back to 60 again.
Is there a chance I could disable VSync and get more FPS?
btw I have it disabled in the NVIDIA Control Panel

**Comment by lemonyPRIDE** [comment]
Doesn't matter, even if it shows off for windows (idk HOW you saw that), but the game is capped on 60 fps on every platform. I opened this issue a while back, but ig Eric didn't have an answer to that problem. [https://github.com/efroemling/ballistica/issues/199](url)

**Comment by sepehrmoh81** [comment]
Yeah, it's totally capped. Here's a photo of how VSync=Never in Game shows up:
![Screenshot (15)](https://user-images.githubusercontent.com/55427571/113475076-c49cb700-9488-11eb-97b2-87605024ca8e.png)

**Comment by TheMikirog** [comment]
Except some people got 120 FPS on their phones and of course there's the 90 FPS of the Oculus version. Clearly 60 FPS is not the cap everywhere.

**Comment by Dliwk** [comment]
Let's merge that with another fps limit discussion (#199)
