### ISSUE TITLE
Bug: Error: ThreadMessage list > 1000 in thread: game

### ISSUE THREAD

**Issue by YashKandalkar** [efroemling/ballistica#249]
## Description
This is how the terminal looks:
```
BombSquad 1.5.29 build 20258.
>>> Unable to bind udp port 43210; some network functionality may fail.
Error: ThreadMessage list > 1000 in thread: game
Thread message tally (1001 in list):
  #1 (1x): kRunnable: struct ballistica::Media::PreloadRunnable
  #2 (1000x): kRunnable: class ballistica::LambdaRunnable<class <lambda_254dd6393448f16cf0755f91cff85018> >
```

## Steps to reproduce
The game randomly crashes (freezes) and then I cannot close the game window to restart. When I close all windows this is what the output is on terminal:
> AL lib: (EE) alc_cleanup: 1 device not closed

## Expected behavior
Game shouldn't crash

## Machine
**Platform**: Windows 10 
**BombSquad version**: [1.5.29](https://github.com/efroemling/ballistica/releases/tag/v1.5.29)

## Screenshots
![image](https://user-images.githubusercontent.com/35102959/112036445-a4a2f480-8b66-11eb-8a62-0933ed7e1588.png)

**Comment by Dliwk** [comment]
Does this happen in the vanilla version without mods?

**Comment by SmooothSoundz** [comment]
> @Dliwk Oh I forgot it could happen because of mods too, and I did have a random mod installed that time. This error doesn't come anymore after I removed those mods. I should close this.

Which mod did you have installed?
