### ISSUE TITLE
WSL2 cant find vcredist files, again...

### ISSUE THREAD

**Issue by lemonyPRIDE** [efroemling/ballistica#257]
WSL2 can't find vcredist debug files, I know Eric you already closed a case on this as you said that you already included those files but the same problem persists again. Culprits are VCRUNTIME140D.dll & MSVCP140D.dll ..... can you update the src with these 2 updated or point me to the direction where I can install it ?

I can run it on Ubuntu Virtual Box, but not on windows terminal 

![WhatsApp Image 2021-04-04 at 11 29 39](https://user-images.githubusercontent.com/67043009/113500228-d722f900-9539-11eb-8982-5322a27fff02.jpeg)
![WhatsApp Image 2021-04-04 at 11 29 39 (1)](https://user-images.githubusercontent.com/67043009/113500229-d8542600-9539-11eb-8781-8bf6658ea760.jpeg)

**Comment by JoseANG3L** [comment]
I created a tutorial for that error, you can see it here.
[YouTube Video](https://youtu.be/-SiYmRBfQjA)

**Comment by lemonyPRIDE** [comment]
I never said Bombsquad didn't open, I mentioned WSL2 not being able to open Bombsquad debug due to these dlls missing which I tried to run through Ubuntu 20.04 LTS Terminal.

**Comment by JoseANG3L** [comment]
Try downloading those DLLs manually, then transfer them to the BombSquad folder.

**Comment by lemonyPRIDE** [comment]
I wouldn't be here if I could do that, would I ?

**Comment by TheMikirog** [comment]
For some reason it worked if the files aren't in the Linux filesystem, but on Windows instead.
Place Ballistica on your desktop or something and it should launch.

**Comment by efroemling** [comment]
I did run into some odd issues where windows Python wouldn't find all of its own files when running under the linux filesystem, but after moving it to the normal windows filesystem everything behaved itself. Perhaps this is a similar situation. Perhaps we should put a note about it in the wiki if this is a reproducible problem.

**Comment by Dliwk** [comment]
Closing this as inactive, feel free to reopen if this is still can be reproduced or anything.
