### ISSUE TITLE
Is there any way to send a server message at set intervals on the linux server build 1.6.0 ?

### ISSUE THREAD

**Issue by driftywinds** [efroemling/ballistica#258]
Just the title

**Comment by drov-drov** [comment]
Just use of ba.Timer

**Comment by driftywinds** [comment]
> Just use of ba.Timer

can you please explain further?

**Comment by drov-drov** [comment]
Simple example:
`
with ba.Context('ui'): ba.Timer(5.0, lambda: _ba.chatmessage('test'), repeat=True, timetype=ba.TimeType.REAL)
`

**Comment by drov-drov** [comment]
You can also use ba.timer instead of ba.Timer, but ba.timer always bases on game time

**Comment by driftywinds** [comment]
> Simple example:
> `with ba.Context('ui'): ba.Timer(5.0, lambda: _ba.chatmessage('test'), repeat=True, timetype=ba.TimeType.REAL)`

where exactly do i use this code, as in in which file

**Comment by drov-drov** [comment]
ba._session

**Comment by Dliwk** [comment]
Everything seems to be working for you, so I gonna close it. Reopen it if something went wrong after all.
