### ISSUE TITLE
Ping from master server appearing in game roster

### ISSUE THREAD

**Issue by imayushsaini** [efroemling/ballistica#268]
## Description
A periodic server check ping from master server ( IP 185.98.87.xxx :47658 ) {"n":"ServerChecker","a":"Local","sn":""}  appearing in game roster . 
-Taking space of a player - In my server with only 4 players limit , most of the time 4th player is master server.
-Join/left party message in private server.

## Screenshots
![image](https://user-images.githubusercontent.com/36878972/117179893-3e5df280-adf1-11eb-8b36-d2eeb4efcccb.png)

![ScreenShot_20210505001402](https://user-images.githubusercontent.com/36878972/117055939-5f630c80-ad39-11eb-89ea-edf35f47212b.png)

**Comment by Dliwk** [comment]
Funny; it's probably my old bot, which I made to get the server that some player is currently playing on, but it should immediate leave after check and I didn't have this join/leave messages at the time I develop it.

**Comment by imayushsaini** [comment]
Lmao... **Mr.Spy**  ... I though its master server checking availability of the server(yes that was strange its coming from russia) , thats why I not blocked this IP , to keep the communication.
Your bot activity was invisible for 1.4 build , but now its not some dumb players even start chatting with this INVISIBLE_MAN . 

If its an old bot , and now not in use can you stop it ?  others may think of it a glitch or hack .
Thanks

**Comment by efroemling** [comment]
Heh yeah that's definitely not communication from the master-server. The master server communicates with games a bit to get their current names and number of players and whatnot but none of that involves 'joining' the game or adding players like that.
