### ISSUE TITLE
Client movement in network play

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#27]
When I play from 1.5 client on any server (1.4.150 or 1.5), any client movement lasts minimum for a second (i.e I cant just turn myself). No reaction to very short movements at all.

e.g. I standing here
![изображение](https://user-images.githubusercontent.com/47295209/80076346-be9e1680-8554-11ea-9261-f3978b23ac1b.png)

After just a click on "A" button.
![изображение](https://user-images.githubusercontent.com/47295209/80076351-c1990700-8554-11ea-90dd-42e4430afc00.png)

This did not happen in 1.4 (I checked it now, from 1.4.150)

**Comment by efroemling** [comment]
Ok this is fixed in commit 5a77f0bc524919fcb83b1f0f94ae378a87b4422d
Thanks for the heads-up!
