### ISSUE TITLE
I don't know how to install mods on bombsquad

### ISSUE THREAD

**Issue by ERWANDAWA** [efroemling/ballistica#277]
Can someone tell me how to install mods on bombsquad plz

**Comment by ERWANDAWA** [comment]
Im on version 1.6.3

**Comment by Dliwk** [comment]
In game, go to Settings -> Advanced -> Show Mods Folder. This will open the mods folder in some platforms, or just print its location. So, just put your mods in this folder and restart the game.

### Screenshots for PC
![изображение](https://user-images.githubusercontent.com/47295209/119270181-26b1a700-bc04-11eb-9030-3901dbc50291.png)
![изображение](https://user-images.githubusercontent.com/47295209/119270188-2dd8b500-bc04-11eb-9608-d8ccb9d7ff3f.png)

Note that old 1.4 mods won't work in newer versions.
