### ISSUE TITLE
Nothing to be done with 'assets-win-Win32'

### ISSUE THREAD

**Issue by Drie-Ice** [efroemling/ballistica#280]
## Description
I ran an instance of BombSquad once before by following the steps in the wiki and it was successful.
However I reset my laptop a few days ago and repeated the process, but this time wsl enters the directory and then leaves it and a window error pops up saying that the application(BombSquad.exe) was unable to start correctly. I'm unsure if I'm missing a driver or if the master code was changed.

**1. Enter bombsquad directory and  make prefab-debug.
2. make[1]: Entering directory '/mnt/c/Users/MyName/Documents/GitHub/ballistica-master'
make[2]: Entering directory '/mnt/c/Users/MyName/Documents/GitHub/ballistica-master/assets'
make[3]: Entering directory '/mnt/c/Users/MyName/Documents/GitHub/ballistica-master/assets'
make[3]: Nothing to be done for 'assets-win-Win32'.
make[3]: Leaving directory '/mnt/c/Users/MyName/Documents/GitHub/ballistica-master/assets'
make[2]: Leaving directory '/mnt/c/Users/MyNAme/Documents/GitHub/ballistica-master/assets'
make[1]: Leaving directory '/mnt/c/Users/MyName/Documents/GitHub/ballistica-master'
cd build/prefab/full/windows_x86/debug && ./BallisticaCore.exe
make: *** [Makefile:129: prefab-debug] Error 123
##** 

## Machine
**Platform**: Windows 10 / Ubuntu 20.04 LTS / AOSP 8.1 / etc.
**BombSquad version**: [1.5.27](https://github.com/efroemling/ballistica/releases/tag/v1.5.27)
**Commit**: [2642488](https://github.com/efroemling/ballistica/commit/2642488a51b250752169738f5aeeccaafa2bc8de)
Select what do you want to use: release version or commit. Please use a hyperlink.

## Extra
_I have installed all necessary dependencies that I am aware of, I've tried running wsl as admin. It seemed to work smoothly a month ago - making me think something has changed with the master._

**Comment by Dliwk** [comment]
`make[N]: Nothing to be done with 'xxx'` message just tells you that all prerequisites of target 'xxx' are done, including their prerequisites, etc. In your case, it means that all Win32 assets have already been built. 

Well, I guess if you run `make prefab-release`, anything will work, so maybe something is wrong again with debug-version of Windows libraries (like #140)?

**Comment by Drie-Ice** [comment]
Thanks for the advice 👍. I'll do some more tinkering. Do you think it's to do with wsl or Eric making an error?

**Comment by Dliwk** [comment]
So, are you running 32 or 64 bit Windows?

**Comment by efroemling** [comment]
Hmm; the prefab builds should currently be pulling down the 32 bit binary (as evidenced by the asset build saying make[3]: Nothing to be done for 'assets-win-Win32'.)

A few questions/ideas for debugging:
- Is make prefab-release broken for you too? Or just prefab-debug?
- Are you seeing anything more specific about what is missing on launch? (cannot find XXX dll, etc?)
- If you copy the build directory from the WSL partition to your windows drive and try to launch it directly from there (perhaps via the standard windows gui) does it work? Launching windows .exe programs from within WSL seems to be a bit flaky sometimes.

**Comment by Dliwk** [comment]
Yeah, it's pulling 32 bit game binary, but it's also pulling 64 bit debug redistributables, isn't it?..

**Comment by efroemling** [comment]
It should be pulling the 32 bit redistributables if its pulling the 32 bit binary. If its not, then I need to fix it. Originally the prefab builds pulled the 64 bit binary but I switched it to 32 when I heard from some folks who still are limited to 32 bit. Perhaps I accidentally left the 64 bit redistributables in there?..

**Comment by Dliwk** [comment]
I ran 'prefab-windows-debug-build', it built Win32 assets and there was 64 bit redistributables, so I guess you need to fix it.

**Comment by efroemling** [comment]
Are you sure you are seeing 64 bit redistributables? Or were they from a previous build? I just did a fresh git clone of ballistica and built `prefab-windows-debug-build` and I'm seeing win32 redistributables (the files in the build dir are identical to ones in assets/build/windows/Win32). The x64 ones would have the same names but also include a 'vcruntime140_1d.dll' in addition to the ones included in both sets (msvcp140d.dll, ucrtbased.dll, and vcruntime140d.dll)

**Comment by Dliwk** [comment]
Arghm; Okay, almost all of redistributables are built for i386, except for `ucrtbased.dll` (and assets/build/windows/Win32/ucrtbased.dll), which is build for x86-64.

```
$ file *d.dll 
msvcp140d.dll:     PE32 executable (DLL) (console) Intel 80386, for MS Windows
python38_d.dll:    PE32 executable (DLL) (GUI) Intel 80386, for MS Windows
ucrtbased.dll:     PE32+ executable (DLL) (console) x86-64, for MS Windows
vcruntime140d.dll: PE32 executable (DLL) (console) Intel 80386, for MS Windows
```

**Comment by Dliwk** [comment]
So, could you check this file in your fresh git clone? It seems like it's the problem.

**Comment by efroemling** [comment]
Ok, it appears that somehow I had stuck the 32 bit ucrtbased.dll into the x64 folder and vice-versa. I swapped them for commit 5ece5db0169219940885a3d779b52a08a7365424, so the prefab version should now correctly be 32 bit. Can you try this and see if it fixes the issue?

**Comment by Dliwk** [comment]
Yeah, now I can launch it via wine; we need to ask @Drie-Ice if it works for he (maybe that wasn't the only problem), but perhaps it can be closed, so, @Drie-Ice, reopen this if you still can't launch `prefab-debug`.
