### ISSUE TITLE
How to fight with non-existent accounts?

### ISSUE THREAD

**Issue by drov-drov** [efroemling/ballistica#282]
Some times ago I began to notice strange accounts that have "null" identificator (see image).
What can be done about it?
![image](https://user-images.githubusercontent.com/51883290/120317968-ec24ca00-c2e7-11eb-809d-e15f6b45b5a3.png)

**Comment by ritiek** [comment]
I think this happens when a player enters the same game server from multiple instances of the game or with linked accounts.

**Comment by drov-drov** [comment]
That's it
