### ISSUE TITLE
zlib error on transactions running

### ISSUE THREAD

**Issue by drov-drov** [efroemling/ballistica#285]
A few hours ago, the server had disappeared from list
![Screenshot_20210607-142507_ConnectBot](https://user-images.githubusercontent.com/51883290/121009314-b034ad80-c79c-11eb-955d-ed69acd0c6ec.png)
`zlib.error: Error -3 while decompressing data: incorrect header check`

**Comment by drov-drov** [comment]
HOW

**Comment by drov-drov** [comment]
![image](https://user-images.githubusercontent.com/51883290/121373159-85d32380-c947-11eb-9286-0030bfdf503b.png)

**Comment by drov-drov** [comment]
@efroemling are you working on game transactions?

**Comment by efroemling** [comment]
> @efroemling are you working on game transactions?

No, but I was seeing some server errors related to invalid transactions coming in for an account a few minutes ago. Were you by chance experimenting with them?

**Comment by drov-drov** [comment]
Maybe
