### ISSUE TITLE
How do you make a mod for bomb squad 1.6.3

### ISSUE THREAD

**Issue by DNdiamon** [efroemling/ballistica#288]
i know how to make a mod for <1.4 but i dont know the new syntax in bomb squad 1.6

**Comment by Al-Clouds** [comment]
You have all documentation on the wiki page

**Comment by bomdsquder** [comment]
Как сделать мод пак бомбсквад

**Comment by DNdiamon** [comment]
> You have all documentation on the wiki page

Thx

**Comment by Dliwk** [comment]
I'll probably close it now that you've figured it out.
