### ISSUE TITLE
Can we use assetMannager actually

### ISSUE THREAD

**Issue by Al-Clouds** [efroemling/ballistica#289]
I try to use dependency system but it seem not work so can we begin use it before 1.7 or it doesn't work and it useless to do this now?

**Comment by efroemling** [comment]
Unfortunately it's useless right now. A lot of it is implemented but there are enough missing pieces still to prevent it from being useable. I'm working on 1.7 now though so hopefully you won't have to wait *too* much longer.

**Comment by Al-Clouds** [comment]
Ok thanks for the fast response
