### ISSUE TITLE
mgr.chatmessage() to specific player

### ISSUE THREAD

**Issue by FAL-Guys** [efroemling/ballistica#294]
### Chatmessage to specific player
chatmessages to a specific player, returns error in 1.6.0 and it doesnt work in 1.6.3 with no errors

![image](https://user-images.githubusercontent.com/85888040/121909982-b0f0b500-cd43-11eb-8d72-27ec62efe820.png)

**Comment by drov-drov** [comment]
1) Set '`transient`' to True
2) Try to clean ba_root folder (dist/ba_root)
3) eror: ? What?

**Comment by FAL-Guys** [comment]
> 1. Set '`transient`' to True
> 2. Try to clean ba_root folder (dist/ba_root)
> 3. eror: ? What?

1- "_ba.chatmessage" has no argument called "transient"
"transient" is an argument for "screenmessage"

2- the ba_root folder has nothing to do with "chatmessage".
but I try that and nothing happend

I also checked the new version of bombsquad (v1.6.4) and it still has this problem

**Comment by drov-drov** [comment]
My bad, I don't know any more ways to solve the problem
