### ISSUE TITLE
How to get Server Statistics

### ISSUE THREAD

**Issue by bhavey21** [efroemling/ballistica#295]
Hello, Can anyone guide me to how to get Player score Statistic file. I know how to host it, but i m unable to generate the data.
I am hosting my server on Linux.
Thanks

**Comment by Dliwk** [comment]
Do I understand correctly that you want to get statistics like 'total number of kills, deaths, score pts, etc.'?

**Comment by bhavey21** [comment]
> Do I understand correctly that you want to get statistics like 'total number of kills, deaths, score pts, etc.'?

Yes bro.. I want Player name/account id and his Total number of kills, deaths etc... So i can further display it on my website.

I have searched google / youtube etc, but found solutions only of version 1.4.x..... I want to do it on version 1.6.x

**Comment by Dliwk** [comment]
Eww; about a year ago I did a server [modification](https://github.com/BombDash/BombDash-server) for 1.5, but it seems there are no statistics there.

So, if you have examples/guides for 1.4, it's impossible to ~port to 1.6~ write again relying on the 1.4-version? As mentioned I haven't completed/tested example and my recommendations like 'redefine `GameActivity.handlemessage()` and increase `playerstats[killer_id].kills`' should be shown in 1.4 examples that you have. But if needed, I can show some basic steps like I would do.

**Comment by bhavey21** [comment]
> Eww; about a year ago I did a server [modification](https://github.com/BombDash/BombDash-server) for 1.5, but it seems there are no statistics there.
> 
> So, if you have examples/guides for 1.4, it's impossible to ~port to 1.6~ write again relying on the 1.4-version? As mentioned I haven't completed/tested example and my recommendations like 'redefine `GameActivity.handlemessage()` and increase `playerstats[killer_id].kills`' should be shown in 1.4 examples that you have. But if needed, I can show some basic steps like I would do.

I am not that good Programmer, so i m not able to understand what u said xD.

Therefore, I started to learn Python by looking at Wiki so i could design my Stat Page Soonler or Later. I desgined a plugin to keep Spamming Screenmessage after 5 minutes. But it is throwing error, can you point me in right direction
![Screenshot from 2021-06-23 18-24-19](https://user-images.githubusercontent.com/82398707/123100367-affd0900-d450-11eb-86ec-173728e41a28.png)

**Comment by Dliwk** [comment]
Your error is easy to fix: replace `ba.screenmessage` with the following:
```python
ba.pushcall(ba.screenmessage('hello world'), from_other_thread=True)
```

This error is trying to tell you that `ba.screenmessage` can be called only in GameThread (which is main python thread in game), but you tried to call it from another thread (back_thread).

**Comment by bhavey21** [comment]
> Your error is easy to fix: replace `ba.screenmessage` with the following:
> 
> ```python
> ba.pushcall(ba.Call(ba.screenmessage, 'hello world'), from_other_thread=True)
> ```
> 
> This error is trying to tell you that `ba.screenmessage` can be called only in GameThread (which is main python thread in game), but you tried to call it from another thread (back_thread).

It compiled with no-errors and even BackThread is running fine. But i m not getting ingame screenmessage
![Screenshot from 2021-06-23 21-48-48](https://user-images.githubusercontent.com/82398707/123133212-23ad0f00-d46d-11eb-95fa-deea217e8e31.png)

**Comment by bhavey21** [comment]
> Your error is easy to fix: replace `ba.screenmessage` with the following:
> 
> ```python
> ba.pushcall(ba.Call(ba.screenmessage, 'hello world'), from_other_thread=True)
> ```
> 
> This error is trying to tell you that `ba.screenmessage` can be called only in GameThread (which is main python thread in game), but you tried to call it from another thread (back_thread).

It compiled with no-errors and even BackThread is running fine. But i m not getting ingame screenmessage.
![Screenshot from 2021-06-23 21-48-48](https://user-images.githubusercontent.com/82398707/123134009-f7de5900-d46d-11eb-87f7-39374ae36f8c.png)
