### ISSUE TITLE
Unexpected interpreter exception: No module named 'apt_pkg'

### ISSUE THREAD

**Issue by Awesome-Logic** [efroemling/ballistica#31]
Everytime I misspell something, the interpreter gives this exception and stops the server.
![image](https://user-images.githubusercontent.com/36323763/80959480-82a46480-8e24-11ea-81e0-84cf52e6a5e1.png)

**Comment by efroemling** [comment]
This seems to be a common problem when installing Python 3.7 on a system that already had 3.6 or things like that. I ran into it myself but I don't remember exactly how I fixed it.

Here is a discussion:
https://askubuntu.com/questions/480908/problem-with-update-manager-no-module-named-apt-pkg-in-ubuntu-13-10-having-i

One simple solution mentioned is: sudo apt-get install --reinstall python3-apt

Can you try that and see if it helps? There are other solutions too but they involve creating symlinks and other more hacky sounding things...

**Comment by efroemling** [comment]
Also, just so I know, what is the OS here? Ubuntu 18.04 with Python 3.7 added via apt?

**Comment by efroemling** [comment]
Ok, I was able to reproduce this and look into it. I updated the [wiki getting started page](https://github.com/efroemling/ballistica/wiki/Getting-Started) with a workaround that worked for me. Can you give that a look and let me know if it works for you?

At some point in the near-ish future I'll be updating things to use Ubuntu 20.04 and Python 3.8 which comes with it, so this should no longer be an issue at that point.

**Comment by efroemling** [comment]
Actually, in commit c038b13fde98fa83bb2f0005244403aedfd22037 I just added a notice about this which should get printed in your situation. Can you give that a try before you attempt the fix and let me know if you see it?

**Comment by Awesome-Logic** [comment]
I attempted that fix and it's working perfectly now.
Thanks :)
