### ISSUE TITLE
{Error 32] Broken pipe

### ISSUE THREAD

**Issue by 1357koushik** [efroemling/ballistica#313]
## Description
[
![IMG_20210828_143505](https://user-images.githubusercontent.com/69414779/131212716-0b23a240-05a0-4e26-aad4-539894d147ef.jpg)
](url)

I'am using python 3.9.1

## Steps to reproduce
1. Launch bombsquad_server
2. Bug!

## Expected behavior
Your server joinable form internet

**Comment by Dliwk** [comment]
Em; I guess you are trying to launch bombsquad 1.4 server, which is no longer supported (and depends on python 2 which is no longer supported too). Download fresh 1.6 builds from [here](https://files.ballistica.net/bombsquad/builds).

**Comment by 1357koushik** [comment]
> Em; I guess you are trying to launch bombsquad 1.4 server, which is no longer supported (and depends on python 2 which is no longer supported too). Download fresh 1.6 builds from [here](https://files.ballistica.net/bombsquad/builds).

but 1.4.155 is easy to edit scripts

**Comment by Mikahael** [comment]
Did you try install py 2.7 libraries?

**Comment by 1357koushik** [comment]
> Did you try install py 2.7 libraries?

doesn't that inbuilt

**Comment by Mikahael** [comment]
No, you have to install the 2.7 libraries for server. type sudo apt-get install python2.7 libsdl2-2.0 in terminal of server.

**Comment by DeathGOD7** [comment]
Same gives error in bombsquad latest version (using pterodactyl and has system terminal access) :
``` 
BombSquad server manager 1.3 starting up (debug mode)...
Interactive mode enabled; use the 'mgr' object to interact with the server.
Type 'help(mgr)' for more information.Valid server config file loaded.

Launching server subprocess...
-cfgdir: 1: home/container/dist/bombsquad_headless: not found
>>> Error running server subprocess: [Errno 32] Broken pipe
Stopping subprocess...
Subprocess stopped.
```

**Comment by Mikahael** [comment]
Are you using falixnodes or website based server?

**Comment by DeathGOD7** [comment]
> Are you using falixnodes or website based server?
Well, not FalixNodes but like it as I use my own pterodactyl game manager.

**Comment by Mikahael** [comment]
try delete server then create new one.

**Comment by DeathGOD7** [comment]
> try delete server then create new one.

Well I did that multiple times. It just says cfgdir cannont find bombsquad_headless in "..........." location. Broken Pipe.
