### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by DarkestStream69** [efroemling/ballistica#316]
There was a problem while trying to create a server. You cannot connect to the server from the server list. When I try to connect, it says "The room is full", and an endless wait. When you try to connect manually, everything works fine. My server is running Ubuntu 20.04 LTS. I already seem to have opened the ports, but this is not certain. With the VPN, I was able to connect, but most players cannot. (This text has been translated using google translate sorry for translation errors)

**Comment by Mikahael** [comment]
Same problem happens to me. Try joining server using 1.4 bs

**Comment by efroemling** [comment]
If you have a server that is behaving this way, can you leave it running and post its name here? I will try to connect and diagnose what is happening..

**Comment by Dliwk** [comment]
There is no progress for long time, so I'll close this (If someone will remember this, feel free to reopen).

**Comment by DarkestStream69** [comment]
After a long time, I tried again to fix this problem, and I managed to do it!!  The problem turned out to be in the IPV6 address, I found it out by setting the value BA_ACCESS_CHECK_VERBOSE=1.  I just disabled the IPV6 address and everything started working correctly.
