### ISSUE TITLE
Discussion : [Server] How to embed playlist data instead of using codes ?

### ISSUE THREAD

**Issue by QosborMaanous** [efroemling/ballistica#320]
Hi.

Im trying to host a modded server, and i need to load a soccer playlist, but i saw this in the config.yaml file : 
"Alternately, you can embed playlist data here instead of using codes."

So please, where could i find my playlist data that im supposed to embed ? 

Thanks

**Comment by QosborMaanous** [comment]
Update : Please i still need help lmao

**Comment by QosborMaanous** [comment]
Plus I even can't change my server's name :(

When i save my edited config.yaml file with my new server name, it doesnt change it in-game... :(

**Comment by Dliwk** [comment]
> Plus I even can't change my server's name lol
> 
> When i save my edited config.yaml file with my new server name, it doesnt change it in-game... :(

Strange, wrapper script should restart server after you changed the config, unless you launched it with '--no-config-auto-restart' argument.

**Comment by QosborMaanous** [comment]
> > Plus I even can't change my server's name lol
> > When i save my edited config.yaml file with my new server name, it doesnt change it in-game... :(
> 
> Strange, wrapper script should restart server after you changed the config, unless you launched it with '--no-config-auto-restart' argument.

yes ofc it restarts the server and i see the console detecting that the file got changed, but after being restarted it doesnt apply in the servers list in-game, its still named FFA...

**Comment by QosborMaanous** [comment]
I tried what you said @Dliwk , so i entered this in the config.yaml file :

![image](https://user-images.githubusercontent.com/90868480/134229897-1d4efe3a-c5e8-4a06-b36f-cfb96c16d7d7.png)


And for the server name it still dont work :( 

![image](https://user-images.githubusercontent.com/90868480/134230388-020ac655-b1bd-429d-995b-960bac5cf9e9.png)


![image](https://user-images.githubusercontent.com/90868480/134230309-2a0c2b4c-4d78-4f6d-add0-9f4c65f9c796.png)

**Comment by Dliwk** [comment]
Are you sure that FFA is really your server?..

**Comment by QosborMaanous** [comment]
> Haha, you should uncomment your field: remove # symbol before `party_name:`, `playlist_inline:` and others.

oh okk, so is it better like this ? 

![image](https://user-images.githubusercontent.com/90868480/134244980-7b53ddac-f0de-4937-85d2-4462ec14c061.png)
![image](https://user-images.githubusercontent.com/90868480/134244898-47eaf379-c455-4f9e-9447-fc101d1a1305.png)

**Comment by QosborMaanous** [comment]
Now when i run the server script in my console i got this :(

![image](https://user-images.githubusercontent.com/90868480/134245355-8e09f28f-0803-41a2-968f-312f74812fd9.png)

**Comment by Dliwk** [comment]
Not team: teams

**Comment by QosborMaanous** [comment]
> Are you sure that FFA is really your server?..

Sure, i can send chat messages with the console command on my server chat in-game with mgr.chatmessage()

**Comment by Dliwk** [comment]
So, do your server work?

**Comment by QosborMaanous** [comment]
> So, do your server work?

i guess yes, but could you test it with me to be sure ? 

The name is `not ffa`

**Comment by Dliwk** [comment]
Well I gotta close this since it works.
