### ISSUE TITLE
Want to know a way to track player's entry acceptance by server side

### ISSUE THREAD

**Issue by LIRIK-SPENCER** [efroemling/ballistica#322]
Like we know when a player gets kicked he/she cannot join server for some period. Here is the thing i wanted to know that. What is the name of method name or how should i able to do it like rejecting a player on before entering server rather than after entered into server !

I hope i will get to know this soon !

**Comment by FAL-Guys** [comment]
same question
Im using on_player_request for now until I find a way to access player when a player connects to a server not joins the game

**Comment by LIRIK-SPENCER** [comment]
Yeaa thats the only thing remains to be usable for this kind of thing !

**Comment by Dliwk** [comment]
> Like we know when a player gets kicked he/she cannot join server for some period. Here is the thing i wanted to know that. What is the name of method name or how should i able to do it like rejecting a player on before entering server rather than after entered into server !
> 
> I hope i will get to know this soon !

Oh that implemented in internal C++ layer :) And I guess in closed-source part.

P.S. All stuff like this is already requested in #41, suggest your other ideas about this there.
