### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by 1357koushik** [efroemling/ballistica#323]
## Description
![IMG_20210930_110747](https://user-images.githubusercontent.com/69414779/135393572-f6f21e5f-b777-4125-b80f-e7e064d07b66.jpg)
i got files from https://files.ballistica.net/bombsquad/builds/BombSquad_Server_Linux_1.6.4.tar.gz
using curl

## Steps to reproduce
1. Launch BombSquad
4. Bug!

**Comment by Dliwk** [comment]
On which platform is this happening?

**Comment by 1357koushik** [comment]
> On which platform is this happening?

it is on linux from the databrick cluster 
and its coming same on pydroid3 in rooted and non rooted both

**Comment by Dliwk** [comment]
Not sure with databrick, but pydroid3/termux/etc will fail because of their ARM architecture while your build made for x86_64

**Comment by 1357koushik** [comment]
> Not sure with databrick, but pydroid3/termux/etc will fail because of their ARM architecture while your build made for x86_64

ooh hey do you know host to host bs in android ?

**Comment by Dliwk** [comment]
> > Not sure with databrick, but pydroid3/termux/etc will fail because of their ARM architecture while your build made for x86_64
> 
> ooh hey do you know host to host bs in android ?

nope :moyai: 

Stuff like this was discussed in #56, maybe it's time to do that.
