### ISSUE TITLE
1.7 development discussion

### ISSUE THREAD

**Issue by YSPQR** [efroemling/ballistica#324]
I just wanted to check in on how BombSquad development is going, I was gone for months to Europe and I wasn't checking BombSquad updates so I wonder what's going on today.

**Comment by schooluser123uheuf** [comment]
yeah man I was wondering too

**Comment by rahulraman0108** [comment]
With each day it looks there are much more to BombSquad and more in the works. I am already very eager to try out all new features when they roll out, and especially the 'workspaces' sound very interesting feature.

**Comment by Dliwk** [comment]
> > > Also, I would like to suggest a feature with the v2 accounts: to have a public method to get the device type ie. Something like: account...get_device_type() which would return device type with which the account was created like 'pc'/'android'/'iircade'/'ios'
> > 
> > 
> > And `creation_date` field instead of query to bombsquadgame.com I guess
> 
> For v2 accounts I will try to expose them to the scripting layer as objects so if it has to talk to the master-server at least it can be something like account.get_creation_date() instead of you having to wrangle a http request. But it may make sense to have some data always available locally too.

Hmm, I just thought it would make sense to get some 'static' account data along with generic account data after logging in (if they aren't too heavy).

**Comment by efroemling** [comment]
> > > > Also, I would like to suggest a feature with the v2 accounts: to have a public method to get the device type ie. Something like: account...get_device_type() which would return device type with which the account was created like 'pc'/'android'/'iircade'/'ios'
> > > 
> > > 
> > > And `creation_date` field instead of query to bombsquadgame.com I guess
> > 
> > 
> > For v2 accounts I will try to expose them to the scripting layer as objects so if it has to talk to the master-server at least it can be something like account.get_creation_date() instead of you having to wrangle a http request. But it may make sense to have some data always available locally too.
> 
> Hmm, I just thought it would make sense to get some 'static' account data along with generic account data after logging in (if they aren't too heavy).

Yes this could make sense at least for the local account. But I would also hope to expose some sort of account object for all players in the game (as opposed to just the string ids that you get now), and it might not make sense to keep significant data locally for each of them, so at least in some cases that sort of query function might be useful.

**Comment by rahulraman0108** [comment]
> 
> Sounds good. Though I think we would want it to return the type of device they are playing on currently and not the type of device the account was created on, since a single account can be used across lots of device types.

Yeah that would be better.

**Comment by rahulraman0108** [comment]
And, what do you think of this suggestion I made [in this comment](https://github.com/efroemling/ballistica/issues/41#issuecomment-933674693) before I knew about v2 accounts?
