### ISSUE TITLE
no players score list seen after game ends.

### ISSUE THREAD

**Issue by akshaymane920** [efroemling/ballistica#33]
After the game ends scores are not being displayed. They are blank.
Screenshot
[https://drive.google.com/open?id=142xS_1Xnj4xl1CSXOCzBPrCSfCrdNfkw]

**Comment by efroemling** [comment]
Thanks for the report. I'm hoping to have this fixed within the next day or so.

**Comment by akshaymane920** [comment]
This happens only in Teams game. FFA works fine. Seams you have intentionally not created an instance of dual teams in multiteamscore.py or may if its a different issue... not sure. but thanks for picking up :)

**Comment by efroemling** [comment]
Ok this should be fixed in commit b69657a08e75dc514a5fee88398ebf0060a96f46

Thanks again for the heads-up!
