### ISSUE TITLE
Replay section : how to separate moments we dont expected to see from those that we wanted to record ?

### ISSUE THREAD

**Issue by QosborMaanous** [efroemling/ballistica#333]
## POTENTIAL IDEA OF UPDATE, REALLY NEEDED AS SOON AS POSSIBLE
@efroemling Listen, i got something interesting to share with you, see just below.

## GAME REPLAYS ENHANCEMENT : TIMELINE 
I saw a lot of people talking about this problem before me recently.
For exemple, at the end of a 'the last stand' session, i may have like 30 matches in a row recorded. But they are **attached**, then i cant catch the moment i wanted to record on the replay, especially if the replay in question is 2 hours long obviously.

And this is the reason why we NEED what im saying below : a TIMELINE 

## Alternatives
WE NEED A TIMELINE IN THE REPLAY SECTION, for selecting every moment we want to go through, in a recording context.

**Comment by TheMikirog** [comment]
> Any other thoughts on things that would be nice to see in replays?
Some ideas I have is camera panning, zooming similar to the F7 menu, but more polished and accessible. Also I can throw in "frame by frame" movement for playback controls and a way to add in slow-mo or fast forward into the replays itself for highlights.

**Comment by Dliwk** [comment]
Moved to #132
