### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by sahil0098** [efroemling/ballistica#336]
hey eric pls check my gmail i really need your help pls check the issue #103 and i need your reply at gmail i am sending you again pls help me my gmail is :- r7835885767@gmail.com

**Comment by sahil0098** [comment]
pls reply?

**Comment by sahil0098** [comment]
hello eric reply me pls it's been 4days

**Comment by Dliwk** [comment]
Consider continuing this discussion in #103, I'd better close this.

**Comment by sahil0098** [comment]
why did you closed it i am waiting for his reply from long ago

**Comment by Dliwk** [comment]
Sorry for this, but there already are similar issue where discussed some reasons of that, and I suppose this kind of questions is better to discuss in some private channels like email. But I can do nothing in case your emails get ignored.

**Comment by sahil0098** [comment]
nope i am creating another issue i hope he noticed me this time and give some proper answer for should i wait or not...
