### ISSUE TITLE
A position error

### ISSUE THREAD

**Issue by Mikahael** [efroemling/ballistica#339]
Hello Eric sir, I have been trying to add a bomb-related powerup, but it keeps giving me an error and I can't seem to get past it. It gives me a position error in the terminal. Here is the error:

```
ERROR: exception in Python call:
  root call: <ba.Call object; _call=<function Spaz.handlemessage.<locals>.checkDead at 0x056DE220> _args=() _keywds={}>
  root call origin: spaz.py:953
  context: <bastd.game.deathmatch.DeathMatchGame object at 0x0E0B8F58>
  real-time: 20692
  sim-time: 12592
  base-time: 12600
Traceback (most recent call last):
  File "ba_data\python\ba\_general.py", line 245, in __call__
    return self._call(*self._args + args_extra, **self._keywds)
  File "ba_data\python\bastd\actor\spaz.py", line 939, in checkDead
    dropBomb()
  File "ba_data\python\bastd\actor\spaz.py", line 943, in dropBomb
    stdbomb.Bomb(position=self.node.position,
AttributeError: 'ba.Node' object has no attribute 'position'
```

It would be great if you can help me with fixing this problem, it would be much appreciated.
Thanks, Mikahael

**Comment by alitla** [comment]
Probably the node wasn't created completely or it was destroyed at the moment of dropBomb.
You can use something like this to skip such error:

`
if not hasattr(self.node,'position'):
     return
`

**Comment by Mikahael** [comment]
Oh, it’s okay bro. There was some error in my script and I fixed it hehe. It was a timer related problem and it’s fixed now. :)

**Comment by Dliwk** [comment]
Since it was some bug in script and successfully got fixed, I will probably close this.
