### ISSUE TITLE
 error while loading shared libraries: libpython3.9.so.1.0

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#340]
## Description
bin/BombSquad_Linux_1.6.5/bombsquad: error while loading shared libraries: libpython3.9.so.1.0: cannot open shared object file: No such file or directory

## Machine
Acer Swift 1 (Pentium CPU) with fresh Ubuntu

**Comment by Mikahael** [comment]
I tried to do that as well, but it was hard, so I installed wine and ran the bomb squad windows version through that.

**Comment by chelikol** [comment]
Thanks for the answer. Meanwhile, i took the snap Store version. This works, but it's an older version 1.5.29.

**Comment by Dliwk** [comment]
Check this [article][1]. Your problem can be possible fixed with this `apt install python3.9-dev`.

[1]: https://github.com/efroemling/ballistica/wiki#python-39

**Comment by chelikol** [comment]
After `apt install python3.9-dev` i got another  error message:
_error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory_

**Comment by chelikol** [comment]
After `apt install python3-pip python3.9-dev libopenal-dev libsdl2-dev libvorbis-dev cmake clang-format` it works. It is important not to run with the absolute path `bin/BombSquad_Linux_1.6.5/bombsquad`, but with the local path `./bombsquad`.
The Windows version works with `wine` as well.
Thank you very much for your hints :-).

**Comment by chelikol** [comment]
Same Problem with python3.12.
First install 3.12
```
 sudo add-apt-repository ppa:deadsnakes/ppa
 sudo apt update
 sudo apt install python3.12
```
Second: `sudo apt-get install libpython3.12-dev`
