### ISSUE TITLE
Chat messages for a specific player do not work

### ISSUE THREAD

**Issue by IvanPragma** [efroemling/ballistica#342]
A long time ago (in version 1.5) I tried to send a message to a specific player, but I failed. Nothing works on 1.6 either.
When I set `clients`, no message is sent to the selected player.
#32

**Comment by alitla** [comment]
are you talking about _ba.chatmessage? If yes then i don't think it was ever possible to send a chat message to specific player
the only option to show something to a specific player is _ba.screenmessage. almost everything else is seen by all players

**Comment by IvanPragma** [comment]
Yes, _ba.chatmessage. In commit https://github.com/efroemling/ballistica/commit/c95357e3d0dcf24fb761edd70070a85c69b798c4 , Eric added an additional argument 'clients' to the _ba.chatmessage function, and said that now it can send messages to a specific player.

**Comment by Freaku17** [comment]
Still doesn't work? :/

**Comment by IvanPragma** [comment]
Yes

**Comment by IvanPragma** [comment]
@efroemling, what is the reason for this problem and why can't it be solved?

**Comment by efroemling** [comment]
As of a few minutes ago, this code should be exposed here if you want to dive into what's not working for you. Look for the definition of `_ba.chatmessage`  in python_methods_ui.cc and `ConnectionSet::SendChatMessage()` that it calls into. There are some limitations right now such as the client-list option only working when called from the host. Are you trying to run it as a client perhaps?

**Comment by IvanPragma** [comment]
Thanks, I'll take a look.

> Are you trying to run it as a client perhaps?

No, I tried from the server console (using mgr), and from the plugin code running on the server.
