### ISSUE TITLE
Bots prevent players from playing on servers.

### ISSUE THREAD

**Issue by IvanPragma** [efroemling/ballistica#344]
## Problem
Several people have written a program that opens many Bomb Squad windows on their PC, each time creating a new account, and logs into a specific server, thereby completely filling it. They periodically jump so that they are not kicked by the auto-kick.

It is useless to kick them, because new ones will come in.

![BombSquad 30 11 2021 22_01_28](https://user-images.githubusercontent.com/74207898/144094871-e55ec469-eb9e-449a-8a9f-e31db2e64ff8.png)

## Solution
I think that having access to the ip addresses of the players, we could kick "suspicious" players from the server, for example, if there are more than 2 players on the server with the same ip address -> kick them.

If it's possible, then it's probably worth adding it to the game roster.

**Comment by imayushsaini** [comment]
Not a good idea to make IP address public , consider the privacy of players . 
Also blocking more then one connection from same IP is not fair for genuine players playing on wifi.

What u can do is auto kick new accounts (we have access to check account creation date).

It would be great if Eric can restrict users  creating multiple accounts from same IP.

**Comment by IvanPragma** [comment]
> Also blocking more then one connection from same IP is not fair for genuine players playing on wifi.

Yes, I agree, it's not worth blocking. But this should be taken into account, for example, if the player's behavior is considered "suspicious", we should also check for the same ip. And only if a player is considered "suspicious" and there is already a player with the same ip address on the server - we can kick him.

> What u can do is auto kick new accounts (we have access to check account creation date).

Bots don't always use new accounts, they often create huge networks of accounts, wait a month, and only after that they start using them.

**Comment by IvanPragma** [comment]
> It would be great if Eric can restrict users creating multiple accounts from same IP.

Yes, that would be very good :)

**Comment by Mikahael** [comment]
Pardon me but, it may be possible to kick a player base on their stand message for a limited amount of time. If spaz, in somewhat radius of 3 for 3-4 min straight, kick that spaz out of the game, or remove him.

**Comment by IvanPragma** [comment]
> Pardon me but, it may be possible to kick a player based on their stand message for a limited amount of time rather than meddling with accounts or up address. If spaz, in somewhat radius of 3 for 3-4 min straight, kick that spaz out of the game, or remove him.

I don't quite understand you

**Comment by drov-drov** [comment]
#298

**Comment by Mikahael** [comment]
What it means is, if spaz stay in the same location for around 3 mins straight, it doesn’t matter if he punches or jumps, if he is still in the location radius, we can command the server to kick that player. This can be easily done in bs version 1.4

**Comment by IvanPragma** [comment]
> What it means is, if spaz stay in the same location for around 3 mins straight, it doesn’t matter if he punches or jumps, if he is still in the location radius, we can command the server to kick that player. This can be easily done in bs version 1.4

Something similar is already on the servers, but it does not give much sense, new bots immediately return

**Comment by Mikahael** [comment]
Ban the id when it joins, or just let server keep kicking.

**Comment by alitla** [comment]
Seems like its endlessly creating new pc accounts
So maybe setup a fast timer (like 0.1 second) and kick any PC player?
Or kick PC accounts that their id is more than 381229....
It will make problem for new pc account to join your server but Android , Google and pervious pc players can still join
Its enough to make the attacker tired after a week or two...

**Comment by Mikahael** [comment]
You can ban new accounts to prevent spam, or what you can do is, after a player joins the server, he must type, verified, if a person tried to join and play without the verification, he is kicked and added to blacklist.

**Comment by JoseANG3L** [comment]
The only thing I think and can work is to create a White List, with the id of the people you want to play on that server, It won't take long for new people to fill out a form to get in.
