### ISSUE TITLE
Cannot run the Makefile

### ISSUE THREAD

**Issue by guyus15** [efroemling/ballistica#345]
## Description
When I try to build the project from the Makefile I get an error telling me that:
```
typing_extensions (for python3.9) is required.
To install it, try: "python3.9 -m pip install typing_extensions"
Alternately, "tools/pcommand install_pip_reqs" will update all pip requirements.
```
Even though that the `typing_extensions` module is definitely installed as when I try installing it independently with pip, it tells me it is already installed.

## Expected behavior
I expect for the project to build and run the Bombsquad application.

## Machine
**Platform**: Both Windows 10 and Ubuntu 20.04 (I tried on both).
**BombSquad version**: [1.5.27](https://github.com/efroemling/ballistica/releases/tag/v1.5.27)
**Commit**: [2642488](https://github.com/efroemling/ballistica/commit/2642488a51b250752169738f5aeeccaafa2bc8de)

**Comment by Dliwk** [comment]
Haha, I'm not the only one with this problem :smile: 
You can find a little conversation about that in [this][1] commit. 
I guess `pip list` gives you `typing-extensions` (while pip downloads `typing_extensions`)?
For the temporary solution you can revert this change: replace `typing_extensions` with `typing-extensions` [here][2].

[1]: https://github.com/efroemling/ballistica/commit/172bd3b50f26fd6c90353767de48c1b8983581eb
[2]: https://github.com/efroemling/ballistica/blob/326f6677a0118667e93ce9034849622ebef706fa/tools/batools/build.py#L43

**Comment by guyus15** [comment]
Ahh thanks so much, that got me past that error. Any ideas while it seems to fail when looking for a command which is also a directory?
`make[1]: /mnt/c/Users/chamb/Documents/Python: Command not found`
This is what I get and not really sure why its doing that.

**Comment by Dliwk** [comment]
Hm, when exactly it happens? Seems like I need some context.

**Comment by guyus15** [comment]
Well it seems to get most of the way through the building process, it even generates an executable, but it throws the error above like its trying to run a directory as a command. The above file path confuses me a bit because the `ballistica` folder isn't even in that directory. The generated executable runs but fails, saying `python39_d.dll` not found. Appreciate your help.
