### ISSUE TITLE
Cannot unlink account for 99999 days

### ISSUE THREAD

**Issue by FreakOPP** [efroemling/ballistica#346]
I'll be frank here,
So I have a default Google ID which I had linked with my other Android device and it used to properly show the dates of Unlink (like 30 then 29 and so on).

One of my friends told me that there's a way to get "tickets" by using Bombsquad AYMP modpack (which unlocks all achievements and gives 3140 tickets) and I linked 3 AYMP accounts (yes, I was greedy 😖) and now when I try to unlink it says "Cannot unlink account for 99999 days".

I'm extremely sorry for doing this, can I somehow unlink those 3 AYMP accounts?

**Comment by Mikahael** [comment]
Reset your account. (Factory Reset device, or app)

**Comment by imayushsaini** [comment]
It's your personal account issue (with your own fault), nothing related to this repository .
Don't get confused between Github issues and Game Support chat . 
If you have any problem particularly for you only reach directly on mailbox.

**Comment by FreakOPP** [comment]
Okay sry
