### ISSUE TITLE
Bug: graphic messed up, but game works 

### ISSUE THREAD

**Issue by madacol** [efroemling/ballistica#351]
# Description
Graphic has green stripes and is a mess (See screenshot), but everything else works fine

## Steps to reproduce
1. Launch BombSquad
2. Bug!

# Machine
**Platform**: Windows 10 
**BombSquad version**: [1.6.5] (https://files.ballistica.net/bombsquad/builds/BombSquad_Windows_1.6.5.zip)
Intel core i7-10750H

## Screenshots
![IMG-20220101-WA0046](https://user-images.githubusercontent.com/6379896/147860517-f8dafefe-ebcc-479a-8e32-9a1331fe8ed4.jpg)

# Extra
I think it has something to do with having an integrated (Intel UHD) and dedicated Graphic card (Nvidia GeForce rtx 3060).

If I let windows to decide which graphic to use, it will use the integrated graphic, and it looks bad like screenshot.
But if I force windows to use the Nvidia, it will look just fine 👍

**Comment by efroemling** [comment]
Unfortunately this sort of thing seems like a likely hardware or driver issue. If anyone else is able to reproduce this on similar hardware, please holler. The graphics engine code is all open in this repo so it would be possible to muck with shader code or flip switches and see if anything fixes it if anyone is feeling adventurous.

**Comment by efroemling** [comment]
I'll go ahead and close this, assuming its a hardware-specific issue. If anyone can reproduce it on other hardware please reopen.
