### ISSUE TITLE
Bombsquad Windows Build 1.6.7 Flagged as Malware 

### ISSUE THREAD

**Issue by iGuEs5** [efroemling/ballistica#357]
Out of curiosity someone that I know scanned the .exe file with VirusTotal, and according to that antivirus service, several files were flagged as virus/malware/trojans. The files in question are shown in the attached photo.![unknown-2.png](https://user-images.githubusercontent.com/45712861/152017682-773f47d8-e5ce-4fd3-adaa-2c01c56ea6a2.png) Are these some false positives by any means?

**Comment by Dliwk** [comment]
I guess it's better to discuss in already existing #195 and #349. 

Brief summary:
> **erfoemling** wrote:
> My assumption is that this was a false positive.
I did go ahead and add a checksum stage to my build scripts. My build server will now write out checksums to a separate server just before it uploads the packages to files.ballistica.net.
>
> I went ahead and put together an automated builds page at https://tools.ballistica.net/builds which contains these checksums as well as direct links to the corresponding files and extra info such as build-numbers. A link is available in the Resources section of the new tools portal at https://tools.ballistica.net/.
