### ISSUE TITLE
ФАТАЛЬНАЯ ОШИБКА: Необработанное исключение в BallisticaMain(): Не выполнено предварительное условие: glActiveTexture != nullptr 

### ISSUE THREAD

**Issue by IamKING3S** [efroemling/ballistica#360]
![Снимок экрана 2022-02-05 052412](https://user-images.githubusercontent.com/99104214/152664132-dd5e9215-491e-4932-9675-ec28c07825cf.png)
When I log into the game I get an error this error

**Comment by Dliwk** [comment]
Possibly another duplicate of #275 and #202, discuss there.
