### ISSUE TITLE
Chat system Enhancement suggestion

### ISSUE THREAD

**Issue by krahma9990** [efroemling/ballistica#370]
### Hello guys,

I wanted to make a suggestion concerning **the chat system**.

Have you not noticed?

how huge size of the text bubble? For example, when playing on the ZigZag map (King of the Hill),

When a large number of messages are sent at once, it blocks the view.

And sometimes It disappears swiftly that you can even read it....

As a result, I propose the following:

***1-Move the conversation bubbles from the middle of the screen to one of the sides.***

***2-The conversation bubble fades by 85% instead of disappearing.***

***3-Place the character icon next to the player's name.***

Example:

### When chatting...
![Screenshot_518](https://user-images.githubusercontent.com/42889595/158720372-a05eda79-b6ae-4d26-bb78-44ef734b73d3.png)

### And when the chat cools down...
![Screenshot_5181](https://user-images.githubusercontent.com/42889595/158720503-edf8b834-d8b0-4fde-a4a3-b7554764c7de.png)

**Comment by DavidReadsGitHub** [comment]
That’s actually a great idea

**Comment by rexmaxwell** [comment]
Great

**Comment by Dliwk** [comment]
Let's move that to #63
