### ISSUE TITLE
Can docker installation be supported?

### ISSUE THREAD

**Issue by HelIwalker** [efroemling/ballistica#377]
Easy to use

**Comment by aryan02420** [comment]
```bash
docker pull aryan02420/bombsquad
xhost +
docker run \
  -it --rm \
  -v "/tmp/.X11-unix:/tmp/.X11-unix" \
  -v "/dev/snd:/dev/snd" \
  -e DISPLAY \
  -e LANG=en_US \
  -p 43210:43210 \
  --privileged \
  aryan02420/bombsquad
```

**Comment by HelIwalker** [comment]
> ```shell
> docker pull aryan02420/bombsquad
> xhost +
> docker run \
>   -it --rm \
>   -v "/tmp/.X11-unix:/tmp/.X11-unix" \
>   -v "/dev/snd:/dev/snd" \
>   -e DISPLAY \
>   -e LANG=en_US \
>   -p 43210:43210 \
>   --privileged \
>   aryan02420/bombsquad
> ```

How do I edit config when I deploy this on synlogy? I've put config.yaml is mapped out, but the modification will not take effect.
![屏幕截图 2022-04-12 083541](https://user-images.githubusercontent.com/19471848/162855247-0a21b200-53e7-40e4-83fe-177d63e49731.png)

**Comment by aryan02420** [comment]
```bash
docker run \
  -d --rm \
  -v "/my/config.yaml:/usr/src/app/bombsquad-server/config.yaml" \
  --net=host \
  aryan02420/bombsquad-server
```

**Comment by HelIwalker** [comment]
> 

thx！
