### ISSUE TITLE
FATAL ERROR: unable to bind to requested udp port 43210 (ipv4)

### ISSUE THREAD

**Issue by Bablue123** [efroemling/ballistica#380]
### Description
I did everything as per instruction. I made my port in config.yml file to 43210 still it shows that error when I run launch bomb squad batch file on windows. My windows is 10 and python is 3.10. please help me to host bombsquad server

**Comment by imayushsaini** [comment]
Seems like some other process running on port 43210 , did you tried killing that process first ? (You might have GUI build running on same computer that occupied your port).
In case  closing bombsquad not solves your problem .
Open command prompt. as admin 
enter  ` netstat -ano | findstr 43210`  , then you will see process id running on that port .
then enter `taskkill /F /pid <processs-id>` .

**Comment by Bablue123** [comment]
Before anything I wanted to tell that, I am not talking about this repo (if you dont know). I came from here: https://files.ballistica.net/bombsquad/builds/BombSquad_Server_Windows_1.6.12.zip When I ran the "launch_bombsquad_server.bat" file everything worked perfectly except this port issue "FATAL ERROR: unable to bind to requested udp port 43210 (ipv4)".

**Comment by Bablue123** [comment]
Btw i fixed this issue. Now i need help with creating public parties. I'll create a new issue for that. This issue has been solved.
