### ISSUE TITLE
Help with opening/forwarding routes to host a public server!

### ISSUE THREAD

**Issue by TechieGeeke** [efroemling/ballistica#382]
Hello, I am really in a depressed issue. I am really curious and excited to host a BS server of mine. I tried every possible ways. Its still not working. It says `not joinable from internet`. If anyone could help me solve this issue, trust me you are my hero forever.

**My Setup:**
> Windows: 10 (64 bit)
> Router: D-Link dir-600m

So what I did is, I forwarded my port to 43210 and it to my local IP address as mentioned in the app.
But it still shows the same. I wanted to know if I need to pay extra money for my providers for forwarding ports and if not, how can I achieve this? Or am I doing something wrong? Any help is appreciated..

![Capture](https://user-images.githubusercontent.com/95920517/164916214-0963a954-8c75-4771-99a1-cdf722690b23.JPG)

In D-Link dir-600m, there is no specific option "Port forwarding", instead this is where we forward port. This is what I got from googling. If there's a mistake, please help me correct it. 
~THANKYOU

**Comment by Dliwk** [comment]
Hi! Your "virtual server forwarding table" seems to be configured correctly, so this has to be limitation from your internet provider :(

**Comment by TechieGeeke** [comment]
> Hi! Your "virtual server forwarding table" seems to be configured correctly, so this has to be limitation from your internet provider :(

Yes you are right. I researched about this a lot and found out that, it was an issue with my ISP. My ISP doesn't provide me open ports! They told I have to pay them to do this. Thanks a lot anyways. :)
