### ISSUE TITLE
Error:precondition failed

### ISSUE THREAD

**Issue by Danis2009** [efroemling/ballistica#383]
Who can fix it?
![IMG_20220428_173325](https://user-images.githubusercontent.com/104640826/165975040-6eb81b71-083a-4e51-9a6b-0fe387c8fd5c.jpg)

![Uploading IMG_20220428_173114.jpg…]
I can't go to any server and i log in how a device but not how a pc

**Comment by Danis2009** [comment]
![Uploading IMG_20220428_173114.jpg…]()

**Comment by Danis2009** [comment]
![IMG_20220428_173114](https://user-images.githubusercontent.com/104640826/165975407-19e37018-02a5-4b18-9766-88d370b2f051.jpg)

**Comment by Dliwk** [comment]
Mmm, try deleting 'C:\Users\PC\AppData\Local\BombSquad/config.json' and 'config.json.prev' if exists.

**Comment by Danis2009** [comment]
> Mmm, try deleting 'C:\Users\PC\AppData\Local\BombSquad\config.json' and 'config.json.prev' if exists.

I dont have the appdata and these files

**Comment by Danis2009** [comment]
I Will try delete and donwload bombsquad

**Comment by Dliwk** [comment]
This is not necessary, though this is most likely empty file, so you can delete it. Anyway, did you try to launch game after deleting first two files?

**Comment by Danis2009** [comment]
> This is not necessary, though this is most likely empty file, so you can delete it. Anyway, did you try to launch game after deleting first two files?

Yes, thank you, its fix the problem
