### ISSUE TITLE
Does building custom modpacks only compatible for ballistica builds?

### ISSUE THREAD

**Issue by MrJetz** [efroemling/ballistica#385]
Can someone tell me that bombsquad in playstore isnt compatible for making modpacks?
Should i create my own modpack using builds in https://ballistica.net/builds ???

**Comment by Easy10781** [comment]
you can make plugin which overriding the game methods and classes, but it can't override the `ba.App`, `MainMenuActivity`, `MainMenuWindow`

**Comment by JoseANG3L** [comment]
@MrJetz Yes, creating modpacks only works for versions in builds
