### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by TechieGeeke** [efroemling/ballistica#387]
## Description
Could you please let us PC players signin with google play account, or atleast change our profile name from that "PCXXXXXX" to something else? Also it would be cool if we are able to buy some tickets from PC.

**Comment by Freaku17** [comment]
Hey there! 👋

You can link your GooglePlay Account with your PC Account via the Profiles tab (in bottom left of menu)

**Comment by IvanPragma** [comment]
The profile name can be changed starting from version 1.7 (v2 accounts)

**Comment by TechieGeeke** [comment]
Glad to hear that. Waiting for the new update 💯

**Comment by Dliwk** [comment]
> The profile name can be changed starting from version 1.7 (v2 accounts)
And you can try this right now with 'prefab' builds! Check out latest commits or changelog.

**Comment by Sachin247c** [comment]
> > The profile name can be changed starting from version 1.7 (v2 accounts)
> 
> And you can try this right now with 'prefab' builds! Check out latest commits or changelog.

Hey dliwk how can we? and are you available on discord?

**Comment by bseditor** [comment]
> > > The profile name can be changed starting from version 1.7 (v2 accounts)
> > 
> > 
> > And you can try this right now with 'prefab' builds! Check out latest commits or changelog.
> 
> Hey dliwk how can we? and are you available on discord?

Refer to [this](https://github.com/efroemling/ballistica/wiki/Getting-Started) page.

**Comment by Sachin247c** [comment]
> > > > The profile name can be changed starting from version 1.7 (v2 accounts)
> > > 
> > > 
> > > And you can try this right now with 'prefab' builds! Check out latest commits or changelog.
> > 
> > 
> > Hey dliwk how can we? and are you available on discord?
> 
> Refer to [this](https://github.com/efroemling/ballistica/wiki/Getting-Started) page.

well i tried everything! everything was going smooth until "tools/pcommand list_pip_reqs" and was just showing some python error! i tried everything i could (removing it , again installing it , lot google search ) no solution ://

**Comment by bseditor** [comment]
Post ur error with terminal Screenshot?

**Comment by Sachin247c** [comment]
![Uploading Screenshot 2022-06-02 115705.png…]()

**Comment by Sachin247c** [comment]
![Screenshot 2022-06-02 115705](https://user-images.githubusercontent.com/67496924/171566865-d28729a4-d7bb-44e6-85d9-86e81977b958.png)

**Comment by Sachin247c** [comment]
See im no pro in this Dev thing but just using all my knowledge , common sense and some googling but nothing worked!

**Comment by bseditor** [comment]
You need to install python 3.10 for this which u can do by executing `sudo apt install python3.10` cmd in terminal.

**Comment by Dliwk** [comment]
> ![Screenshot 2022-06-02 115705](https://user-images.githubusercontent.com/67496924/171566865-d28729a4-d7bb-44e6-85d9-86e81977b958.png)
> 

Haha, you were referred to wiki just in time when ballistica moved from python 3.9 to 3.10 but nobody updated Getting Started wiki section yet. 

As mentioned, you should install python 3.10: execute commands from wiki but replace all the "3.9" with "3.10".

**Comment by Sachin247c** [comment]
> > ![Screenshot 2022-06-02 115705](https://user-images.githubusercontent.com/67496924/171566865-d28729a4-d7bb-44e6-85d9-86e81977b958.png)
> 
> Haha, you were referred to wiki just in time when ballistica moved from python 3.9 to 3.10 but nobody updated Getting Started wiki section yet.
> As mentioned, you should install python 3.10: execute commands from wiki but replace all the "3.9" with "3.10".

whaaaaaaaaaaaaa? "sudo apt update && sudo apt dist-upgrade && sudo apt install python3-pip python3.9 cmake clang-format" just have to update 3.9 to 3.10 ?

**Comment by Sachin247c** [comment]
![Screenshot 2022-06-02 121437](https://user-images.githubusercontent.com/67496924/171569439-ae98ea50-c698-4838-9c0d-b297ba6fbe6b.png)
   
Nothing seems to workkk :/

**Comment by Dliwk** [comment]
> whaaaaaaaaaaaaa? "sudo apt update && sudo apt dist-upgrade && sudo apt install python3-pip python3.9 cmake clang-format" just have to update 3.9 to 3.10 ?
> 

Well, in case you already ran these commands, you need only `sudo apt install python3.10-dev`.

(sorry I accidentally edited your comment instead of quoting it)

**Comment by Sachin247c** [comment]
![Screenshot 2022-06-02 121847](https://user-images.githubusercontent.com/67496924/171570049-494d8a52-1a99-44d5-9745-264f131bcbfc.png)
well tried it already , but here again! btw you on discord?

**Comment by Dliwk** [comment]
> ![Screenshot 2022-06-02 121437](https://user-images.githubusercontent.com/67496924/171569439-ae98ea50-c698-4838-9c0d-b297ba6fbe6b.png)
>    
> Nothing seems to workkk :/ 

Hmmm, I'm not an Ubuntu user, but perhaps 3.10 is only for Ubuntu 22.04 (or whatever called latest release) and you, perhaps, trying to install it to older 20.04? 🤷

**Comment by Sachin247c** [comment]
My version of Ubuntu says "ubuntu 20.04.4" :/

**Comment by Dliwk** [comment]
> btw you on discord?

Yes I think you can reach me there Dliwk#7961

**Comment by Sachin247c** [comment]
![Screenshot 2022-06-02 122225](https://user-images.githubusercontent.com/67496924/171570587-e147546c-582d-467f-af46-fc1e8317e2f5.png)

well while downloading ubuntu 20.04 i saw newer 22.04 but well i did just according to wiki :/

**Comment by Dliwk** [comment]
> ![Screenshot 2022-06-02 122225](https://user-images.githubusercontent.com/67496924/171570587-e147546c-582d-467f-af46-fc1e8317e2f5.png)
> 
> well while downloading ubuntu 20.04 i saw newer 22.04 but well i did just according to wiki :/ 

Yes, as I mentioned, nobody updated wiki yet :( I will as soon as I get home.

**Comment by efroemling** [comment]
Hey folks; the wiki is updated now. Basically to get Python 3.10 on Ubuntu 20 or older you need to add the [deadsnakes ppa](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) which will let you install Python versions outside of the one or two that are available for the OS. Ubuntu 20 came with Python 3.8 and more recently added Python 3.9 but For 3.10 you need deadsnakes. (or you could build from source or use [pyenv](https://github.com/pyenv/pyenv))
