### ISSUE TITLE
Building from source fails with GCC 12

### ISSUE THREAD

**Issue by ritiek** [efroemling/ballistica#412]
### Description

I upgraded my gcc to 12.1 and building ballistica from source now fails.

### Steps to reproduce
```bash
$ make cmake
...
[ 29%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/generic/utils.cc.o
[ 29%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/graphics_server.cc.o
[ 29%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/graphics.cc.o
[ 30%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/mesh/image_mesh.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/mesh/mesh_data_client_handle.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/mesh/text_mesh.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/mesh/mesh_data.cc.o
[ 31%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/net_graph.cc.o
[ 32%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/render_pass.cc.o
[ 32%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/render_target.cc.o
/home/ritiek/Downloads/ballistica-custom/src/ballistica/generic/utils.cc: In constructor ‘ballistica::Utils::Utils()’:
/home/ritiek/Downloads/ballistica-custom/src/ballistica/generic/utils.cc:120:17: error: static assertion failed
  116 |   static_assert(static_type_name_constexpr<decltype(g_app_globals)>()
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  117 |                     == "ballistica::AppGlobals *"
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  118 |                 || static_type_name_constexpr<decltype(g_app_globals)>()
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  119 |                        == "ballistica::AppGlobals*"
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  120 |                 || static_type_name_constexpr<decltype(g_app_globals)>()
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  121 |                        == "class ballistica::AppGlobals*");
      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ritiek/Downloads/ballistica-custom/src/ballistica/generic/utils.cc:126:7: error: static assertion failed
  124 |       static_type_name_constexpr<decltype(testnode)>()
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  125 |           == "ballistica::Object::Ref<ballistica::Node>"
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  126 |       || static_type_name_constexpr<decltype(testnode)>()
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  127 |              == "class ballistica::Object::Ref<class ballistica::Node>");
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 32%] Building CXX object CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/graphics/renderer.cc.o
make[4]: *** [CMakeFiles/ballisticacore.dir/build.make:874: CMakeFiles/ballisticacore.dir/home/ritiek/Downloads/ballistica-custom/src/ballistica/generic/utils.cc.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/ritiek/Downloads/ballistica-custom/build/cmake/debug'
make[3]: *** [CMakeFiles/Makefile2:111: CMakeFiles/ballisticacore.dir/all] Error 2
make[3]: Leaving directory '/home/ritiek/Downloads/ballistica-custom/build/cmake/debug'
make[2]: *** [CMakeFiles/Makefile2:118: CMakeFiles/ballisticacore.dir/rule] Error 2
make[2]: Leaving directory '/home/ritiek/Downloads/ballistica-custom/build/cmake/debug'
make[1]: *** [Makefile:137: ballisticacore] Error 2
make[1]: Leaving directory '/home/ritiek/Downloads/ballistica-custom/build/cmake/debug'
make: *** [Makefile:856: cmake-build] Error 2
```

### Machine
**Platform**: Manjaro 21.2.6
**BombSquad version**: 1.7.0
**Commit**: [8ddaf71](https://github.com/efroemling/ballistica/commit/8ddaf71bf8b73470ebaf572af8c610ad664c027d)

### Extra
I downgraded to gcc 11.2 and can now compile ballistica alright!

**Comment by efroemling** [comment]
The whole static_type_name_constexpr() thing is just supposed to take that long mess (in your test case `std::string_view static_type_name_constexpr(bool) [with T = foobar::Foo*; std::string_view = std::basic_string_view<char>]`) and trim it down into something human readable like `foobar::Foo*`. It is doing that by assuming the string starts and ends with a fixed substring and trimming away the length of those. The static_assert is there to catch our attention when the formatting changes, which apparently is what happened between gcc 11 and 12.
Ideally I think the fix would be to change static_type_name_constexpr() to look for `[with T = ` in the string and trim everything up to that so it would be more flexible to formatting changes, but I'm not well versed with constexpr stuff so I don't know what is possible within one. (I believe as of C++17 std::string_view can be used within a constexpr but not std::string).
Anyway if anyone wants to take a swing at updating this to do the right thing, feel free. Otherwise I'll try to get to it soon.

**Comment by Dliwk** [comment]
> The whole static_type_name_constexpr() thing is just supposed to take that long mess (in your test case `std::string_view static_type_name_constexpr(bool) [with T = foobar::Foo*; std::string_view = std::basic_string_view<char>]`) and trim it down into something human readable like `foobar::Foo*`. It is doing that by assuming the string starts and ends with a fixed substring and trimming away the length of those. The static_assert is there to catch our attention when the formatting changes, which apparently is what happened between gcc 11 and 12.

I wanted to draw attention to the fact that `namespace::` prefix is missing (but not in small example above, it returns `foobar::Foo*`). Though I just updated last one and moved static_type_name funcs to same namespace as Foo and bar:
<details>

```c++
#include <iostream>

namespace ballistica {
// simplified version of original from core/inline.h
template <typename T>
constexpr auto static_type_name_constexpr(bool debug_full = false)
    -> std::string_view {
  std::string_view name = __PRETTY_FUNCTION__;
  return name;
}

template <typename T>
static auto static_type_name(bool debug_full = false) -> std::string {
  return std::string(static_type_name_constexpr<T>(debug_full));
}
}


namespace ballistica {
    class Foo {};
}

namespace ballistica {
    void bar() {
        auto foo = new Foo();
	std::cout << static_type_name<decltype(foo)>() << std::endl;
    }
}

int main() {
    ballistica::bar();
}
```
</details>

And now it prints `constexpr std::string_view ballistica::static_type_name_constexpr(bool) [with T = Foo*; std::string_view = std::basic_string_view<char>]` (without `ballistica::`). Formatting didn't changed and it still fits into same boundaries, except missing namespace prefix.

**Comment by efroemling** [comment]
Yeah; I noticed the ballistica:: prefix was missing in yours. Maybe gcc 12 changed to no longer include the namespace only in some conditions (like when the evaluation is happening within that namespace?..)

Regardless, it seems that we may now get this prefix in some cases:
`constexpr std::string_view static_type_name_constexpr(bool) [with T = `
Whereas the current code assumes it will be this when trimming the string:
`constexpr std::string_view ballistica::static_type_name_constexpr(bool) [with T = `
This could lead to incorrect trimming. Perhaps that's why we got "AppGlobals*" instead of "ballistica::AppGlobals*".

So I still think the cleanest solution is to calc the prefix/suffix lengths instead of hard-coding them (the last link I posted)

**Comment by efroemling** [comment]
Ok I think while it's fresh on my mind I'll go ahead and update to the dynamic prefix detection code. And while I'm in there I'll add plain "AppGlobals*" as a valid result in the static_assert().  (unless you are already doing the same; let me know if that's the case and I'll hold off).

**Comment by Dliwk** [comment]
> unless you are already doing the same

I didn't start because I assumed the same thing about you :smile: 

Cool, probably this issue can be closed after this commit.

**Comment by efroemling** [comment]
Ok the fix is pushed. Can one of you try it on gcc 12 and see if its behaving now?

**Comment by efroemling** [comment]
Ah yes I noticed that right after I kicked off a push. 😬. Updated one should be there now.
