### ISSUE TITLE
FATAL ERROR: Unhandled exception in BallisticaMain(): SDL_Init failed: No available video device

### ISSUE THREAD

**Issue by bseditor** [efroemling/ballistica#414]
Getting this error while executing `make prefab-gui-debug` cmd
![Capture](https://user-images.githubusercontent.com/51753219/171366118-440b0537-5b64-4bd7-bff2-db46128c7e8d.JPG)
.

**Comment by bseditor** [comment]
Sounds like I shouldn't!

**Comment by Dliwk** [comment]
You can perform `make prefab-windows-x86-gui-debug-build` and grab your build at ~/ballistica/build/prefab/full/windows_x86_gui/debug/

**Comment by bseditor** [comment]
> You can perform `make prefab-windows-x86-gui-debug-build` and grab your build at ~/ballistica/build/prefab/full/windows_x86_gui/debug/
> 
> After that you can download this directory to your local PC and launch game there.

It worked flawlessly. thx
