### ISSUE TITLE
Can't add new maps

### ISSUE THREAD

**Issue by EraOSBeta** [efroemling/ballistica#416]
Hello! So I've been trying to do some modding on BombSquad (1.6.9), but I've ran into issues from the very beginning, I've been trying to add my own custom maps, I would use blender 2.77 with the .bob (and .cob) import and export plugin (3.1 doesn't support that plugin), create a map, export the files, rename them to the name of files for another map and replace them, then boom, custom map; but that's "replacing" the map, I want to "add" new maps, I thought adding new maps would be easy, I would just put the files in the right folders with their own names, I would open maps.py, I would copy and paste the code for one of the maps, then replace all of the file names to the one that I want to use and customize the game modes it can be played on, make sure the map function doesn't flag it as duplicate, and boom, map would get added, not. It didn't work, the map wasn't in the map selector, and there weren't any errors either, can anyone help me out here? Is this a bug or am I just simply too dumb? I can't currently attach any files since I'm away from my computer, but I will if the problem doesn't get solved until I go back home (in 2 days). Thanks in advance!

**Comment by Dliwk** [comment]
Sorry but I don't think starting with custom maps, models and stuff is a good idea (at least before [1.8][1] where that process should become a bit more simple). You mentioned you added your map to 'maps.py' but your map also should be registered in ba._app (which simply contains hard-coded list of maps now; in future there could be some [meta-tag][2] or what).

If you're new to modding (if I correctly understood your "I've been trying to do some modding ... ran into issues from very beginning"), firstly I'd recommend read these wiki pages:
- [Getting Started][3] to set up your environment and being able to build game (just noticed; now it also contains nice topic about virtual environment)
- [Knowledge Nuggets][5] has 3 simple hello worlds which could be a good starting point 
- [Python Overview][4] to understand difference between ba, bastd and other modules
- [Editor Setup][6] is short topic about setting up PyCharm or Emacs for working with ballistica
- [Coding Style Guide][7]
- And everything remaining

[1]: https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-18
[2]: https://github.com/efroemling/ballistica/wiki/Meta-Tag-System
[3]: https://github.com/efroemling/ballistica/wiki/Getting-Started
[4]: https://github.com/efroemling/ballistica/wiki/Python-Overview
[5]: https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets
[6]: https://github.com/efroemling/ballistica/wiki/Editor-Setup
[7]: https://github.com/efroemling/ballistica/wiki/Coding-Style-Guide

**Comment by EraOSBeta** [comment]
aight that's a problem solved :D
