### ISSUE TITLE
Precondition failed: hExt.dxgiFormat == 0

### ISSUE THREAD

**Issue by TheNotEasy** [efroemling/ballistica#432]
I created my texture and when I want to load it an error occurs
Unhandled exception in media thread:
Precondition failed: hExt.dxgiFormat == 0.
I used nvidia texture tools plugin for photoshop

**Comment by Easy10781** [comment]
How to add this "help wanted" label 😂

**Comment by IvanPragma** [comment]
Perfect!

**Comment by TheNotEasy** [comment]
> Perfect! How did you solve this problem?

I just saved in png and found png to dds [converter](https://convertio.co/ru/png-dds/)
