### ISSUE TITLE
Do not let people create V2 account same as a device name

### ISSUE THREAD

**Issue by FAL-Guys** [efroemling/ballistica#438]
For example my device account name is PC1234, and I create V2 account with PC1234 tag; so do not let them to create such accounts because it can cause problems for their friends or server owners...

**Comment by efroemling** [comment]
Thanks for the heads-up on this.

I just went ahead and added server-side code to prohibit any device-account prefixes followed by numbers (or letters like capital 'o', lowercase 'L', or capital 'i' which can look like numbers). Here's the code if you want to see if it seems like I'm missing anything:

```python
# Disallow things like PC1234 which can be used to spoof
# V1 device accounts.
for prefix in ('server', 'mac', 'rift', 'pc', 'iircade', 'vr',
               'android', 'ios', 'linux'):
    if ltag.startswith(prefix) and ltag.removeprefix(prefix).replace(
            'o', '0').replace('l', '1').replace('i', '1').isdecimal():
        raise CleanError(f'Names consisting of \'{prefix}\''
                         ' followed only by numbers (or letters'
                         ' looking like numbers) are prohibited.')
```

All account types will eventually be migrated to V2 accounts, so at some point everyone will have a unique tag of their own choosing and this sort of thing won't be a problem anymore. But for now while there is the potential of V2 account tags overlapping with V1 account names I'll try to do what I can to avoid confusion.

**Comment by FAL-Guys** [comment]
That's perfect, Thank's. also please consider checking lowercase 'L' in '**i**os' and capital 'i' in '**l**inux' if needed.
