### ISSUE TITLE
Upload files directly to workspaces

### ISSUE THREAD

**Issue by itsre3** [efroemling/ballistica#439]
Tested out the workspaces and seems to be working very well. Besides that, there is a feature which should be added. It would have been nice if there would be an option to upload files directly to workspaces from our devices

**Comment by efroemling** [comment]
Glad it's been working well for you so far 👍.
I'm right in the middle of working on some upload/download options. Planning on having 2 things:
- ability to upload single files from the 'add files/folders' screen.
- the `becloud` tool in this repo will be usable to sync entire workspaces to or from a computer for people who want to use their own editor, push workspaces to GitHub, etc.

I'll get a Workspaces wiki page up explaining this stuff in more detail as soon as it's done. Shouldn't be much longer now.

**Comment by efroemling** [comment]
Quick update here: I've added a [wiki page](https://github.com/efroemling/ballistica/wiki/Workspaces) about workspaces.
I've also finished the second of my two list items above: the `bacloud` tool can now be used to upload/download entire workspaces. (Here's the [section](https://github.com/efroemling/ballistica/wiki/Workspaces#offline-editing-with-bacloud) for it in the wiki page).
I'll try to get the first part finished soon (a simple 'upload file' option for the online workspace editor).

Let me know if you run into any problems with any of this stuff or have ideas for improvements.

**Comment by efroemling** [comment]
Another quick update: Just got individual file uploading added to the web ui. Holler if you run into any problems with it.
<img width="686" alt="Screen Shot 2022-07-02 at 10 15 35 PM" src="https://user-images.githubusercontent.com/10857610/177025971-c7401898-5c63-48ce-a942-444d06d11017.png">

**Comment by efroemling** [comment]
One more thing: just added a download button to grab individual files, so you can download files, edit them, and re-upload them individually if you like.

Hopefully, with these 3 additions, workspaces should be pretty useable now. Please holler if there's anything else that would be useful to have.

<img width="686" alt="Screen Shot 2022-07-03 at 12 22 14 PM" src="https://user-images.githubusercontent.com/10857610/177054339-e59a62db-db21-4bb9-ad18-1abd225c2294.png">

**Comment by Dliwk** [comment]
@itsre3 wanted to say "Cool, thanks!" and close this, but couldn't, so he asked me to help. :man_shrugging: :)

By the way, in your last screenshot there is 'light' theme (it seems like I saw it once?..), but first one contains website with dark theme. How does it work?

**Comment by efroemling** [comment]
> By the way, in your last screenshot there is 'light' theme (it seems like I saw it once?..), but first one contains website with dark theme which I usually see. How does it work?

I set up the css for ballistica.net to use a light or dark theme based on whether the OS/browser is in 'dark mode'. Most recent OS versions should have some sort of global dark mode switch. Or perhaps some browsers support overriding it. I've got my Mac set up to switch to dark mode at night so you can tell what time of day I made a given screenshot 😬.
Are you folks able to switch to dark mode that way? I can look into adding an explicit site setting for it if not.

**Comment by Dliwk** [comment]
Hmm yeah seems like it's depending on current firefox theme.
