### ISSUE TITLE
Hooks doesn't work in release builds

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#44]
Hooks from `ba/_hooks.py` works only in debug builds.

**Comment by efroemling** [comment]
Are you perhaps trying to edit them directly in the build directory?
In release builds you currently have to blow away the associated .pyc file before changes to the .py file will get detected. If you edit in the source directory and rebuild then the .pyc should be updated automatically.

This explains more: https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#python-cache-files-and-release-builds

**Comment by Dliwk** [comment]
:man_facepalming: Oh, thanks, I forgot about it.

Hmm, ok, but I can't seem to redefine hooks from Python code; it feels like the internal layer is using a copy of them.

**Comment by Dliwk** [comment]
And it seems `make update` doesn't work (it doesn't detect new files and/or directories)... Perhaps I should create another issue for this purpose :thinking:

**Comment by efroemling** [comment]
If 'make update' isn't working for you then yes that could be a separate bug unto itself. Or if you want to diagnose it yourself, it is not doing anything *too* crazy; `make update` just calls tools/update_project which will itself call tools/update_assets_makefile to rewrite part of assets/Makefile based on what files it finds. The result should be that new files you add under assets/src/ should end up listed in assets/Makefile after you run `make update`. Is that not happening for you?

**Comment by efroemling** [comment]
> 🤦‍♂️ Oh, thanks, I forgot about it.
> 
> Hmm, ok, but I can't seem to redefine hooks from Python code; it feels like the internal layer is using a copy of them.

The only 'copy' of them it could be using is the .pyc file I think. Did you delete that for sure or are you working in the assets source directory for sure?

As a test, I just edited assets/src/ba_data/python/ba/_hooks.py and added a 'print("hello world")' under the `launch_main_menu_session()` function. Then I ran `make prefab-debug` and got the 'hello world' output when the game launched. Do those same steps not work for you?

**Comment by Dliwk** [comment]
I haven't tools/update_assets_makefile... And tools/update_project just do nothing if it can't find this executable.

> If 'make update' isn't working for you then yes that could be a separate bug unto itself. Or if you want to diagnose it yourself, it is not doing anything _too_ crazy; `make update` just calls tools/update_project which will itself call tools/update_assets_makefile to rewrite part of assets/Makefile based on what files it finds. The result should be that new files you add under assets/src/ should end up listed in assets/Makefile after you run `make update`. Is that not happening for you?

**Comment by efroemling** [comment]
🤦🏼‍♂️
That is definitely a bug. That file is supposed to be there. I'll get that fixed now..

**Comment by Dliwk** [comment]
> The only 'copy' of them it could be using is the .pyc file I think. Did you delete that for sure or are you working in the assets source directory for sure?
> 
> As a test, I just edited assets/src/ba_data/python/ba/_hooks.py and added a 'print("hello world")' under the `launch_main_menu_session()` function. Then I ran `make prefab-debug` and got the 'hello world' output when the game launched. Do those same steps not work for you?

Yes, this way works fine, ~but I can't use something like `ba._hooks.filter_chat_message = my_filter_chat_message`~
Hmm, now it works but... yesterday I couldn't do it :thinking: :thinking:

**Comment by Dliwk** [comment]
Ok, I think this issue may be closed.

**Comment by efroemling** [comment]
Ok; I got the update_assets_makefile script added. You should now be able to do `make update` and see new scripts show up in assets/Makefile and in builds. Please let me know if not.
