### ISSUE TITLE
always remis

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#440]
### Description
In several games, there is no time counter. So, nobody wins. Always remis.

### Steps to reproduce
1. Launch BombSquad linux 1.7.2
2. play

### Expected behavior
count down timer

### Machine
**Platform**:  Ubuntu 20.04 LTS 
**BombSquad version**:  1.7.2

**Comment by efroemling** [comment]
Can you explain a bit more?
What is 'remis'?
And which mini-game is this, etc.?  Is it one that is expected to have a timer?

**Comment by chelikol** [comment]
remis means undecided, nobody wins after five minutes. Yes, Games with
Timer.

Eric Froemling ***@***.***> schrieb am Sa., 25. Juni 2022,
00:21:

**Comment by chelikol** [comment]
Here a screenshot:

![Bildschirmfoto von 2022-06-25 21-51-49](https://user-images.githubusercontent.com/66850897/175788678-0ce92cd1-4f42-49dc-9cfa-0926b8930410.png)

**Comment by chelikol** [comment]
![Bildschirmfoto von 2022-06-25 22-02-27](https://user-images.githubusercontent.com/66850897/175788952-d22d2f9a-ad25-497b-8ae0-a90add7489c1.png)

**Comment by chelikol** [comment]
Went back to 1.7.1. No difference.

**Comment by chelikol** [comment]
Seems to be a bug in the server version. Most time I play with Germany1, Germany2 or Germany3.

**Comment by efroemling** [comment]
On taking a look at this, it seems to be the King-of-the-Hill bug that was recently fixed: https://github.com/efroemling/ballistica/pull/436

The public servers should be running the fixed version I think. Can you confirm this or are you still seeing the problem?

**Comment by chelikol** [comment]
I tried it a few minutes ago with Germany1,2,3 with my version (1.7.2 linux). No difference, the problem is still there.

**Comment by chelikol** [comment]
Now I tried Italy2 with the same problem. After some time I got the message "server is restarted". But even after the restart, the problem remains.

**Comment by efroemling** [comment]
Ok I'm doing a full update on all my servers to make sure they're on the latest build. This should be done one hour from now. Can you let me know if you still see this after that?

And just so you know: this problem is in the Python code that runs on the server, so it shouldn't matter which client version you are using.

**Comment by chelikol** [comment]
Now I played on Germany3. Bug seems to be fixed. Thank you very much for that. And especially for having built such a great game!!!

**Comment by efroemling** [comment]
Glad to hear! And thanks for reporting that. It's easy for little things like this to slip by occasionally so I really appreciate the heads-up.
