### ISSUE TITLE
King of the hill isnt working right

### ISSUE THREAD

**Issue by MrJetz** [efroemling/ballistica#442]
### Description
While playing, i noticed that players cant take over the flag and its impossible to play (unless the time limit isnt None)

### Steps to reproduce
1. Launch BombSquad
2. Play king of the hill
3. Approach the flag
4. Bug!

### Expected behavior
Maybe kingofthehill.py had an error

### Machine
**Platform**: Android 10 (Realme C11)
**BombSquad version**: [1.7.2](https://github.com/efroemling/ballistica/releases/tag/v1.7.2)

### Video
https://user-images.githubusercontent.com/99152077/175795399-4453fc3a-596e-4d1e-93f4-6531f8a86ebb.mp4

**Comment by krahma9990** [comment]
Yes, I have noticed that...
All minigames that have Timer does not work well

**Comment by imayushsaini** [comment]
solved in #436
