### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by secghost** [efroemling/ballistica#454]
i will run a make prefab-gui-debug but thats error like this

make[1]: Entering directory '/home/secghost/ballistica'
Checking environment...
rsync is required; please install it via apt, brew, etc.
make[1]: *** [Makefile:959: .cache/checkenv] Error 1
make[1]: Leaving directory '/home/secghost/ballistica'
make_prefab failed with error: Command '['make', 'prefab-windows-x86-gui-release-build']' returned non-zero exit status 2.
make: *** [Makefile:145: prefab-gui-release-build] Error 255

**Comment by Dliwk** [comment]
Did you follow [Getting Started][1] guide? Seems like it's missing step with installation of rsync; try `sudo apt install rsync` (if you're running Ubuntu on WSL).

[1]: https://github.com/efroemling/ballistica/wiki/Getting-Started

**Comment by efroemling** [comment]
> Did you follow [Getting Started][1] guide? Seems like it's missing step with installation of rsync; try `sudo apt install rsync` (if you're running Ubuntu on WSL).

Hmm yes we should add rsync to the list of stuff to install with apt/homebrew/etc. in the guide if it's not there...

**Comment by secghost** [comment]
thanks its worked
