### ISSUE TITLE
ImportError: cannot import name 'Player' from _ba (unknown location) - Windows

### ISSUE THREAD

**Issue by KoLenka12** [efroemling/ballistica#46]
Error of startup BallisticaCore 1.5 (build 20060) on OS Windows. I have not encountered this error in previous builds

```
BallisticaCore 1.5.0 build 20060.
Traceback (most recent call last):
  File "<string>", line 98, in <module>
  File "<string>", line 90, in _ballistica_bootstrap
  File "ba_data\python\ba\__init__.py", line 31, in <module>
    from _ba import (CollideModel, Context, ContextCall, Data, InputDevice,
ImportError: cannot import name 'Player' from '_ba' (unknown location)
Error in ba Python bootstrapping.
```

**Comment by efroemling** [comment]
Hmm; it looks like something in your build might be out-of-date.  For one, that code should not be trying to import 'Player' from _ba. In the current code, that should be 'SessionPlayer'. 

https://github.com/efroemling/ballistica/blob/93f3900b99b457bca7a0749b30736fd93e1d2c9b/assets/src/ba_data/python/ba/__init__.py#L31

Perhaps try something like `make prefab-clean; git pull; make prefab-debug` and see if that works?.. I just tried the 20060 build on windows and it worked on my end.

**Comment by Dliwk** [comment]
:man_shrugging: I shared this build with @KoLenka12 and it works for me and it is latest build...

**Comment by efroemling** [comment]
On a related note, I'll start releasing proper pre-built BombSquad 1.5 builds later today so anyone who just wants to run things and not bother with building them will be able to grab those...

**Comment by KoLenka12** [comment]
Now I tried to unpack the archive to another folder. And I got another error

```
BallisticaCore 1.5.0 build 20060.
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001e78 (most recent call first):
```

![6l6wPs3JvII](https://user-images.githubusercontent.com/58659520/84080003-295fc000-a9e4-11ea-81dd-fc345ecdfb1f.jpg)
![li-hYPwIdZQ](https://user-images.githubusercontent.com/58659520/84080007-2bc21a00-a9e4-11ea-8898-327862f63337.jpg)
![OkzqW58glNM](https://user-images.githubusercontent.com/58659520/84080010-2bc21a00-a9e4-11ea-83cc-64fe053fb063.jpg)

**Comment by efroemling** [comment]
Interesting. The internal Python interpreter should be setting sys.paths so that it locates the modules included with the game (which includes 'encodings').

Can you check to make sure that your ballistica dir contains Lib/encodings/__init__.py?

Also, can you try moving the ballistica dir to a simple path with no Cyrillic characters or spaces in it, like C:\Users\admin\Desktop\ballisticacore and see if that makes a difference? I think there might be a bug or two in the game's handling of unicode characters in pathnames and this could be related.

**Comment by KoLenka12** [comment]
I changed the directory name to ballisticacore, but the error remained.

I checked the availability Lib/encodings/init.py in my directory. The file is present.
![image](https://user-images.githubusercontent.com/58659520/84082087-ebfd3180-a9e7-11ea-8c13-ba5f1065e6c2.png)

**Comment by Dliwk** [comment]
Oh, it is my fault. I zipped only top-level files and directories without files they contained...

**Comment by efroemling** [comment]
Ok I've started pushing official BombSquad 1.5.x builds to https://files.ballistica.net/bombsquad/builds/
So if someone simply wants to run the game and not muck around with scripting, that's the easiest way to do so now.  I'll go ahead and close this..
