### ISSUE TITLE
Playing on 1.5 builds server from old builds issues

### ISSUE THREAD

**Issue by SushrutShidhaye** [efroemling/ballistica#47]
Movements not working (wasd) on 1.5 builds hosted server if playing from old version 1.4.150 and below).

**Comment by efroemling** [comment]
Thanks; I've repro'd this and will get 1.5.2 out asap with a fix..

**Comment by Zee-hash** [comment]
@efroemling I update Server builds to 1.52 by download package form https://files.ballistica.net/bombsquad/builds/, and then i can't move on BombSquad_Linux_1.5.1(I can move normally on server 1.51 build).

**Comment by efroemling** [comment]
The 1.5.2 client builds are compiling right now and will be up in a few minutes; they should work correctly with the 1.5.2 servers. (as should the 1.4.x line and the latest ballistica commits).

1.5.0 and 1.5.1 contained a bug which caused them to play nice with each other but not with 'correct' builds. (ie: 1.5.3 or 1.4.x)

**Comment by efroemling** [comment]
Ok, the client 1.5.2 builds are up. Can you confirm that everything is working for you when you are using 1.5.2 and/or 1.4.x servers/clients? I'll go ahead and close this if so.

**Comment by Zee-hash** [comment]
For me, everything is normal since I updated client to 1.5.2 version.

**Comment by efroemling** [comment]
Great; I'll go ahead and close this. Please let me know if you run into any other issues with 1.5.x
