### ISSUE TITLE
Bug, error in plugins on android 1.7.5 with google play

### ISSUE THREAD

**Issue by KrinNoSse** [efroemling/ballistica#470]
After update 1.7.5 mods/plugins stopped working.  I pasted the plugins into the mods folder at Android/data/net.froemling.bombsquad/files/mods.  After that, when I restarted the game, I got an error Error(s) scanning scripts: see log for details.  And of course there are no plugins in the settings.  What could be the reason for this and can you release a fix?
![Screenshot_20220715-105354_BombSquad](https://user-images.githubusercontent.com/109340051/179186887-d0858b98-950e-4c69-8c32-5207f8daf2d0.jpg)
![20220715_105332](https://user-images.githubusercontent.com/109340051/179186897-b3748fbb-8a61-43ec-bbb6-240e6b7a04a8.jpg)

**Comment by aryan02420** [comment]
Try this change in your mods

```diff
- # ba_meta require api 6
+ # ba_meta require api 7
```

this needs to be updated
https://github.com/efroemling/ballistica/wiki/Meta-Tag-System#api-version

to reflect this
https://github.com/efroemling/ballistica/blob/master/CHANGELOG.md
> 1.7.2 (20620, 2022-06-25)
> - Api version increased from 6 to 7 due to the aforementioned plugin changes (on_app_launch becoming on_app_running, etc.)
