### ISSUE TITLE
Bug, error in activate.py files and mods

### ISSUE THREAD

**Issue by KrinNoSse** [efroemling/ballistica#471]
I inserted the plugins folder into the mods folder, but it does not find this folder and plugins at all, it does not even give an error, it's just not in the list of plugins in the game.  

The folder contains the activate.py file, which should activate this folder with plugins (I changed # ba_meta require api 6 to # ba_meta require api 7), if it is in the folder, then nothing happens, but if I transfer activate.py to  "mods" folder, then it will appear in the list of plugins, but nothing will work, because the plugins are not activated, and by the way it gives such a notification when entering the game (attachments).

This seems like nonsense, if it's not clear, I can throw off the archive with these problematic plugins, I hope you can help.
![20220716_125430](https://user-images.githubusercontent.com/109340051/179349966-d4335792-fa5c-4f4a-8e6e-1c0af59da55b.jpg)
[Cinema-Camera-1.2.zip](https://github.com/efroemling/ballistica/files/9125524/Cinema-Camera-1.2.zip)

**Comment by KrinNoSse** [comment]
I forgot to mention, this is on version 1.7.5 android google play

**Comment by IvanPragma** [comment]
Hmm, are you using [Cinema Camera](https://github.com/IvanPragma/Cinema-Camera) 😄? A couple of days ago I moved it to 1.7, try to update plugin from repo.
