### ISSUE TITLE
Bug: Cannot pop up the browser window

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#472]
The "bacloud" command cannot pop up the browser window.
It showed a "Authenticating via web-browser..." message and then doing nothing.

**Comment by aryan02420** [comment]
What OS are you using? Do you have a default browser set? Can you try this command

```bash
python -m webbrowser -t "https://www.python.org"
```

**Comment by aryan02420** [comment]
It might be useful to print the login url to the console in case the environment does not support opening urls.

**Comment by efroemling** [comment]
Yeah the bacloud script simply calls Python's webbrowser.open() with the login url so we should figure out why that isn't working. It would also be possible to have the script print the url that it is opening just in case the open doesn't work.

**Comment by efroemling** [comment]
Ok; just added this in the latest commit: 5c77e7c24f50550082a64b7e73fea2ad6dae9ef9

**Comment by xujianing12** [comment]
I uses windows11 x64

**Comment by xujianing12** [comment]
> What OS are you using? Do you have a default browser set? Can you try this command
> 
> ```shell
> python -m webbrowser -t "https://www.python.org"
> ```

I try this, it open www.python.org, but still can't open the login page.

**Comment by xujianing12** [comment]
> Ok; just added this in the latest commit: [5c77e7c](https://github.com/efroemling/ballistica/commit/5c77e7c24f50550082a64b7e73fea2ad6dae9ef9)

ERROR: dummy _ba module is out of date.
Error checking/updating dummy module.

assets/src/ba_data/python/ba/_net.py:117: error: Module "efro.error" has no attribute
"is_urllib_network_error"
            from efro.error import is_urllib_network_error
            ^
assets/src/ba_data/python/bastd/ui/gather/publictab.py:222: error: Module "efro.error" has no attribute
"is_udp_network_error"
                from efro.error import is_udp_network_error
                ^
assets/src/ba_data/python/bastd/ui/gather/publictab.py:274: error: Module "efro.error" has no attribute
"is_udp_network_error"
                from efro.error import is_udp_network_error
                ^
assets/src/ba_data/python/bastd/ui/gather/manualtab.py:708: error: Module "efro.error" has no attribute
"is_udp_network_error"
                from efro.error import is_udp_network_error
                ^
Mypy failed.

**Comment by xujianing12** [comment]
> Yeah the bacloud script simply calls Python's webbrowser.open() with the login url so we should figure out why that isn't working. It would also be possible to have the script print the url that it is opening just in case the open doesn't work.

Thacks!!

**Comment by JoseANG3L** [comment]
@xujianing12 Try having the game in windowed mode when using bacloud.

**Comment by efroemling** [comment]
@xujianing12 Curious why you reopened this?.. I think if the engine is showing the url and also calling web browser.open() then that's about all we can ask of it. Are either of those not happening?

**Comment by xujianing12** [comment]
@efroemling
