### ISSUE TITLE
Bug: Visual Studio build

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#473]
When I Input "make windows-debug", it showed:
\\wsl.localhost\ubuntu-22.04\home\xuliyong\ballistica\build\windows\obj\ballistic
acoregeneric\debug_win32\ballisticacoregeneric.pch”: No such file or directory [\\wsl.localhost\Ubuntu-22.0
4\home\xuliyong\ballistica\ballisticacore-windows\Generic\BallisticaCoreGeneric.vcxproj]

When I input "make windows-debug", it showed:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppComm
on.targets(550,5): error MSB6006

But I had done all work. 
Who can tells me why?????

**Comment by brostosjoined** [comment]
- Try moving or clone the repository on a windows accesssible path `/mnt/c/....` 
- Use wsl terminal dont use the ubuntu
