### ISSUE TITLE
Bug: Port Fail

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#475]
I open the port 43210.
But the server still showed checked fail.
I uses windows11 x64.
I have a free cloud server too.
So who can tells me why???

**Comment by efroemling** [comment]
When you run the availability check, the master-server simply tries to send a udp 'ping' packet to the address that it sees you are connected from. If this makes it through to your device and it gets a response, it will tell you that your game is available from the internet. Usually forwarding ports on your router will allow things through but perhaps you have a unique setup that is preventing this. But in general that's a network setup issue, not a game issue, and not something we can really help with, so I'll go ahead and close this.

In general though I'm working on moving more of the game to things like cloud servers where you don't have to mess with ports and whatnot...
