### ISSUE TITLE
Unusual popup every launch

### ISSUE THREAD

**Issue by Freaku17** [efroemling/ballistica#477]
Hi,
Every launch I get this popup
![bs](https://user-images.githubusercontent.com/92618708/180431027-7b26890e-86f6-425a-9620-66365b0b48c8.png)

I use mods (via the Android/data/),
I've seen `_ba.getlog()` but there's nothing in those logs.

**Comment by vishal332008** [comment]
Test build or play store app?

**Comment by aryan02420** [comment]
try #470

**Comment by Freaku17** [comment]
I've made all changes for 1.7 api

It's a bug either ways, shouldn't it "log" any errors 🤨

**Comment by aryan02420** [comment]
It does log errors in the console. Not sure how to view it on android, but if you have a keyboard, connect it to your device and press <kbd>`</kbd> (backtick) key

**Comment by Freaku17** [comment]
That's what I said, I fetched logs via `_ba.getlog()` and it's empty 😄

**Comment by Freaku17** [comment]
Hi there, I researched a bit and found something.

So ba/_meta.py is normally like this (bs v1.7.6):
![Screenshot_1](https://user-images.githubusercontent.com/92618708/181915952-65f5632a-2d68-49fd-9fdb-4021f9dd9ad3.png)

Since every launch its giving this "Error Scanning scripts" and not giving any logs.
I edited and added a `print` statement in line 125
![Screenshot_2](https://user-images.githubusercontent.com/92618708/181916063-abf6e58b-7874-44b2-a140-3e7e09f3538d.png)

Which printed this:
![Screenshot_3](https://user-images.githubusercontent.com/92618708/181916142-87440372-f5e5-49bf-bbe4-7c7b0066bacf.png)


Inshort... Yes it *was*  my plugin error, but it wasn't logging it 🙂

**Comment by Dliwk** [comment]
Seems like `_ba.getlog()` works only with 'to-server' logs (this is optional parameter for `_ba.log`). This parameter is true by default (standard python `print` calls wired up to this as well, so they behave like _ba.log with default arguments), but it is set to false for meta-scan warnings:
https://github.com/efroemling/ballistica/blob/2ddb0d6eb419aa779d4a27690e23c09a83746732/assets/src/ba_data/python/ba/_meta.py#L194-L197
