### ISSUE TITLE
 Error in BombSquad 1.5 Windows

### ISSUE THREAD

**Issue by MarkSaibel** [efroemling/ballistica#49]
When I try to start the BombSquad application, the command line appears and disappears and writes an error:
BombSquad 1.5.2 build 20065.
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002444 (most recent call first):

__init__ was in encondings and encodings was in lib but for some reason it gives me this error
![Снимок534657](https://user-images.githubusercontent.com/65766777/84261287-41138180-ab67-11ea-83ca-2da722c6ed79.PNG)

**Comment by efroemling** [comment]
I think this was related to having a non-ascii characters in the file path (ПК)
I just took a pass at the windows version and updated all file access so it should work with any unicode file paths now. Can you try the 1.5.3 build and let me know if it works for you now?
https://files.ballistica.net/bombsquad/builds/

**Comment by MarkSaibel** [comment]
It still doesn’t work, such an error:
![Снимокегвоап](https://user-images.githubusercontent.com/65766777/84461324-e6d60600-acb7-11ea-9430-03265066523a.PNG)

**Comment by efroemling** [comment]
Whoops; it seems I missed a spot 😬.
Can you try 1.5.4? I'm pretty sure it should work now...
https://files.ballistica.net/bombsquad/builds/

**Comment by MarkSaibel** [comment]
Now everything works, thanks for the help
