### ISSUE TITLE
Error BombSquad - Windows 

### ISSUE THREAD

**Issue by JoseANG3L** [efroemling/ballistica#5]
By following all the steps, this is the error:

`Downloading: build/prefab/windows/debug/BallisticaCore.exe
Extracting: build/prefab/windows/debug/BallisticaCore.exe
build/prefab/windows/debug/BallisticaCore.exe
BallisticaCore 1.5.0 build 20001.
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000007bc (most recent call first):
Makefile:177: recipe for target 'prefab-windows-debug' failed
make[1]: *** [prefab-windows-debug] Error 9
make[1]: Leaving directory '/home/angel/ballistica'
Traceback (most recent call last):
  File "tools/snippets", line 880, in <module>
    snippets_main(globals())
  File "/home/angel/ballistica/tools/efrotools/snippets.py", line 82, in snippets_main
    funcs[sys.argv[1]]()
  File "tools/snippets", line 851, in make_prefab
    run(f'make {target}')
  File "/home/angel/ballistica/tools/efrotools/__init__.py", line 146, in run
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'make prefab-windows-debug' returned non-zero exit status 2.
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "tools/snippets", line 880, in <module>
    snippets_main(globals())
  File "/home/angel/ballistica/tools/efrotools/snippets.py", line 82, in snippets_main
    funcs[sys.argv[1]]()
  File "tools/snippets", line 851, in make_prefab
    run(f'make {target}')
  File "/home/angel/ballistica/tools/efrotools/__init__.py", line 146, in run
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'make prefab-windows-debug' returned non-zero exit status 2.
Makefile:118: recipe for target 'prefab-debug' failed
make: *** [prefab-debug] Error 1`

**Comment by Awesome-Logic** [comment]
Try `sudo apt-get install --reinstall python3-apt`

**Comment by efroemling** [comment]
Hmmm; odd. I'm not able to reproduce this on my end. The game is complaining that is can't find the 'encodings' module. Do you have the following file in your ballistica dir?: 'build/prefab/windows/debug/Lib/encodings/__init__.py'

**Comment by Awesome-Logic** [comment]
Just install `Python 3.8 Windows` on your system.
This fixed the error for me.

**Comment by Dliwk** [comment]
**Python 3.8**? How it may help if Ballistica uses **Python 3.7**? I built version 3.7.7 special for it (in official distro repository only latest version).

**Comment by Awesome-Logic** [comment]
Python3 matters in the end. Both 3.7 and 3.8 share the same core. I decided to go with the latest and it worked out.

**Comment by SushrutShidhaye** [comment]
sush@DESKTOP-Q9PCBL3:~/ballistica$ make prefab-debug
make[1]: Entering directory '/home/sush/ballistica'
make[2]: Entering directory '/home/sush/ballistica/assets'
make[3]: Entering directory '/home/sush/ballistica/assets'
make[3]: Nothing to be done for 'assets-win-x64'.
make[3]: Leaving directory '/home/sush/ballistica/assets'
make[2]: Leaving directory '/home/sush/ballistica/assets'
build/prefab/windows/debug/BallisticaCore.exe
BallisticaCore 1.5.0 build 20001.
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002008 (most recent call first):




after that
BallisticaCore.exe has stopped working..... after close 

again 
sush@DESKTOP-Q9PCBL3:~/ballistica$ make prefab-debug
make[1]: Entering directory '/home/sush/ballistica'
make[2]: Entering directory '/home/sush/ballistica/assets'
make[3]: Entering directory '/home/sush/ballistica/assets'
make[3]: Nothing to be done for 'assets-win-x64'.
make[3]: Leaving directory '/home/sush/ballistica/assets'
make[2]: Leaving directory '/home/sush/ballistica/assets'
build/prefab/windows/debug/BallisticaCore.exe
BallisticaCore 1.5.0 build 20001.
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00002008 (most recent call first):
Makefile:177: recipe for target 'prefab-windows-debug' failed
make[1]: *** [prefab-windows-debug] Error 255
make[1]: Leaving directory '/home/sush/ballistica'
Traceback (most recent call last):
  File "tools/snippets", line 880, in <module>
    snippets_main(globals())
  File "/home/sush/ballistica/tools/efrotools/snippets.py", line 82, in snippets_main
    funcs[sys.argv[1]]()
  File "tools/snippets", line 851, in make_prefab
    run(f'make {target}')
  File "/home/sush/ballistica/tools/efrotools/__init__.py", line 146, in run
    subprocess.run(cmd, shell=True, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'make prefab-windows-debug' returned non-zero exit status 2.
Makefile:118: recipe for target 'prefab-debug' failed
make: *** [prefab-debug] Error 1
 any help?

**Comment by efroemling** [comment]
I'm curious to get to the bottom of what's going on here. Installing system python shouldn't be necessary to run the game since a full python install is included with it.

For any of you who ran into this problem but fixed it by installing python, could I have you test a few things for me:
- in the terminal after launching the game, can you run `import encodings; print(encodings.__file__)`? I'm curious to see if the encodings module it is picking up is the one packaged with the game or not.
- could you run `import sys; print(sys.path)`? I'd like to see if the directory containing the game's bundled python modules is properly listed there..

**Comment by Awesome-Logic** [comment]
import encodings; print(encodings.__file__) returns `C:\Users\Home\AppData\Local\Programs\Python\Python37\Lib\encodings\__init__.py`

sys.path returns this list:
```
\\wsl$\Ubuntu-18.04\root\ballistica\build\prefab\windows\release\python37.zip
C:\Users\Home\AppData\Local\Programs\Python\Python37\Lib
C:\Users\Home\AppData\Local\Programs\Python\Python37\DLLs
\\wsl$\Ubuntu-18.04\root\ballistica\build\prefab\windows\release
C:\Users\Home\AppData\Local\Programs\Python\Python37
C:\Users\Home\AppData\Local\Programs\Python\Python37\lib\site-packages
\\wsl$\Ubuntu-18.04\root\ballistica\build\prefab\windows\release\ba_data/python
C:\Users\Home\AppData\Roaming\BallisticaCore\mods
```

Interestingly the Lib folder from the game is missing.

**Comment by efroemling** [comment]
Ok I think I know what's going on here. It seems Python is not calculating correct script paths when it gets run from under a funky path like \\wsl$\Ubuntu-18.04\... The #2 and #3 paths (Lib and DLLs) are supposed to be the ones included with the game, but it's not setting them correctly, which is why it is not finding things unless a system install of python is present.

This should be an easy fix; I'll try to get it in tomorrow...

**Comment by efroemling** [comment]
Ok, I reworked the code the sets up python paths in commit 98058bc449f2582dba321f4402c27483216d0bdd

Could you folks do a pull and try this again and let me know if it seems to be working?
- if you do `import encodings; print(encodings.__file__)` you should now always see a path in your ballistica build
- if you do `import sys; print(sys.path)` you should now see 4 paths; your mods dir, the DLLs/Libs dirs in the ballistica build, and the ba_data/scripts in your ballistica build.

And things should now always run correctly even if there is no system python installed.

**Comment by Awesome-Logic** [comment]
Looks like it worked! I don't see anything from system python in sys.path.

I also tried uninstalling python and everything runs fine.

I guess this issue can be closed now.
