### ISSUE TITLE
NewBot(1.7.7)

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#500]
I want to create a new bot in Bombsquad 1.7.7.
I copied some code of 'BomberBot',and edit a new one called 'NewBot'.
But when I import 'bastd.actor.spazbot.NewBot',it showed 'Can not import 'NewBot' from ''bastd.actor.spazbot''.
I used windows 11.
Any One?

**Comment by efroemling** [comment]
Hmm I think this might not be the right place for this. I think we should keep the Issues section limited to things that need fixing/improving with the game/engine itself. Can you recreate this in the discussions section or ask for help on the discord server?
