### ISSUE TITLE
Open 'bob' files(1.7.7)

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#501]
How can I open the '.bob' files?
I used windows 11 and BombSquad 1.7.7.

**Comment by JoseANG3L** [comment]
Some time ago I made this tutorial, it works for new versions: https://www.youtube.com/watch?v=C27dCeeN0oU&ab_channel=byANG3L

**Comment by xujianing12** [comment]
@JoseANG3L I am in China, Can't see YouTube : (

**Comment by JoseANG3L** [comment]
@xujianing12 Install Blender 2.77: https://download.blender.org/release/Blender2.77/
Then install add-on bob_plugin: https://icedrive.net/s/Q8CA4P6CiAAbh14yfhgtN2hby77F

**Comment by xujianing12** [comment]
I can't see https://icedrive.net/s/Q8CA4P6CiAAbh14yfhgtN2hby77F too : (

**Comment by Dmitry450** [comment]
@xujianing12 try https://github.com/bseditor/BombSquad-Community-Mod-Manager/blob/master/utils/blender/bob_plugin.py

This is probably the same file as in icedrive

**Comment by JoseANG3L** [comment]
New download link: https://www.mediafire.com/file/llz8j1tjwt3oacn/bob_plugin.py/file
