### ISSUE TITLE
Server not joinable from public tab

### ISSUE THREAD

**Issue by iphonor** [efroemling/ballistica#510]
On my new Ubuntu VDS, I run BS v1.7.7 server. It runs succesfully, appears in list but players cannot join it. I can join by ip and there are no errors in terminal but if I try to join in public tab I just stay in queue and get message "connection failed" . I tried v1.6.4, with mods and without mods but it all doesn't work. Can you help me?

**Comment by SenjuZoro** [comment]
Try disabling ipv6, and only use ipv4 (as enabled)

**Comment by iphonor** [comment]
> Try disabling ipv6, and only use ipv4 (as enabled)

Ok it worked, thank you very much
