### ISSUE TITLE
Disable Camera Shake (Bug).

### ISSUE THREAD

**Issue by Ralfreengz** [efroemling/ballistica#511]
### Description
After playing for a while, I noticed that something was bothering me, I paused the game and discovered that something was wrong with the camera.

### Expected behavior
I guess this must be a "Disable Camera Shake" bug.

### Machine
**Platform**: Windows 10 and Android
**BombSquad version**: [1.7.7]

### Screenshots
![Screenshot_20220920-190039](https://user-images.githubusercontent.com/71152012/191387331-70a5f9b5-02d8-4269-b428-49f6def140cc.png)

**Comment by Dliwk** [comment]
Should be fixed by linked PR #512.
