### ISSUE TITLE
Feature Request: Allow starring this project more than once.

### ISSUE THREAD

**Issue by lucasea777** [efroemling/ballistica#526]
## Description
Currently I am able to star this project only "once".

## Solution
It Would require contacting github.com developers.

## Alternatives
Add a "Sponsor" button?.

## Additional context

![onestar](https://user-images.githubusercontent.com/8538002/194943407-b3d402bd-165c-4611-9607-cece1e97cf8a.png)

**Comment by Loup-Garou911XD** [comment]
Uhh what

**Comment by Dliwk** [comment]
Yeah that's fun, sorry that we can't implement it :cry:
