### ISSUE TITLE
lost my identity

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#53]
After the change from Windows Version BombSquad_Windows_1.5.3 to BombSquad_Windows_1.5.4 i lost my identity. So i made a new character. Username chelikol is no problem. But i lost my loved Grumbledore.

**Comment by efroemling** [comment]
So I forgot to add this to the CHANGELOG (I will for the next update), but the windows 1.5.4 version now stores its data in 'local' app data, so something like C:\Users\YourName\AppData\Local\BombSquad

Previously it was in 'roaming', which would be something like C:\Users\YourName\AppData\Roaming\BombSquad

If you copy/move the BombSquad directory from Roaming into Local you should have access to your old stuff...

**Comment by chelikol** [comment]
The copy worked perfectly. Grumbledore (and other things) is back. I felt a little naked as Kronk. Thanks for the quick answer.

**Comment by Benefit-Zebra** [comment]
@efroemling I am on Android and I too lost my identity.
