### ISSUE TITLE
python for bombsquad

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#533]
### Description
I installed bombsquad on a fresh ubuntu. I got the error message
**./bombsquad: error while loading shared libraries: libpython3.10.so.1.0: cannot open shared object file: No such file or directory**

`python3 -V` showed 3.8. So I installed 3.10, but the path was wrong.
After `ln -s /usr/bin/python3.10 python3`, the path error was fixed, but the error with the library remained. 
Now I installed the developer version `apt-get install python3.10-dev` and with that bombsquad starts.
### By the way
The windows version with wine works too: `wine BombSquad.exe`

**Comment by IvanPragma** [comment]
I don't think it's a bug 🤔

**Comment by Dliwk** [comment]
>I don't think it's a bug :thinking:
Yeah.. unless I got something wrong. Ballistica requires shared python library (currently 3.10), you this is why you had to install `python3.10-dev`.

**Comment by chelikol** [comment]
After changing from HD to SSD i reinstalled ubuntu. So I had the problem once more. Now I succeded with 

- First 
Install 3.10 
```
sudo apt update && sudo apt upgrade -y
sudo apt install software-properties-common -y
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.10
```

- Second
`sudo apt-get -y install python3.10-dev`

See: https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/?utm_content=cmp-true
See: [[https://installati.one/install-python3.10-dev-ubuntu-22-04/]](https://installati.one/install-python3.10-dev-ubuntu-22-04/)

**Comment by chelikol** [comment]
After `sudo apt-get -y install python3.10-dev`  for `BombSquad_Linux_x86_64_1.7.20`
i get some warnings:
```
Warning (meta-scan): hot_potato.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): practice_tools.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): chat_cmd.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): quickturn.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): floater.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): plugin_manager.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): boxing.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): disco_light.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): mood_light.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): pro_unlocker.py requires api 7 but we are running 8. Ignoring module.
Warning (meta-scan): tnt_respawn_text.py requires api 7 but we are running 8. Ignoring module.
```
