### ISSUE TITLE
Missing DLL errors on windows debug build through WSL

### ISSUE THREAD

**Issue by rahulraman0108** [efroemling/ballistica#54]
I get three missing DLL errors every time when I try to run the windows debug builds from WSL (including server builds) However, there are no errors when I try to run the 1.5.x builds downloaded from the files.balistica.net or run release builds from WSL on my laptop

I also have the Microsoft Visual Studio Redistributable latest installed

![image: my debug builds not work](https://user-images.githubusercontent.com/42905362/84565333-020f4700-ad86-11ea-9ca0-d6612df84f32.png)

![image: downloaded builds work](https://user-images.githubusercontent.com/42905362/84565312-d8eeb680-ad85-11ea-9e48-c83e38df5002.png)

![image: release builds from wsl also work](https://user-images.githubusercontent.com/42905362/84565750-ee191480-ad88-11ea-9af5-299a161776ee.png)

**Comment by efroemling** [comment]
Interesting.. Yeah I guess the debug builds of the game are looking for the debug version of the redistributable (so MSVCP140D.dll instead of MSVCP140.dll)

I found [this page](https://docs.microsoft.com/en-us/cpp/windows/preparing-a-test-machine-to-run-a-debug-executable?view=vs-2019) which talks about the issue.

It sounds like there's no redistributable installer for those debug .dlls, so perhaps I'll need to have them included alongside the application (the same as the SDL, Ogg/vorbis, and Python DLLs)..

**Comment by efroemling** [comment]
You mentioned there are 3 missing DLL errors; could you give me the exact names of them? I see MSVCP140D.dll in your screenshot but I'm curious about the other two. I'll set them up to be automatically included with ballistica debug builds...

**Comment by rahulraman0108** [comment]
There comes three missing DLL errors one after another. I have put them in a list below:
1. MSVCP140D.dll
2. VCRUNTIME140D.dll
3. VCRUNTIME140_1D.dll

**Comment by efroemling** [comment]
Ok I've added these 3 libraries to the debug ballisticacore builds. Can you pull the latest and do a build and see if things work for you?

**Comment by rahulraman0108** [comment]
I will get to check it later, and I can't say anything about it right now due to my network.
At the current time it is bad weather here with low signal and I have pulled the latest commits already but the `make prefab-debug` is stuck on `Downloading: assets/build/windows/x64/vc_redist.x64.exe` (tried restarting it 3 times).
I do not think that the download will finish at the time and is stuck for more than 30 minutes.

**Comment by rahulraman0108** [comment]
Okay, I tried it again right now and it finished successfully and the debug build is also correctly working now.
