### ISSUE TITLE
Map Modification "api" bug

### ISSUE THREAD

**Issue by lukinhagf** [efroemling/ballistica#541]
I am trying to make a map on bombsquad only using scrypt i modified BIG G and i am using TNT AS PLATFORM for this i need to remove gravity but when character collide on tnt , the tnt moves i used flag code do desactivate rigidbody but the tnt loses collision see the modifications that i made
![Screenshot_20221028-163425_QuickEdit](https://user-images.githubusercontent.com/116916926/198720334-8c070e8b-0808-41b9-a8ec-9e93c0c2fbeb.jpg)
![Screenshot_20221028-163452_QuickEdit](https://user-images.githubusercontent.com/116916926/198720338-51fa4375-a939-4b0c-8dab-45dc63a398c2.jpg)
![Screenshot_20221028-163524_QuickEdit](https://user-images.githubusercontent.com/116916926/198720340-611862f9-d79b-4475-baaa-17e91dba37b9.jpg)
![Screenshot_20221028-163534_QuickEdit](https://user-images.githubusercontent.com/116916926/198720343-0132f600-1ac9-4b9d-a3c2-cbed53383b68.jpg)

When the tnt losed collision o tried this
  touchable: bool = True
NOT WORKED

**Comment by imayushsaini** [comment]
I think touchable field will only disable collide with spaz pickup material .
Anyways spaz has more materials u need to disable collide with those materials also or better disable all collides with your TNT prop node . Yes then spaz cant even stand on TNT prop, for that your need u need to create another node of region and make it collide with every material.

**Comment by imayushsaini** [comment]
And yeah its not a bug , issue can be closed.
