### ISSUE TITLE
How do you win a tournament?

### ISSUE THREAD

**Issue by ixPost** [efroemling/ballistica#542]
How do I win a tournament? Every time I play a tournament I don't get any thing.

**Comment by brostosjoined** [comment]
Be the best

**Comment by Dliwk** [comment]
You get (or not) a prize when the tournament ends, based on final scoreboard. Note that to compete in tournaments you must have absolutely unmodified game, with no workspaces enabled and empty mods folder.

**Comment by ixPost** [comment]
Thanks for telling me.
