### ISSUE TITLE
No geting ride of votes

### ISSUE THREAD

**Issue by ixPost** [efroemling/ballistica#543]
## Description
Pin vote-messages.

## Alternatives
People won't be able to chat when the vote-message.

**Comment by imayushsaini** [comment]
🤔 good way to freeze chat if we are losing argument with someone, just start random kick vote.

**Comment by Dliwk** [comment]
> :thinking: good way to freeze chat if we are losing argument with someone, just start random kick vote.

Yes, it sounds quite weird. But it's possible to implement it using C++ layer right now, or waiting for https://github.com/efroemling/ballistica/issues/41. If you think that it's actually useful feature, feel free to reopen and explain more.

**Comment by ixPost** [comment]
Yes, but you can make only one vote at a time.
