### ISSUE TITLE
AttributeError: '_AccountClientV2' object has no attribute '_state'.

### ISSUE THREAD

**Issue by Xicoric** [efroemling/ballistica#547]
![image](https://user-images.githubusercontent.com/118528934/202687126-0de0d5eb-4a72-460b-9610-c82d11443008.png)

ive been having this error in bombsquad, it doesnt give me a pc id and my id remains as device. I cant link with other accounts or make new profiles, the error goes away in version 1.5 but i am not able to move in online games

**Comment by Dliwk** [comment]
Try removing you configs at `C:\Users\deepa\AppData\Local\BombSquad\config.json` and `C:\Users\deepa\AppData\Local\BombSquad\config.json.prev`. You'll only have to re-login (just reproduced this issue on my machine by corrupting these config files).

**Comment by Dliwk** [comment]
But actually, some settings will be lost forever if you remove these files, so better save config.json, config.json.prev and config.json.broken somewhere and see if they contain almost correct json.

**Comment by efroemling** [comment]
<img width="967" alt="Screenshot 2022-11-18 at 11 03 24 AM" src="https://user-images.githubusercontent.com/10857610/202782897-98c9a8f0-46d0-4c99-bb49-23b810fd029b.png">

On a side note there is a config-error window that is supposed to come up on desktop builds when the config can't be read, but I can see from the log there that is is broken. I just took a pass and got it fixed so this is what you should see in the next build in your case.

**Comment by Xicoric** [comment]
> Try removing you configs at `C:\Users\deepa\AppData\Local\BombSquad\config.json` and `C:\Users\deepa\AppData\Local\BombSquad\config.json.prev`. You'll only have to re-login (just reproduced this issue on my machine by corrupting these config files).

its not able to find the location
![image](https://user-images.githubusercontent.com/118528934/202843223-410fb5e8-4d07-49c4-abeb-76b69bd6c128.png)
![image](https://user-images.githubusercontent.com/118528934/202843237-534541f2-2028-47ee-b7ab-60034c51da47.png)

**Comment by Xicoric** [comment]
it worked, thank you very much
