### ISSUE TITLE
Controller key mapping under Windows

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#55]
For quite some time (before 1.5) i had to redefine the key bindings of the controller after each start. 
![CrontollerMapping1](https://user-images.githubusercontent.com/66850897/84575912-33513c80-adb1-11ea-8366-ec889cff1cb6.PNG)

Since 1.5 I also have to define the race buttons.
![CrontollerMapping2](https://user-images.githubusercontent.com/66850897/84575933-4401b280-adb1-11ea-9ee0-ee57ee757a78.PNG)
Have I possibly got a "legacy problem" in my directory?: C:\Users\myName\AppData\Roaming\BombSquad

**Comment by efroemling** [comment]
Yes it is possible that you've got a corrupt config file or something that is preventing these settings from saving properly. Could you temporarily relocate the existing config and see if the problem still occurs?

On a related note, the latest builds store their data in C:\Users\myName\AppData\Local\BombSquad (no longer roaming)

Lastly, if you do still see the problem, you might be able to debug it by looking at the contents of config.json or the code in ba_data\python\bastd\ui\settings\gamepad*.py

Or if you can confirm that it is happening on a fresh install I can take a look...

**Comment by chelikol** [comment]
After nenaming  `C:\Users\myName\AppData\Local\BombSquad\config.json` the problem seems to be disappeared. I will test it  tomorrow again. 

The new file looks "normal":
```{
 "Achievements": {
  "Boom Goes the Dynamite": {
   "Complete": true
  },
  "Boxer": {
   "Complete": true
  },
  "Dual Wielding": {
   "Complete": true
  },
  "Flawless Victory": {
   "Complete": false
  },
```
The old one with looks "binary" in vi and has a content of only one line with 63.000 : "`^@`"

Thank you very much for the fast response!

**Comment by efroemling** [comment]
Good to hear! I'll go ahead and close this.
It's slightly worrying that your config file somehow got into such a corrupted state previously; please let me know if that happens again...
