### ISSUE TITLE
Tournament Scores not Registering

### ISSUE THREAD

**Issue by RobbieElias** [efroemling/ballistica#551]
### Description
As the title describes, any tournament score I achieve isn't being registered. So if I enter a tournament and get first place, I won't win the tournament and my score won't be posted on the leaderboard. I've tested on both Android and Windows (with a linked account). My account is Sporticus8.

### Steps to reproduce
1. Launch BombSquad
2. Enter any tournament
3. Get a decent score
4. Look at the tournament's leaderboard
5. Bug!

### Expected behavior
Tournament scores should be entered.

### Machine
**Platform**: Windows 10
**BombSquad version**: 1.7.14

### Extra
I noticed that ever since I logged a 30,000 score in Infinite Onslaught, my scores have no longer been accepted. Is it possible that I was banned?

**Comment by efroemling** [comment]
It sounds like you might have been shadow-banned for an unexpectedly high score. Sorry about that if that’s the case. I’m working to eventually move tournaments to my own servers so I can better protect against cheating but in the meantime there’s some score checks in place which can lead to false-positive bans happening.

Can you go to settings->advanced->enter code and enter “sendinfo robbie”? That will point me at your account so I can have a look.

**Comment by RobbieElias** [comment]
Done, thanks!

**Comment by efroemling** [comment]
> Done, thanks!

Ok you should be good to go now 👍🏻

**Comment by RobbieElias** [comment]
Awesome, thanks for the quick reply. Would you like me to close this issue?
