### ISSUE TITLE
Server on Termux

### ISSUE THREAD

**Issue by Brostos** [efroemling/ballistica#56]
can it run on termux the problem i found was the bs_headless saying exec formart error

**Comment by Dliwk** [comment]
Currently BombSquad has no headless builds for Android. You can't run x86 binaries on ARM device, but theoretically you can try headless build for Raspberry Pi (it not works for me).

**Comment by efroemling** [comment]
I would be happy to add a server build for termux arm64 or whatnot; I just need to know how and to set up a build script. I don't know if/when I'll have time for this in the near future, but if somebody wants to take a stab at this using a simple dummy project then I'd be happy to wire it up to my builds.

**Comment by Dliwk** [comment]
Update: Arm64 builds are now available; it's possible to run a headless version on Termux (an example of how people do it: https://www.youtube.com/watch?v=Gs8czdMXIxY).
