### ISSUE TITLE
Please Create a new server on south america

### ISSUE THREAD

**Issue by lukinhagf** [efroemling/ballistica#561]
All servers os south america keeps full for hours , but why i dont play on other servers because the super lag that is impossible to play
Server hosted on phone come with lag
Others south america server like UDIUDIV3 OR UDIUDIV4 HAVE LAG
IN USA HAVE MORE SERVERS LIKE
FFA USA 1 
FFA USA 2
FFA USA 1A
FFA USA 2B
PLEASE MAKE NEW SERVERS ON SOUTH AMERICA
WHEN I CAME TO PLAY BOMBSQUAD I QUIT FASTER BECAUSE ALL OFFICIAL SERVERS ON SOUTH AMERICA ARE FULL
![Screenshot_20230120-121757_BombSquad](https://user-images.githubusercontent.com/116916926/213735344-bf23fb28-ef78-46ce-8cdd-93e69a2c515a.jpg)

**Comment by efroemling** [comment]
Thanks for the suggestion. South America has become one of the most popular places for the game so I should have done this before. Anyway I just upped the number of servers in São Paulo from 2 FFA and 2 Teams to 4 FFA and 4 Teams and added 2 of each in Miami and Houston as well, which are in decent range to Central/South America. Before long I will have a few more cities available down there to host from so hopefully latency will be improving then too.
Please let me know if it is still hard to find a server after this, and thanks again for the heads-up.

**Comment by lukinhagf** [comment]
Thanks for new servers
Now is easy to find servers

**Comment by efroemling** [comment]
Great to hear! Please let me know if it ever becomes difficult again.
