### ISSUE TITLE
make_prefab failed with error: Command '['make', 'prefab-mac-arm64-gui-release-build']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by xujianing12** [efroemling/ballistica#573]
<img width="569" alt="截屏2023-02-10 18 27 39" src="https://user-images.githubusercontent.com/109203353/218074806-509c003f-71b7-4e4b-89a0-78ea0a6f30fc.png">
machine:mac ventura 13.2

**Comment by EraOSBeta** [comment]
I think your environment isn't set up properly, read [this](https://github.com/efroemling/ballistica/wiki/Getting-Started#preparing-your-environment) (specifically [this](https://github.com/efroemling/ballistica/wiki/Getting-Started#optional-set-up-a-python-virtual-environment) and [this](https://github.com/efroemling/ballistica/wiki/Getting-Started#wrapping-up))

**Comment by xujianing12** [comment]
my environment is set up properly.

**Comment by xujianing12** [comment]
still not work : (
