### ISSUE TITLE
Server Start failed on port 43210

### ISSUE THREAD

**Issue by chelikol** [efroemling/ballistica#577]
### Start server
Master server access check of 2001:9e8:b081:b900:fda1:e7f0:4002:bc4d udp port 43210 failed

### Steps to reproduce
1. Download and unzio BombSquad_Server_Linux_x86_64_1.7.19.tar.gz
2. Open udp port 43210 in my router for my pc 
3. start  server with: ./bombsquad_server

### Machine
Ubuntu

### Extra
I tried to find the host with nslookup. But I got only the message:
** server can't find e.9.7.a.e.e.3.2.5.7.f.7.3.5.a.a.0.0.9.b.1.8.0.b.8.e.9.0.1.0.0.2.ip6.arpa: NXDOMAIN

**Comment by chelikol** [comment]
I did not try to start the game because the start of the server failed.

**Comment by chelikol** [comment]
Perhaps it's an incompatibility between the tcp-ip handling of bombsquad in the restriction of the german providers. I think they have not the full ipv6 functionality.

**Comment by Dliwk** [comment]
IPv6 always comes with some problems (like [these][1] and [these][2]), plus even if you manage to launch server, almost no people would be able to connect. :/ If you have a public IPv4 address, everything should be fine. Feel free to reopen if there is something different.


[1]: https://github.com/efroemling/ballistica/issues/316
[2]: https://github.com/efroemling/ballistica/issues/510
