### ISSUE TITLE
Lost all my characters and tickets

### ISSUE THREAD

**Issue by aaaz607** [efroemling/ballistica#578]
I lost all my characters and tickets. I deleted the game for a while and downloaded it again. The V2 icon appeared and now I have nothing. There were definitely tickets, and I have completed all the achievements of Bomb squad. I also had characters, but they disappeared. There were also several accounts linked, now they are also gone. I had all the events from the single-player game completed, and they also reset.
![Screenshot_2023-03-19-12-45-41-583_net froemling bombsquad](https://user-images.githubusercontent.com/68124486/226163980-c4f49434-df96-4921-8369-f425b33e9851.jpg)
![Screenshot_2023-03-19-12-45-33-707_net froemling bombsquad](https://user-images.githubusercontent.com/68124486/226163982-e0c59a8c-0a89-4935-888b-0c2e888c2748.jpg)

**Comment by aaaz607** [comment]
![Uploading Screenshot_2023-03-19-12-48-13-424_net.froemling.bombsquad.jpg…]()

**Comment by Dliwk** [comment]
Email support@froemling.net, this might be some issue transferring your account data. (Or your old account might be of legacy type, which are always lost when you uninstall game, etc.)
