### ISSUE TITLE
strange pylint empty messages

### ISSUE THREAD

**Issue by rahulraman0108** [efroemling/ballistica#58]
Pylint is giving strange empty messages on the console when doing make check, no error no detail provided in the message.
Image below.

![image](https://user-images.githubusercontent.com/42905362/84763078-4c443280-afe9-11ea-9315-1562bd39194f.png)

**Comment by efroemling** [comment]
hmmmm; smash.py isn't a standard ballistica thing; Can you give the authors a holler? If there's anything I can tighten up on the ba side, I will....

**Comment by rahulraman0108** [comment]
Actually I am the creator of the file and I am making the Super Smash minigame updated to the latest API so that I can use it on my device and server. I opened this issue here to get any info why such a thing is printing on the console.

**Comment by rahulraman0108** [comment]
Hey, got the issue, it was due to colours I think it was not visible in PowerShell window. Tried it in command prompt and it showed up correctly.

![image](https://user-images.githubusercontent.com/42905362/84773312-ddbba080-aff9-11ea-8e3f-eda84e5c809a.png)

I got the idea to check it on cmd as I have experienced it before too in PowerShell when using make:

![image](https://user-images.githubusercontent.com/42905362/84773132-99300500-aff9-11ea-9db8-a1abf85fd7c2.png)
