### ISSUE TITLE
Updating BombSquad for App Store

### ISSUE THREAD

**Issue by M0REKZ** [efroemling/ballistica#587]
I realized that 1.7 exists now, while the app store version is actually at 1.4... it would be very nice to update that version

thanks 🙂

**Comment by Dliwk** [comment]
Quoting https://github.com/efroemling/ballistica/discussions/304#discussioncomment-1374897 and moving this issue there
> Sorry for the slow reply, but a quick explanation: There are currently a number of outdated builds of the game out there (the Mac App Store, Oculus Rift, etc.). Each one of these has some minor blocker that I need to take care of before I can update it (Mac App Store builds currently get rejected due to how the game handles hardware controllers, the Rift builds need to be updated to properly support touch controllers, etc). I do intend to get these all back up to date at some point, but for the time being I am iterating on the game and only releasing official updates on Android platforms just to keep things simple. The ballistica builds here as well as the bombsquad test builds at https://files.ballistica.net/bombsquad/builds/ should always be up to date though and hopefully enough to hold people over until I can get all store versions back in sync.
> 
> Worth mentioning: there was also a snap version in the Ubuntu store maintained by someone else, but it seems to have only been 1.4.x. If someone would like to put together a script to assemble a snap package from the repo here I'd be happy to start pushing updates to the store. I hope to do this myself when I get time but it's not at the top of my priority list.
