### ISSUE TITLE
Map Spawn set problem

### ISSUE THREAD

**Issue by TornadoesPride** [efroemling/ballistica#59]
Hey Eric, 
I play offline quite a while when am not online.... so suppose am playing the Last Stand, when I select the Leave option, the UI takes me back to the Main Screen..... whereas it used to show the list of offline games and the tournament menu.... so please look into it if you have time.... (not important but still)

so about the map respawn problem, my family is huge and we typically make 4teams to play so the old BS is of 1.4 update and it was pretty straight-forward to make the new spawn points for all individual 4 teams...no problems there thanx to you... but in ur 1.5 update it doesnt seem to work, even if I render the spawn region and mesh file of the map together it shows my preferred set locations but still the game manages to set the spawn point to default when playing the game. My edited one doesnt seem to work at all... though it works perfectly fine on the older version... Help😞

**Comment by efroemling** [comment]
Thanks for the heads-up! I've recreated the leaving-last-stand issue so I'll get that fixed for the next update. Interestingly I'm noticing that I get dropped to the top level menu if I do 'End Game' but dropped into the Co-op selection screen if I do 'Leave Game' and wait for a few seconds. Do you see that same behavior or do you always get the top level menu?

On the second note: I'm assuming you're editing the files in bastd/mapdata/\<mapname\>.py?
My guess is that you might be running into [this](https://github.com/efroemling/ballistica/wiki/Knowledge-Nuggets#python-cache-files-and-release-builds).
(long story short: you may need to blow away \_\_pycache\_\_/\<mapname\>.opt-1.pyc before any changes to \<mapname\>.py will take effect.
Hope that helps!

On a random note: 1.5 is more strict about disallowing tournament scores if it finds modified python files, so you may want to make a copy of the whole python or ba_data folder that you can swap back in when you want to play tournaments.

**Comment by TornadoesPride** [comment]
Hi Eric again,

That was a silly mistake on my part. Yea, you're correct it happens when I
press the End Game button NOT THE LEAVE GAME button.

Plus, tremendous amount of thanx for the Help... and yea it makes me Happy
to say that I dont regret at all that I bought this game😃

**Comment by efroemling** [comment]
Ok the main menu issue should be fixed in the latest commit: 113175218569626920ae4621a07355c0ddcfc489

Did you get your map modification stuff working?

**Comment by TornadoesPride** [comment]
Thank you very much Eric, The Spawn problem was fixed way easily..... I'll
keep you posted for more issues that come along the way..... thanx for the
help😃
