### ISSUE TITLE
. Your server does not appear to be joinable from the internet. 

### ISSUE THREAD

**Issue by IPCisNotM77** [efroemling/ballistica#604]
Master server access check of udp port 43210 failed.
Your server does not appear to be joinable from the internet.
Set environment variable BA_ACCESS_CHECK_VERBOSE=1 for more info.

### Steps to reproduce
1. Launch launch_bombsquad_server.bat
2.BombSquad server manager 1.3.1 starting up (opt mode)...
Interactive mode enabled; use the 'mgr' object to interact with the server.
Type 'help(mgr)' for more information.
Valid server config file loaded.
>>> Launching server subprocess...
root: BombSquad Headless 1.7.22 build 21167.
root: BombSquad 1.7.22 (21167) entering server-mode Fri Jul 14 13:04:42 2023
3.Master server access check of udp port 43210 failed.
Your server does not appear to be joinable from the internet.
Set environment variable BA_ACCESS_CHECK_VERBOSE=1 for more info.

### Machine
**Platform**: Windows 10
**BombSquad version**: [1.7.22]
**Commit**: [2642488](https://github.com/efroemling/ballistica/commit/2642488a51b250752169738f5aeeccaafa2bc8de)
Select what do you want to use: release version or commit. Please use a hyperlink.

### Screenshots
Put some screenshots here if needed.

### Extra
Put some extra information here. For example, describe your assumptions about the cause of the bug.

**Comment by Dliwk** [comment]
Hi! This does not look like Ballistica issue; you can google how to open/forward port in your router/hosting service or ask in our [Discord server][1].

[1]: https://discord.gg/U7cUJTajpP

But if you're sure that you did forward port 43210 correctly, feel free to reopen and add some additional information.
