### ISSUE TITLE
generate dummy modules error in WSL

### ISSUE THREAD

**Issue by PersonManRee** [efroemling/ballistica#643]
im getting this error when i try to generate dummy modules in WSL

![image](https://github.com/efroemling/ballistica/assets/79378783/8d55988e-26b8-475e-8910-8e4c2a17967d)
![image](https://github.com/efroemling/ballistica/assets/79378783/19355366-9c3b-4377-a3a4-5e0a8286ad55)

**Platform**: Windows 10 / WSL 1 (also tryed on WSL 2. same result) / Ubuntu 22.04.3 LTS.
**BombSquad version**: least (1.7.32)

i setted up the project just like in the [getting started](https://github.com/efroemling/ballistica/wiki/Getting-Started) step-by-step (except Python virtual environment)

**Comment by Loup-Garou911XD** [comment]
@PersonManRee check this commit,I think it fixed it
https://github.com/efroemling/ballistica/commit/cf284e475536455430fe313d2218e7933b8f3bf8

**Comment by PersonManRee** [comment]
yep it fixed now
thanks for notifying me

**Comment by PersonManRee** [comment]
> @PersonManRee check this commit,I think it fixed it [cf284e4](https://github.com/efroemling/ballistica/commit/cf284e475536455430fe313d2218e7933b8f3bf8)

yep it fixed now
thanks for notifying me !
