### ISSUE TITLE
There's a little problem, Mr. Eric

### ISSUE THREAD

**Issue by LAMER-coder** [efroemling/ballistica#657]
Hello,

Although my device is not rooted, I am receiving a warning that "rooted devices cannot participate in the tournament" because I once logged into the game from the LD emulator. I am sure that the LD emulator is not rooted. My device does not have root. I do not enter many tournaments, but this situation is a bit frustrating. Could you please help me with this issue, Mr. Eric? :)

**Comment by Loup-Garou911XD** [comment]
If you are running game on emulator, then that's expected behaviour

**Comment by Dliwk** [comment]
Root checker is annoying, but it seems to be around until could-based tournaments appear. (duplicate of #194)
