### ISSUE TITLE
Leaderboard issue

### ISSUE THREAD

**Issue by hondoslack** [efroemling/ballistica#66]
Hey Eric, was playing Infinite Onslaught, got 7th place, but score didn't post to leaderboard?? Thanks, great job on the updates!!

![IMG_20200623_220202](https://user-images.githubusercontent.com/1002589/85504562-226aad00-b5a1-11ea-83a6-3b2e192a9377.jpg)

**Comment by efroemling** [comment]
Hmmm; could you let me know if this happens every time for you or if it was a one-time thing? If it was just once then perhaps a server-side glitch is to blame, but if it is constantly happening then something might be broken that I need to look into...

**Comment by hondoslack** [comment]
Well, its definitely not every time, but definitely oddities pop up now and then. Like this evening, I completed a round that was 9th best per the top 10 scores, but it showed as #14 out of 1000. So maybe the top 10 is just not refreshing? I've noticed this on previous versions too, where the (#n out of 1000) isn't in sync with top 10. Oh well, 1st world problems! :)
