### ISSUE TITLE
Game gets stuck on exit

### ISSUE THREAD

**Issue by Dliwk** [efroemling/ballistica#660]
### Description
This blocking `fgets` call seems to prevent game from gracefully exiting:
https://github.com/efroemling/ballistica/blob/978f32f9f098bd0ff1dc64b496ec31cf493ded09/src/ballistica/base/support/stdio_console.cc#L52-L55

Pressing Ctrl+D (and triggering EOF) allows game to finally shut down.

I didn't find any inter-thread-signal-forwarding logic which could trigger EOF, but this problem didn't exist for me some time ago. :man_shrugging: 

### Steps to reproduce
1. Launch BombSquad
2. Close BombSquad
3. Do not press Ctrl+D
4. ???

### Machine
**Platform**: Fedora Linux 39
**Commit**: https://github.com/efroemling/ballistica/tree/978f32f9f098bd0ff1dc64b496ec31cf493ded09/

**Comment by Loup-Garou911XD** [comment]
I can vouch
This is reproducible everytime on my machine

**Comment by Dliwk** [comment]
This seems to be fixed now https://github.com/efroemling/ballistica/blob/main/CHANGELOG.md#1735-build-21889-api-8-2024-06-20
