### ISSUE TITLE
I have problem with making my server public

### ISSUE THREAD

**Issue by MRcreeper176** [efroemling/ballistica#675]
### Discussed in https://github.com/efroemling/ballistica/discussions/665

<div type='discussions-op-text'>

<sup>Originally posted by **MRcreeper176** February 24, 2024</sup>
My server was working correctly after i run it, but after 2 days...
I tried to change my port (it was 1176), but it doesn't work.
Where's the problem from?
![20240224_192723](https://github.com/efroemling/ballistica/assets/156354493/b4ba227c-6d99-4225-ad35-73b79f3d8b6b)
</div>

**Comment by MRcreeper176** [comment]
I forwarded my port from my router.
My server is running at the moment, but my problem is that it's not public.
It's true in the config file,
And i can search it with (filter), but i can't join it (it says 'party is full')

**Comment by Loup-Garou911XD** [comment]
Did you do the port forwarding correctly?
Because the game check of the port failed

**Comment by MRcreeper176** [comment]
I did it step_to_step with google and for multiple times.

**Comment by Loup-Garou911XD** [comment]
> Remember that my server is working but it isn't public My problem is making the server public

can you share the port forwarding configuration?
Be careful to not expose your public ip

**Comment by MRcreeper176** [comment]
![Screenshot (1)](https://github.com/efroemling/ballistica/assets/156354493/616cd712-f625-423d-a136-fb78ae9a0160)
Do you mean this?

**Comment by Loup-Garou911XD** [comment]
> ![Screenshot (1)](https://github.com/efroemling/ballistica/assets/156354493/616cd712-f625-423d-a136-fb78ae9a0160)
> Do you mean this?

No
That's windows firewall
There's also a firewall in your router that doesn't allow incoming traffic 
You need to allow the incoming traffic from your router

**Comment by MRcreeper176** [comment]
How to do it?
I'm using my phone's hotspot i haven't got a router

**Comment by MRcreeper176** [comment]
I can't find how to do it in the google :(

**Comment by EraOSBeta** [comment]
As far as I know you aren't able to forward or open up ports at all when using mobile data because of how ISPs usually operate

**Comment by EraOSBeta** [comment]
However if your ISP actually allows it (probably not, you could contact and ask from their customer support) then you *could* do some research and make it work. If that is the case you can start your research from [here](https://android.stackexchange.com/a/207342)

**Comment by MRcreeper176** [comment]
So i can't do it😕

**Comment by MRcreeper176** [comment]
Thanks anyway🙏🙏🙏
