### ISSUE TITLE
Mods compiler Issue (Android) 

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#69]
@efroemling I was trying to write mods so I copied and pasted the **meteorshower.py** into the BombSquad folder and **changed the class name** as you can see below:

![IMG-20200625-WA0009](https://user-images.githubusercontent.com/42458260/85688287-3de3ce00-b6ef-11ea-855f-4eb72ebda736.jpg)

I opened BombSquad and then closed it to check if the file was compiled to _.pyc_. I found out that the file was not compiled as you can see: 

![IMG-20200626-WA0001](https://user-images.githubusercontent.com/42458260/85819560-aa170e00-b791-11ea-8195-8fe294bbea07.jpg)

Even a single line statement (which I wrote in a new py file) :
```python
import ba
```
was not getting compiled

**Comment by efroemling** [comment]
I wonder if this is a permissions issue. By default, Android can't read that folder until you give it read/write-external-files permission. Perhaps if you've uninstalled/reinstalled it may have lost this. Can you delete the whole BombSquad folder and relaunch the game?.. if the folder gets recreated then the game has access; otherwise you can poke 'show mods folder' in settings/advanced which should get it to ask you for permission again.

If that is not it, we may have to poke around more. Are you able to telnet in to the game or do you have a keyboard you can attach to use the in-game console (~ key)?

**Comment by Benefit-Zebra** [comment]
This is not a **Permission Issue** since:

1. I am playing BombSquad on a lower Android version(5.1.1) which means that by default the apps have access to permissions they will need when they are installed.

2. I tried to _delete the whole BombSquad folder and relaunch the game_ and the BombSquad Folder got created. I clicked on 'show mods folder' and then the 'about_this_folder.txt' also got created.

I don't know what telnet means.

Sadly I don't have a keyboard to attach with my device.

**Comment by Awesome-Logic** [comment]
You can use a Mobile Telnet app to connect to port 43250 on localhost (127.0.0.1) :)

**Comment by Benefit-Zebra** [comment]
@Awesome-Logic It worked, Thanks

**Comment by Benefit-Zebra** [comment]
@efroemling @Awesome-Logic When I Establish Telnet connection with BombSquad, BombSquad asks to allow telnet access, I tapped on allow. When I return back on Telnet screen, it asks for password which I don't know:

![IMG-20200701-WA0014](https://user-images.githubusercontent.com/42458260/86202698-a106b200-bb80-11ea-82da-68fa2133c376.jpg)

Also @efroemling, please tell the further steps what I need to do now.

**Comment by Benefit-Zebra** [comment]
@efroemling This problem of Mods Compiler is now going over places. Today, after downloading **BombSquad 1.5.16 Play Store Version**, I opened the game, clicked on Play button, Team Game, Customize, New playlist, Add game, I found that **Brain Freeze got compiled** and it was working perfectly. 

![IMG-20200702-WA0012](https://user-images.githubusercontent.com/42458260/86318798-94ea2580-bc50-11ea-8001-76d1aa9d6dbe.jpg)

![IMG-20200702-WA0013](https://user-images.githubusercontent.com/42458260/86318800-96b3e900-bc50-11ea-9380-0aa1f7479934.jpg)

I _experimented_ and got to know that **_only when I click on Add game_**, The **BombSquad folder gets compiled**. But this raised a issue that why "import_ba.py" did _not get compiled_.

I think we should instead to getting BombSquad folder compiled when we press Add game, We should get the folder compiled when the BombSquad game starts.

**Comment by Benefit-Zebra** [comment]
Mods Folder is working perfectly fine.
