### ISSUE TITLE
Startup Error Of BombSquad 1.5.11 on Android

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#70]
I separated this issue since it didn't have any connection with the mentioned bug in **Android BombSquad Bug**

Sometimes when I open BombSquad app, it shows error: 
![IMG-20200625-WA0007](https://user-images.githubusercontent.com/42458260/85687454-83ec6200-b6ee-11ea-98ef-a1bc4c7f6638.jpg)
and when I restart the app, it works fine.

**Comment by efroemling** [comment]
Ok, I *think* I've got this fixed in 1.5.13. That should be hitting the beta channel within an hour or two.. Can you let me know if you're still seeing this crash after you get that update?

**Comment by Benefit-Zebra** [comment]
I installed BombSquad 1.5.12 and this bug got solved.
