### ISSUE TITLE
Banned from Bombsquad tournaments due to rooted device

### ISSUE THREAD

**Issue by 999pingGG** [efroemling/ballistica#714]
### Description
So… I just remembered this game and installed it for the first time after a few years, and I happen to use a rooted device now as my daily driver. Nobody told me that my Google Play account would be PERMANENTLY banned from tournaments JUST because I OPENED the game on a rooted phone. I can enter tournaments on a fresh account on an unrooted phone, but if I use my main account tournaments are disabled. Online cheating is something I DESPISE and cheating on Bombsquad is something that didn't even cross my mind. Now I'm being punished as one of them. Is there any way to get unbanned?? Bonus points if able to play on a rooted phone WITH NO CHEATS.

**Comment by EraOSBeta** [comment]
Your account shouldn't be banned right now. Are you able to join a tournament on your old account but on a not rooted device?

**Comment by 999pingGG** [comment]
Not at all. With my main (banned) account on an unrooted device I still get the error. On the unrooted device I reinstalled the game, made a new account and I was able to enter tournaments, but as soon as I login with my main account I'm no longer allowed in tournaments.

**Comment by EraOSBeta** [comment]
When logged into your main account, go to `Settings->Advanced->Send Code`, type `999pinggg_banned_account`, and hit send. This way Eric can take a look at your account next time he comes to the mortal realm

**Comment by 999pingGG** [comment]
Thank you, I didn't know of that option. I did that already, let's hope for the best and wait for the day where this "root ban" won't be necessary.

**Comment by EraOSBeta** [comment]
rooted devices won't be a problem for 1.9 since tournaments will be moving to the cloud by then; however that's still a long time away.

**Comment by 999pingGG** [comment]
I entered the game today and noticed that I'm no longer banned and I can enter tournaments even on the rooted phone, thanks Eric!
