### ISSUE TITLE
We need Unicode and Chinese

### ISSUE THREAD

**Issue by longmouses233** [efroemling/ballistica#716]
## Description
**Support chinese** in game on Windows,Linux and so on.

## Solution
**Show chinese** in normal。。。

## Alternatives
Change english to pinyin ,but its so silly

## Additional context
:P

**Comment by EraOSBeta** [comment]
Has been requested many times for a lot of languages. Right now it's in the "planned for 2.0" pile.

**Comment by Dliwk** [comment]
Hi there; yes, requested many times, I'll close this as duplicate of #45 #367 #523. (See a bit more explanations there).
