### ISSUE TITLE
Tournament UI remains on top after transferring to the store

### ISSUE THREAD

**Issue by efroemling** [efroemling/ballistica#74]
(pasting from an email)
I found a problem with the tournament menu. It is nothing very serious, just something that is not working properly. When I click to use tickets in the tournament and I don't have enough, the game automatically warns me that I don't have tickets and a button to go to the store appears. If I click on the button, I am directed to the store, but the entry interface for the tournament remains on top.

**Comment by itsre3** [comment]
I guess this might be too late but the bug still there till now. I guess the pic below might help
![Screenshot_20220605-201523](https://user-images.githubusercontent.com/105688454/172066929-bdda6a27-fe70-461f-a53b-51a0797bdfaa.jpg)
