### ISSUE TITLE
Main Menu Screen Bug

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#75]
**Occasionally** this happens, When I press the play button on Main Menu the Play screen appears but when I click on back arrow, the Main Menu screen gets replaced by Play Screen as you can see below:

![IMG-20200627-WA0001](https://user-images.githubusercontent.com/42458260/85914954-e9f8f680-b860-11ea-9909-0a9f15acb075.jpg)

I think we should force the Main Menu UI Screen to come again irrespective of anything when the back arrow is pressed on Play Screen. In this condition, Buttons of Main Menu work perfectly fine. 

Note: @efroemling This Bug is **since** when **_BombSquad had its Hard Mode for Free._**

**Comment by efroemling** [comment]
You're right; this darn bug has been lurking there for a while. I'd like to fix it but I can't find a consistent way to reproduce it; I just run into it occasionally. Are you aware of a consistent way to get it to happen?

**Comment by Benefit-Zebra** [comment]
@efroemling Yeah it can be reproduce more often if the device gets lagged, like instantly turning on the internet and then clicking on play button. Other than this, I don't know any other way to reproduce this.

**Comment by Benefit-Zebra** [comment]
@efroemling Yeah, it can be reproduced more often if BombSquad or Device **gets lagged**, like turning on the internet after opening BombSquad and then clicking on play button while the BombSquad is still syncing data. 

Other than this, I don't know any other way to reproduce this. It just happens occasionally.

**Comment by efroemling** [comment]
Ok, I *think* this should be fixed with the latest commit: 3891394831c04ec84fec9b87feaf49da0f9123d3
(this will correspond to BombSquad 1.5.121 which I'll push out in a day or two).
Can you let me know if you see this show up still after that?

**Comment by Benefit-Zebra** [comment]
I will reopen this issue if this bug occurs again.
