### ISSUE TITLE
Please add the scroll button for zooming in and out using manual camera?

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#80]
i am having a really hard time trying to zoom in and out, ie i need to shake the mouse 100 times in order to move in and out, when holding alt. If i could just zoom in and out using the scroll option of the mouse, it would save massive amount of time.

**Comment by Zee-hash** [comment]
In the latest version, I can use the mouse wheel to zoom in and out, but I don’t know when the function was added. But you can try with the version after 1.5.7

**Comment by efroemling** [comment]
I was cleaning up input code recently and in the release notes for 1.5.6 you'll see that the mouse wheel should work for manual camera movement on more platforms. Can you let me know if its working for you?

**Comment by efroemling** [comment]
Anyway, this *should* be improved now. Please open up a new issue if it is not.
