### ISSUE TITLE
Can you please add the option of disabling camera shake

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#81]
Most tournament games plus playing coop with friends cause the camera to shake whenever the bomb hits the ground. Its good but since it overshakes, the aim precision is lost whenever i am throwing multiple impacts on bots or players. Please give the option of disabling it.

**Comment by efroemling** [comment]
Ok, done. Added in commit 5fd7783b23240d64746aa8cece1e616270ebaf4b
(and BombSquad 1.5.21 which I'll push out within the next day or so)
