### ISSUE TITLE
Names In Credits list

### ISSUE THREAD

**Issue by Gengar-lab** [efroemling/ballistica#83]
The Credits list should have the names arranged in Alphabetical order so it will be easy for anyone to find anyone's name.

Also some have have been repeated in list.

**Comment by Benefit-Zebra** [comment]
@efroemling Here is the credit list in Alphabetical order:

[langdata.txt](https://github.com/efroemling/ballistica/files/4841994/langdata.txt)

I have changed the extension of langdata from .json to .txt as github doesn't support uploading .json

**Comment by efroemling** [comment]
The langdata.json file gets auto-generated as part of my build system, so if you'd like to write a bit of python code that takes those names, alphabetizes them in a smart way, removes duplicates, etc. then I'd be happy to take a look. They are currently sorted based on last name I believe; though perhaps the relationship between multi-word names and single-word ones is not ideal. I originally did a simple sort so they were alphabetized by first name but a number of people commented that that wasn't ideal either. 🤷🏼‍♂️

**Comment by Benefit-Zebra** [comment]
@efroemling Here is the program, It will sort the names and remove the duplicate ones:

(langdata_sorter.py)[https://drive.google.com/file/d/1pVRT9Wh4GH_DJBcW89TK3GYj9mNOO1wO/view?usp=drivesdk]

The langdata.json file should be in the same directory as this program. Everything else of sorting the names and removing the duplicate ones and rewriting langdata.json will be done by the program.

**Comment by Benefit-Zebra** [comment]
@efroemling Here is the program📄:

[langdata_sorter.py](https://drive.google.com/file/d/1pVRT9Wh4GH_DJBcW89TK3GYj9mNOO1wO/view?usp=drivesdk) 

The **_langdata.json file should be in the same directory as this program_** or you can just replace both "**langdata.json**" in the program with file path. Everything else of **sorting the names** and **removing the duplicate ones** and **rewriting langdata.json** will be done by the program when it is run.

It will get sorted in following way:

1. Symbols and Numbers
2. Names starting with CAPITAL letter, if two names are same, they will be sorted by second name and so on
3. Names starting with small letter
4. Non English Text

**Comment by Benefit-Zebra** [comment]
@efroemling Here is the program📄:

[langdata_sorter.py](https://drive.google.com/file/d/1q01T-bmS75s_oV6n2S4CMdU4yjYTEfuZ/view?usp=drivesdk) 

The **_langdata.json file should be in the same directory as this program_** or you can just replace both "**langdata.json**" in the program with file path. Everything else of **sorting the names** and **removing the duplicate ones** and **rewriting langdata.json** will be done by the program when it is run.

It will get sorted in following way:

1. Symbols and Numbers
2. Names starting with CAPITAL letter, if two names are same, they will be sorted by second name and so on
3. Names starting with small letter
4. Non English Text

**Comment by Benefit-Zebra** [comment]
@efroemling I think, we should now do this.

**Comment by efroemling** [comment]
I haven't had time to wire this up to my tools that generate the name list, but I wonder if it might make more sense to just sort them after they have been loaded in the UI so that I am not the bottleneck here. The code for that is bastd/ui/creditslist.py if you'd like to give it a whirl.
