### ISSUE TITLE
Save replays

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#84]
The replays that we rename in the **Watch** window should have a option to save the replay as video in the storage/gallery.

**Comment by astrojade** [comment]
The replays which you save, are recorded in the format BombSquad Replay (.brp). If they were saved normally(as mp4) the file size would be HUGE. That is why it is saved in a very super compressed format. If you want to record your replays, you will have to use a screen recorder like bandicam or gamebar on window 7/8.1 and windows 10 respectively.  And to screen record on phone, use a screen recorder like a2z recorder or any other inbuilt screen recorder.

**Comment by Benefit-Zebra** [comment]
Thanks @astrojade for Info.
