### ISSUE TITLE
Why is the camera zooming out when there are like less players in the map. 

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#85]
This is really annoying. I was playing just now against 2 players, in the pad map, and the camera just zooms out for no reason, instead of keeping the camera close to the player, it shows the entire map, plus you can even see the underneath edges of the pad. The players were not standing on opposite sides of the map, there were in front of me, Please do something about the camera, I checked the android camera movement, and its really much better than compared to the pc camera which keeps zooming in and out, and moving on its own. its acts more like a distraction than actually benefiting the player. Please do something about it.  The camera doesnt work well if its in windows version. The players appear really small, and even in full screen, I have to make it entirely full full screen just soo the players and characters look bigger in size.

**Comment by Awesome-Logic** [comment]
Were you in full screen? Unusual window sizes can sometimes cause this issue I suppose, which is not really a bug in my opinion.

**Comment by astrojade** [comment]
> Were you in full screen? Unusual window sizes can sometimes cause this issue I suppose, which is not really a bug in my opinion.
I can understand when it happens once in a blue moon. When its not completely full screen, ie hiding the task bar and the close, max buttons, the players are always zoomed out. I played this game on phoenix os just to see whether i was in the wrong somewhere, and boy the difference is massive. The camera is really well optimized for phone, The camera is really zoomed in. It wont zoom out and show the underneath of the map, it knows how to keep the camera on the player.

**Comment by efroemling** [comment]
If you can show a video of this behavior it would be helpful. I would imagine the camera zoom logic might behave strangely in extremely wide or tall windows but it shouldn't go crazy at normal screen ratios.
Perhaps you saw some other glitch such as a player or flag falling through the floor? In that case the camera could try to to zoom out to keep everything in view and look broken..

**Comment by astrojade** [comment]
The camera is fine when its 1 vs 1. But when there are more than 3 players the camera zooms out to show everyone on the map, when it should be stuck close to you. But anyways ill record and show what is the scene.

**Comment by efroemling** [comment]
This also brings up an interesting question. Should the camera always try to keep all players/flags/etc on screen at once (the current behavior) or should it only try to keep players on the local device in view? It might be interesting to try the latter but I imagine we'd need some sort of offscreen indicators for other players/flags/etc. or else one might not even know where the flag is in a large map.

**Comment by astrojade** [comment]
That last point, really gave me a better perspective as to why the camera is acting in this kind of strange way.
If i had to choose, i too would choose the latter, but after reading that last point, it made me realise, that it would complicate things for bigger maps. Basically i  only wanted the camera to stay close in modes like death matches/elimination/boxing , but i think it would over-complicate it. Better i just stick to using the manual camera.

Btw i really liked the new modification of the manual camera via the scroll button. now at least i can zoom out without having to disable the manual camera, re-enable it, and then shake all the way to the destination.
Btw im sorry for not sending the video regarding it, 
  I have attached a 1 min video if you Still want to see the problem, The camera zooms out at the very starting and at the end. I am the one with the penguin character.
https://drive.google.com/file/d/1kK21DwaTNHMgbYxhVnlDYbN2IB2B7esX/view?usp=sharing

**Comment by astrojade** [comment]
Okay, just an update regarding this, In maps like football or the pad, the camera zooms out when any player is closer to the camera. Its very annoying. I am forced to use the manual camera for such maps.

**Comment by astrojade** [comment]
Update: I tried the new version  today, and i noticed something wrong with the camera, The camera is away from the player plus its tilted to the left for some weird reason, I will upload the video and send.

**Comment by astrojade** [comment]
### Please rollback the camera modifications
@efroemling I just realized how dumb my above statements were, i didn't expect the camera to be looking like this, Please rollback the changes. The Camera Movement worked out well for the Online Servers. But the problem came up when i was playing the 1 player tournaments. The camera was focused too much on the player, and didn't show the bots on the above platform. 

i am attaching a video of the scene:
https://drive.google.com/file/d/17uZKQVvhAKlT_vSJSd_4OA9WPthR8UQU/view?usp=sharing

Now that i have seen this modification, i really feel that the old camera adjustments were better, Really Sorry for giving you extra headache regarding all this.

**Comment by efroemling** [comment]
Interesting; that does look significantly different at times.
I've not actually made any intentional changes to the camera logic since 1.4, but it is possible that I threw something off accidentally.
Can you confirm which version of the game was the last one with the 'old' camera behavior? That would help me track down what might have changed.

**Comment by efroemling** [comment]
I've been poking around at this and I can't seem to reproduce the look from your 'New Camera Adjustment' video. For example, when I move to the bottom of the map on Runaround the bottom railing stays pretty close to the bottom of the screen for me like in your 'old' video. In your 'new' video the railing is like 25% up from the bottom of the screen.

I'm wondering if there is something else at fault here such as faulty gyroscope offsets. Can you go into Settings->Advanced and disable camera gyroscope movement and see if that makes a difference?

**Comment by astrojade** [comment]
Ok, i just realised that the camera shake also controls the gyroscope movement.
The moment I disabled it, the camera was back to normal.
I will do further testing and inform you regarding this.
Can you make the camera shake and the gyro as 2 separate buttons?
I will attach a video regarding this.
https://drive.google.com/file/d/1JeLCB17MvDLIG2rxnQ-6jycBm3zK0X6w/view?usp=sharing
Disable Camera shake should just prevent the camera from shaking up and down whenever a tnt or bomb explodes. 
And gyro is gyro.

**Comment by efroemling** [comment]
Camera shake and gyro should be 2 separate controls currently. Are you seeing that the camera shake check-box affects both? That would definitely be a bug if so...

**Comment by astrojade** [comment]
Yes the camera shake checkbox is affecting both

**Comment by astrojade** [comment]
Eric, i have fixed the problem, i am using the magnifier tool while playing, and its helping out wherever the camera is in an awkward position. You can remove the gyroscope option. Just keep the "Disable camera shake" checkbox.

**Comment by astrojade** [comment]
Lol, my system cannot even handle multi tasking :( Is there some way to implement the mouse scroll for zooming in while the camera is moving around? Normal camera movment + zooming in/out(without hitting manual camera).  Yea this would help alot.

**Comment by astrojade** [comment]
I am really sorry for all this, im closing this discussion because i believe that my system is the cause for this complete fiasco. Please remove the gyro if no one is using it. Really Really Sorry, thank you for trying even though my system was doing stupid stuff. The only thing i am aware of is that there was some clarity problem in my system which caused all this problems. Even while it was on high settings, ghosting seemed to be happening which caused alot of problems. Anyways after breaking my head  alot on this ssystem and fixing the thermal, power throttling as well as tweaking the nvidia controls to the correct settings the game seems to be performing much better than before. I almost left this game for good. 
Sry once again
