### ISSUE TITLE
Score didnt get uploaded bug in infinite runaround Tournament

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#86]
The score didnt get uploaded, neither did the black screen containing my score was displayed at the very end. It crashed immediately after the game ended. Version.1.5.13. I even have the replay showing that the black screen didnt get displayed. It immediately cuts to the starting of the vid. This is the link of the vid. Its a 11mb file np. https://drive.google.com/file/d/1Vq1-BpANeSh8c4VMeBNDovbKLVi1T8TW/view?usp=sharing

**Comment by efroemling** [comment]
Thankfully this is fixed now as of 1.5.16
