### ISSUE TITLE
Weird bug...

### ISSUE THREAD

**Issue by PythonCode-blip** [efroemling/ballistica#87]
(I downloaded the latest version of BombSquad)
So there is this bug/error when you're done with Target Practice Pro, it kicks me out of the app and restarts... Why?

**Comment by Benefit-Zebra** [comment]
@PythonCode-blip Does your screen appears like this after completing Target practice pro:

![IMG-20200625-WA0006](https://user-images.githubusercontent.com/42458260/85687035-1fc99e00-b6ee-11ea-8c34-2a94d34b7372.jpg)

**Comment by efroemling** [comment]
This is a known bug I'm trying to track down, but I haven't been able to reproduce it on my test devices yet so it's taking me a while. Any info anybody can give me would be useful. Stuff like:
- does this happen all the time, or just randomly?
- is this only in tournaments, or on any co-op game? (target-practice is mentioned here, but I think it happens elsewhere too)
- what device/android-version are you seeing this on?
- is this happening to anyone on non-android versions of the game? Or the generic android version? Or just the Google Play version?
Thanks in advance for any help. I'll try to get this cleared up as soon as possible. In the meantime you may want to go back to 1.4 if this is too much of a problem.

**Comment by Benefit-Zebra** [comment]
@efroemling 

> * does this happen all the time, or just randomly?
It happens with me all the time. 

> * is this only in tournaments, or on any co-op game? (target-practice is mentioned here, but I think it happens elsewhere too)
It happens in both tournament and all co-op games except in Team mode/FFA mode

> * what device/android-version are you seeing this on?
I think it is a compatibility issue. If I play on my device having lower Android version(5.1.1), all above issues occur but if I play on my other device which is of higher Android version(7.1.1), none of the above issues occur. 
Both my device my same version of BombSquad. 

> * is this happening to anyone on non-android versions of the game? Or the generic android version? Or just the Google Play version?
I have installed BombSquad 1.15.5 Google Play version on both my device.

**Comment by efroemling** [comment]
Thanks a ton for the info. This bug has been quite tricky for me to track down, but I *think* I've got it fixed now in 1.5.16. Can you folks give that a try and let me know if you're still seeing any crashes? Test builds are up now at https://files.ballistica.net/bombsquad/builds/ and I'll get the Google Play build updated as soon as I can (their developer portal is down at the moment, so as soon as it comes back up...)

**Comment by Benefit-Zebra** [comment]
@efroemling I have downloaded BombSquad 1.5.16 Generic Version. All Co-op games and tournament + with their score submissions are working perfectly.

**Comment by efroemling** [comment]
Great to hear things are working! This bug was quite a pain. I'm hopeful it'll start to be more smooth sailing for 1.5 now..
