### ISSUE TITLE
Scores Not uploading in Football 

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#89]
Same bug, the game crashes at the end screen. You can only see 0s for a split second, and then it immediately crashes.

**Comment by Benefit-Zebra** [comment]
@astrojade Does your screen appears like this before the app crashes:

![IMG-20200625-WA0006](https://user-images.githubusercontent.com/42458260/85687035-1fc99e00-b6ee-11ea-8c34-2a94d34b7372.jpg)

**Comment by astrojade** [comment]
Not at the beginning. But yea it looks exactly this out after the map ends. I see 0s on top, and Bam crashed.

**Comment by Benefit-Zebra** [comment]
@astrojade On which device are you playing PC or Android.

If on PC : What is your BombSquad version?

If on Android : What is your Android version and BombSquad version?

**Comment by efroemling** [comment]
Ok, I *think* I've got this fixed in 1.5.16. Can you give it a try and let me know?  Test builds are up now [here](https://files.ballistica.net/bombsquad/builds/) and I'll get the Google Play beta channel updated as soon as I can (their developer console is down at the moment.. grumble)

**Comment by Benefit-Zebra** [comment]
@efroemling #66 #86 #87 #88 issues can now be closed, if wanted.

**Comment by efroemling** [comment]
Yes I'll go ahead and close these :)
