### ISSUE TITLE
Few textures are same

### ISSUE THREAD

**Issue by Benefit-Zebra** [efroemling/ballistica#93]
1. Actionhero,
2. Alien,
3. Assassin, 
4. Cowboy,
5. Gladiator, 
6. Jumpsuit, 
7. Neospaz, 
8. Oldlady, 
9. OperaSinger, 
10. Robot, 
11. Superhero, 
12. Warrior, 
13. Witch, 
14. Wrestler, all have same **Color, ColorMask, Icon, IconColorMask** textures.

![IMG-20200705-WA0046](https://user-images.githubusercontent.com/42458260/86536726-81b4af80-bf07-11ea-8b51-d493f5598485.jpg)

![IMG-20200705-WA0043](https://user-images.githubusercontent.com/42458260/86536729-837e7300-bf07-11ea-8ff1-e3792fae084b.jpg)

![IMG-20200705-WA0045](https://user-images.githubusercontent.com/42458260/86536731-837e7300-bf07-11ea-91f3-001c98789c6b.jpg)

![IMG-20200705-WA0044](https://user-images.githubusercontent.com/42458260/86536732-84170980-bf07-11ea-9a35-4bb7930ba2dc.jpg)

**Comment by efroemling** [comment]
This is expected. Those were placeholders that I put in long ago so I could add new characters without requiring everyone to update their game after I added them (so un-updated people would simply see spaz instead). I'll be rolling out downloadable assets in [1.7](https://github.com/efroemling/ballistica/wiki/Roadmap#ballistica-17) which will make this unnecessary so this stuff will go away at some point...
