### ISSUE TITLE
Cant see open ports

### ISSUE THREAD

**Issue by MythB** [efroemling/ballistica#94]
BombSquad Build Windows 1.5.18 ports are opened but i get "not joinable from internet" error. Without any terminal error.

**Comment by efroemling** [comment]
If you're seeing this in the GUI then I don't think there's supposed to be any terminal error, so this is expected.

Basically what this test does is sends a message to the master-server out on the internet which then tries to contact your IP address on the game port. If the message makes it to the game and the game responds successfully, it will tell you that you are accessible.

So if you've opened the correct UDP port and are still seeing this error then it could mean something else is preventing this message from getting through (perhaps a firewall at the ISP level?)

**Comment by MythB** [comment]
Oh! I just reset my router settings and it works now, Samethings happend on my router im sorry for the fuss

**Comment by efroemling** [comment]
No worries. Glad it's working now!
