### ISSUE TITLE
While typing in the chatbox, some alphabets don't get typed. 

### ISSUE THREAD

**Issue by astrojade** [efroemling/ballistica#98]
This is a very recent bug, i noticed it like 2 3 days ago, Every server has the same kind of problem. You can clearly see that all the keys are working becoz im typing with the same keyboard. First i thought maybe only in my game its the same problem. But then i noticed someone else typing something fast and alphabets were omitted after he posted it. I needed to press it alot of times to get it to register in the chatbox. Keys like the Y and D key were missing. i will send a video later regarding this problem.

**Comment by efroemling** [comment]
Thanks for any info you can provide. First, though, which platform are you seeing this on?

**Comment by astrojade** [comment]
The bug got resolved. Thanks.
